// Turbo → vx migration: the RENDERING half. The mapping itself lives in
// `turbo()` (which runs it live); this file turns turbo's global
// fields into a root vx-preset.ts that each generated config imports and
// spreads — TypeScript composition replaces turbo's global config.

import path from 'node:path'
import {
  type GeneratedProject,
  type MigrationFormat,
  type MigrationPlan,
  PERSISTENT_TODO,
  type ProjectMeta,
  quoteTsLiteral as quote,
} from '@vzn/vx'
import { mapTurboWorkspace, type TurboGlobal } from './turbo/turbo-map.js'

/** `path.relative` with forward slashes — the shape an ESM specifier or a report line needs. */
function relPosix(from: string, to: string): string {
  return path.relative(from, to).split(path.sep).join('/')
}

/** The preset takes the configs' extension: plain arrays either way. */
function presetFile(format: MigrationFormat): string {
  return `vx-preset.${format}`
}

/** The preset export each global field becomes. */
const PRESET_NAMES: Record<TurboGlobal, string> = {
  inputs: 'globalInputs',
  env: 'globalEnvInputs',
  pass: 'globalPassThroughEnv',
}

export async function migrateTurbo(
  root: string,
  metas: readonly ProjectMeta[],
  format: MigrationFormat = 'ts',
): Promise<MigrationPlan> {
  const mapping = await mapTurboWorkspace(root, metas, {
    splice: (kind) => [{ raw: `...${PRESET_NAMES[kind]}` }],
    persistentTodo: PERSISTENT_TODO,
  })

  const projects: GeneratedProject[] = mapping.projects.map((p) => {
    const used = new Set<string>()
    for (const t of p.tasks) for (const kind of t.uses) used.add(PRESET_NAMES[kind])
    return {
      name: p.name,
      dir: p.dir,
      importLines: presetImportLines(used, root, p.dir, format),
      tasks: p.tasks.map(({ name, todos, task }) => ({ name, todos, task })),
    }
  })

  const { inputs, env, pass } = mapping.globals
  const extraFiles: MigrationPlan['extraFiles'] = []
  if (inputs.length > 0 || env.length > 0 || pass.length > 0) {
    extraFiles.push({ relPath: presetFile(format), contents: renderPreset(inputs, env, pass) })
  }

  return { headerNotes: [], projects, extraFiles, notes: mapping.notes }
}

function presetImportLines(
  used: ReadonlySet<string>,
  root: string,
  dir: string,
  format: MigrationFormat,
): string[] {
  if (used.size === 0) return []
  const rel = relPosix(dir, path.join(root, presetFile(format)))
  const spec = rel.startsWith('.') ? rel : `./${rel}`
  return [`import { ${[...used].sort().join(', ')} } from '${spec}'`]
}

function renderPreset(inputs: string[], env: string[], pass: string[]): string {
  // Escape each entry via the shared `quote()` — a turbo.json global (a file
  // glob, or an env name a user hand-wrote) may contain a `'`/`\`/newline that
  // would otherwise splice into a malformed, unloadable `vx-preset.ts`.
  const arr = (xs: string[]): string => `[${xs.map(quote).join(', ')}]`
  const lines = [
    '// Generated by `vx migrate` from turbo.json. TypeScript composition',
    "// replaces turbo's global fields: each vx.config.ts imports these",
    '// arrays and spreads them into the matching task fields.',
  ]
  if (inputs.length > 0) {
    lines.push(
      '',
      '// From globalDependencies — workspace-root-relative, spread into each',
      '// task’s cache.inputs.workspaceFiles (the $TURBO_ROOT$ equivalent).',
      `export const globalInputs = ${arr(inputs)}`,
    )
  }
  if (env.length > 0) {
    lines.push(
      '',
      '// From globalEnv: cache inputs AND passed through to every task',
      '// (vx child environments are isolated; see docs/schema.md).',
      `export const globalEnvInputs = ${arr(env)}`,
    )
  }
  if (pass.length > 0) {
    lines.push(
      '',
      '// From globalPassThroughEnv: forwarded to every task, never hashed.',
      `export const globalPassThroughEnv = ${arr(pass)}`,
    )
  }
  lines.push('')
  return lines.join('\n')
}
