// vx-migrate's command lines are a 1.0 contract surface (docs/design/
// versioning-1.0.md). `vx-migrate` is typed by people and CI scripts, and
// `nx-exec`, `nx-env` and `lage-worker` are typed by the configs vx-migrate
// WRITES: a vx.config.ts generated by 1.0 must still run under every 1.x,
// so their argv grammar cannot change under it. Each bin is spawned for its
// `--help` (the usage line is the grammar: its leading positionals and each
// flag it names, one line each, so a flag added is no break) and for a
// usage error, and
// `vx-migrate --from` is asked which sources it takes;
// `tests/contract/cli.txt` records the answers. A lost line is a break the
// break law sees.
//
// Regenerate after a deliberate change, then review the diff:
//   VX_UPDATE_CONTRACT=1 bun test tests/contract-cli.test.ts

import { mkdtempSync, readFileSync, realpathSync, rmSync, writeFileSync } from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { afterAll, expect, it } from 'bun:test'
import { parseMigrateArgs } from '../src/index.js'

const SRC = path.join(import.meta.dir, '..', 'src')
const RECORD = path.join(import.meta.dir, 'contract', 'cli.txt')
const CWD = realpathSync(mkdtempSync(path.join(os.tmpdir(), 'vx-migrate-cli-')))
afterAll(() => rmSync(CWD, { recursive: true, force: true }))

/** Each bin as its shebang runs it, and an argv its parser refuses. */
const BINS: ReadonlyArray<readonly [string, readonly string[], readonly string[]]> = [
  ['vx-migrate', [process.execPath, path.join(SRC, 'bin.ts')], ['--no-such-flag']],
  ['nx-exec', ['node', path.join(SRC, 'nx-exec.cjs')], []],
  ['nx-env', ['node', path.join(SRC, 'nx-env.cjs')], []],
  ['lage-worker', ['node', path.join(SRC, 'lage-worker.cjs')], []],
]

/** Sources `--from` could name; the record keeps the ones it takes. */
const FROM = ['turbo', 'nx', 'moon', 'wireit', 'lage', 'scripts', 'rush', 'lerna', 'bazel', 'pnpm']

function spawn(cmd: readonly string[]): { code: number | null; stdout: string } {
  const r = Bun.spawnSync({
    cmd: [...cmd],
    cwd: CWD,
    env: { ...process.env, NO_COLOR: '1' },
    stdout: 'pipe',
    stderr: 'pipe',
  })
  return { code: r.exitCode, stdout: r.stdout.toString() }
}

it('each bin answers as tests/contract/cli.txt records', () => {
  const lines: string[] = []
  for (const [name, run, refused] of BINS) {
    const help = spawn([...run, '--help'])
    lines.push(`${name} --help: exit ${help.code}`)
    const usage = help.stdout.split('\n')[0]!
    expect(usage.startsWith(`usage: ${name} `)).toBe(true)
    const words = usage.slice(`usage: ${name} `.length).split(' ')
    const lead = words.slice(
      0,
      words.findIndex((w) => !w.startsWith('<')),
    )
    lines.push(`${name} argv starts: ${lead.join(' ') || '(a flag)'}`)
    for (const flag of new Set(usage.match(/--[a-zA-Z][a-zA-Z-]*/g) ?? []))
      lines.push(`${name} ${flag}`)
    lines.push(
      `${name} ${refused.join(' ') || '(no arguments)'}: exit ${spawn([...run, ...refused]).code}`,
    )
  }
  for (const v of FROM)
    if (parseMigrateArgs(['--from', v]).error === undefined) lines.push(`vx-migrate --from ${v}`)
  const text = lines.join('\n') + '\n'
  if (process.env['VX_UPDATE_CONTRACT'] === '1' && process.env['CI'] !== 'true') {
    writeFileSync(RECORD, text)
  }
  expect(text).toBe(readFileSync(RECORD, 'utf8'))
}, 30_000)
