// yarn.lock: berry per workspace through descriptors; classic as one root
// digest; and the plugin end to end.
import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { afterEach, beforeEach, describe, expect, it } from 'bun:test'
import { planRun, type Logger } from '@vzn/vx'
import { localWorkspaceSource } from './helpers/local-workspace.js'
import { affectedIds, commitAll, moved } from './helpers/affected.js'
import { yarn } from '../src/index.js'
import { importerDigests, parseLockfile } from '../src/yarn.js'
import { lowHalfGlobals } from './helpers/low-half.js'

const PLUGIN_INDEX = path.resolve(import.meta.dir, '..', 'src', 'index.ts')

function silent(): Logger {
  return {
    runStart() {},
    taskStart() {},
    taskStdout() {},
    taskStderr() {},
    taskComplete() {},
    runStatus() {},
    runEnd() {},
    status() {},
  } as never
}

/** Berry: `a` → foo → bar; `b` → baz; `c` → workspace `b`. */
function berry(opts: { bar?: string; baz?: string; cacheKey?: string; ts?: string } = {}): string {
  const bar = opts.bar ?? '2.0.0'
  const ts = opts.ts ?? '5.0.0'
  const baz = opts.baz ?? '3.0.0'
  return `# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 8
  cacheKey: ${opts.cacheKey ?? '10c0'}

"a@workspace:packages/a":
  version: 0.0.0-use.local
  resolution: "a@workspace:packages/a"
  dependencies:
    foo: "npm:^1"
  languageName: unknown
  linkType: soft

"b@workspace:*, b@workspace:packages/b":
  version: 0.0.0-use.local
  resolution: "b@workspace:packages/b"
  dependencies:
    baz: "npm:^3"
  languageName: unknown
  linkType: soft

"bar@npm:^2":
  version: ${bar}
  resolution: "bar@npm:${bar}"
  checksum: 10c0/bar${bar}
  languageName: node
  linkType: hard

"baz@npm:^3":
  version: ${baz}
  resolution: "baz@npm:${baz}"
  checksum: 10c0/baz${baz}
  languageName: node
  linkType: hard

"c@workspace:packages/c":
  version: 0.0.0-use.local
  resolution: "c@workspace:packages/c"
  dependencies:
    b: "workspace:*"
  languageName: unknown
  linkType: soft

"foo@npm:^1, foo@npm:^1.0.0":
  version: 1.0.0
  resolution: "foo@npm:1.0.0"
  dependencies:
    bar: "npm:^2"
  checksum: 10c0/foo
  languageName: node
  linkType: hard

"ws@workspace:.":
  version: 0.0.0-use.local
  resolution: "ws@workspace:."
  dependencies:
    typescript: "npm:^5"
  languageName: unknown
  linkType: soft

"typescript@npm:^5":
  version: ${ts}
  resolution: "typescript@npm:${ts}"
  checksum: 10c0/ts${ts}
  languageName: node
  linkType: hard
`
}

/** Classic: one flat tree, every descriptor at the root. */
function classic(bar = '2.0.0'): string {
  return `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


bar@^2:
  version "${bar}"
  resolved "https://r/bar-${bar}.tgz#abc"
  integrity sha512-bar${bar}

"foo@^1", "foo@^1.0.0":
  version "1.0.0"
  resolved "https://r/foo-1.0.0.tgz#def"
  integrity sha512-foo
  dependencies:
    bar "^2"
`
}

/**
 * Yarn 4 catalogs, in the shape a real Yarn 4.18.1 install writes: a
 * workspace's `catalog:` / `catalog:odd` dependency is recorded as that
 * literal, and the range the catalog names gets its own entry that
 * nothing in the file points at. `a` → `catalog:` is-number (^6, or ^7
 * with `seven`); `b` → is-odd → is-number ^6; `c` → workspace `a`; `e`
 * → `catalog:odd` is-even.
 */
function catalogLock(opts: { seven?: string; isEven?: string } = {}): string {
  const even = opts.isEven ?? '1.0.0'
  const seven =
    opts.seven === undefined
      ? ''
      : `"is-number@npm:^7.0.0":
  version: ${opts.seven}
  resolution: "is-number@npm:${opts.seven}"
  checksum: 10c0/number${opts.seven}
  languageName: node
  linkType: hard

`
  return `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 10
  cacheKey: 10c0

"a@workspace:*, a@workspace:packages/a":
  version: 0.0.0-use.local
  resolution: "a@workspace:packages/a"
  dependencies:
    is-number: "catalog:"
  languageName: unknown
  linkType: soft

"b@workspace:packages/b":
  version: 0.0.0-use.local
  resolution: "b@workspace:packages/b"
  dependencies:
    is-odd: "npm:^3.0.1"
  languageName: unknown
  linkType: soft

"c@workspace:packages/c":
  version: 0.0.0-use.local
  resolution: "c@workspace:packages/c"
  dependencies:
    a: "workspace:*"
  languageName: unknown
  linkType: soft

"e@workspace:packages/e":
  version: 0.0.0-use.local
  resolution: "e@workspace:packages/e"
  dependencies:
    is-even: "catalog:odd"
  languageName: unknown
  linkType: soft

"is-even@npm:^1.0.0":
  version: ${even}
  resolution: "is-even@npm:${even}"
  checksum: 10c0/even${even}
  languageName: node
  linkType: hard

"is-number@npm:^6.0.0":
  version: 6.0.0
  resolution: "is-number@npm:6.0.0"
  checksum: 10c0/number6.0.0
  languageName: node
  linkType: hard

${seven}"is-odd@npm:^3.0.1":
  version: 3.0.1
  resolution: "is-odd@npm:3.0.1"
  dependencies:
    is-number: "npm:^6.0.0"
  checksum: 10c0/odd3.0.1
  languageName: node
  linkType: hard

"root@workspace:.":
  version: 0.0.0-use.local
  resolution: "root@workspace:."
  languageName: unknown
  linkType: soft
`
}

const digests = (text: string) => importerDigests(parseLockfile(text))

/** The workspace dirs whose digest differs between two lockfiles, sorted. */
function movedDirs(before: string, after: string): string[] {
  const b = digests(before)
  const a = digests(after)
  return [...a.keys()].filter((dir) => a.get(dir) !== b.get(dir)).sort()
}

describe('workspace digests (yarn berry)', () => {
  it('two lockfile globals whose digests share a low half still part the digests (item 682)', () => {
    // Folded as a seed, Bun's xxHash3 would read only the low half of the
    // global's digest and the two would agree.
    const parsed = parseLockfile(berry())
    const [g1, g2] = lowHalfGlobals()
    const a = importerDigests({ ...parsed, global: g1 })
    const b = importerDigests({ ...parsed, global: g2 })
    expect(a.get('packages/a')).not.toBe(b.get('packages/a'))
  })

  it('a transitive bump moves the workspaces that reach it and no other', () => {
    const before = digests(berry())
    const after = digests(berry({ bar: '2.0.1' }))
    expect([...before.keys()].sort()).toEqual(['.', 'packages/a', 'packages/b', 'packages/c'])
    expect(after.get('packages/a')).not.toBe(before.get('packages/a'))
    expect(after.get('packages/b')).toBe(before.get('packages/b'))
    expect(after.get('.')).toBe(before.get('.'))
  })

  it("a workspace dependency folds the linked workspace's reach", () => {
    const before = digests(berry())
    const after = digests(berry({ baz: '3.0.1' }))
    expect(after.get('packages/b')).not.toBe(before.get('packages/b'))
    expect(after.get('packages/c')).not.toBe(before.get('packages/c'))
    expect(after.get('packages/a')).toBe(before.get('packages/a'))
  })

  it('the metadata cache key moves every workspace', () => {
    const before = digests(berry())
    const after = digests(berry({ cacheKey: '11c0' }))
    for (const dir of before.keys()) expect(after.get(dir)).not.toBe(before.get(dir))
  })
})

describe('Yarn 4 catalogs (turborepo#12635)', () => {
  it('a catalog bump `^6 → ^7` moves the workspace that names `catalog:` and what links it', () => {
    // The file records `is-number: "catalog:"`, never the range: folded
    // as that literal, the bump left every digest byte-identical.
    expect(movedDirs(catalogLock(), catalogLock({ seven: '7.0.0' }))).toEqual([
      'packages/a',
      'packages/c',
    ])
  })

  it('a bump inside the catalog range moves the workspace that names `catalog:`', () => {
    // `yarn up is-number` with `.yarnrc.yml` unchanged: only the entry
    // nothing points at moves, so `.yarnrc.yml` cannot carry it.
    expect(movedDirs(catalogLock({ seven: '7.0.0' }), catalogLock({ seven: '7.0.1' }))).toEqual([
      'packages/a',
      'packages/c',
    ])
  })

  it('a named catalog (`catalog:<name>`) reaches the entries of its package', () => {
    expect(movedDirs(catalogLock(), catalogLock({ isEven: '1.0.1' }))).toEqual(['packages/e'])
  })

  it('a scoped package named by a catalog reaches its entries', () => {
    const lock = (v: string) => `__metadata:
  version: 10
  cacheKey: 10c0

"a@workspace:packages/a":
  version: 0.0.0-use.local
  resolution: "a@workspace:packages/a"
  dependencies:
    "@types/node": "catalog:"
  languageName: unknown
  linkType: soft

"@types/node@npm:^22.0.0":
  version: ${v}
  resolution: "@types/node@npm:${v}"
  checksum: 10c0/node${v}
  languageName: node
  linkType: hard
`
    expect(movedDirs(lock('22.0.0'), lock('22.0.1'))).toEqual(['packages/a'])
  })
})

describe('classic yarn.lock', () => {
  it('is one root digest that a change anywhere moves', () => {
    const before = digests(classic())
    expect([...before.keys()]).toEqual(['.'])
    expect(digests(classic('2.0.1')).get('.')).not.toBe(before.get('.'))
    expect(digests(classic()).get('.')).toBe(before.get('.'))
  })

  it('reads dependencies and multi-descriptor keys', () => {
    const lock = parseLockfile(classic())
    expect(lock.generation).toBe('classic')
    expect(lock.descriptors.get('foo@^1.0.0')).toBe('foo@^1')
    expect(lock.entries.get('foo@^1')!.deps.get('bar')).toBe('^2')
  })

  it('refuses what is neither generation', () => {
    expect(() => parseLockfile('hello: world\n')).toThrow(/neither a classic/)
  })

  it('a descriptor moving to another entry moves the digest (item 902)', () => {
    // `foo@^1.0.0` re-pointed from the 1.0.0 entry to the 1.1.0 one, as a
    // deduplication or `yarn upgrade` writes it: every entry's version,
    // url and integrity are unchanged, yet a workspace now installs 1.1.0.
    const two = (older: string, newer: string) => `# yarn lockfile v1


${older}:
  version "1.0.0"
  resolved "https://r/foo-1.0.0.tgz"
  integrity sha512-foo100

${newer}:
  version "1.1.0"
  resolved "https://r/foo-1.1.0.tgz"
  integrity sha512-foo110
`
    const before = digests(two('"foo@1.0.0", "foo@^1.0.0"', '"foo@^1.1.0"')).get('.')
    expect(digests(two('"foo@1.0.0"', '"foo@^1.0.0", "foo@^1.1.0"')).get('.')).not.toBe(before)
    // CONTROL: the same descriptors in another order are the same file.
    expect(digests(two('"foo@^1.0.0", "foo@1.0.0"', '"foo@^1.1.0"')).get('.')).toBe(before)
  })
})

describe('yarn() declared', () => {
  let root: string
  const BUILD =
    "export default { tasks: { build: { exec: { command: 'echo built' }, cache: { inputs: { files: ['src/**'] }, outputs: { files: [] } } } } }\n"
  beforeEach(async () => {
    root = await mkdtemp(path.join(tmpdir(), 'vx-yarn-'))
    await writeFile(
      path.join(root, 'package.json'),
      JSON.stringify({ name: 'ws', private: true, workspaces: ['packages/*'] }),
    )
    for (const name of ['a', 'b', 'c']) {
      const dir = path.join(root, 'packages', name)
      await mkdir(path.join(dir, 'src'), { recursive: true })
      await writeFile(path.join(dir, 'package.json'), JSON.stringify({ name, version: '1.0.0' }))
      await writeFile(path.join(dir, 'src', 'index.js'), `// ${name}\n`)
      await writeFile(path.join(dir, 'vx.config.mjs'), BUILD)
    }
    await writeFile(path.join(root, 'yarn.lock'), berry())
    await writeFile(
      path.join(root, 'vx.workspace.mjs'),
      localWorkspaceSource(['yarn()'], `import { yarn } from ${JSON.stringify(PLUGIN_INDEX)}\n`),
    )
    Bun.spawnSync({ cmd: ['git', 'init', '-q'], cwd: root })
  })
  afterEach(async () => {
    await rm(root, { recursive: true, force: true })
  })

  it('a transitive bump re-keys only the projects that reach it', async () => {
    const hashes = async () => {
      const plan = await planRun({ cwd: root, tasks: ['build'], log: silent() })
      return Object.fromEntries(plan.tasks.map((t) => [t.node.id, t.hash]))
    }
    const before = await hashes()
    await writeFile(path.join(root, 'yarn.lock'), berry({ bar: '2.0.1' }))
    const after = await hashes()
    expect(after['a#build']).not.toBe(before['a#build'])
    expect(after['b#build']).toBe(before['b#build'])
    expect(after['c#build']).toBe(before['c#build'])
  })

  it('a root devDependency bump re-keys and selects every project: the root `.bin` is on every PATH', async () => {
    // The root package's tools run from the root `node_modules/.bin`,
    // which core puts on every task's PATH, and Node resolution walks up
    // to the root `node_modules`: a bump that moved no project's key
    // replayed the old tool's output (nx#36415 class, 2026-09-24).
    const plan = async () => {
      const p = await planRun({ cwd: root, tasks: ['build'], log: silent() })
      return Object.fromEntries(p.tasks.map((t) => [t.node.id, t.hash]))
    }
    commitAll(root)
    const before = await plan()
    // CONTROL: a package only `a` reaches still moves only a's key.
    await writeFile(path.join(root, 'yarn.lock'), berry({ bar: '2.0.1' }))
    expect(moved(before, await plan())).toEqual(['a#build'])
    expect(affectedIds(root, 'build')).toEqual(['a#build'])
    await writeFile(path.join(root, 'yarn.lock'), berry({ ts: '5.1.0' }))
    expect(moved(before, await plan())).toEqual(['a#build', 'b#build', 'c#build'])
    expect(affectedIds(root, 'build')).toEqual(['a#build', 'b#build', 'c#build'])
  })

  describe('Yarn 4 catalogs (turborepo#12635)', () => {
    const rc = (range: string) =>
      writeFile(
        path.join(root, '.yarnrc.yml'),
        `nodeLinker: node-modules\ncatalog:\n  is-number: ${range}\n`,
      )
    const plan = async () => {
      const p = await planRun({ cwd: root, tasks: ['build'], log: silent() })
      return Object.fromEntries(p.tasks.map((t) => [t.node.id, t.hash]))
    }

    it('a bump inside the catalog range re-keys and selects the projects that reach it', async () => {
      await rc('^7.0.0')
      await writeFile(path.join(root, 'yarn.lock'), catalogLock({ seven: '7.0.0' }))
      commitAll(root)
      const before = await plan()
      await writeFile(path.join(root, 'yarn.lock'), catalogLock({ seven: '7.0.1' }))
      expect(moved(before, await plan())).toEqual(['a#build', 'c#build'])
      expect(affectedIds(root, 'build')).toEqual(['a#build', 'c#build'])
    })

    it('a catalog flip the lockfile does not record re-keys and selects every project', async () => {
      // A real Yarn 4.18.1 install with `^6` and `^7` both already
      // resolved (another workspace depends on `^7` directly) rewrote
      // not one byte of yarn.lock when the catalog flipped `^6 → ^7`,
      // while `a`'s node_modules moved from 6.0.0 to 7.0.0. Only
      // `.yarnrc.yml` changed, so the workspace fingerprint folds it.
      await rc('^6.0.0')
      await writeFile(path.join(root, 'yarn.lock'), catalogLock({ seven: '7.0.0' }))
      commitAll(root)
      const before = await plan()
      await rc('^7.0.0')
      expect(moved(before, await plan())).toEqual(['a#build', 'b#build', 'c#build'])
      expect(affectedIds(root, 'build')).toEqual(['a#build', 'b#build', 'c#build'])
    })
  })

  it('refuses an unknown scope', () => {
    expect(() => yarn({ scope: 'x' as never })).toThrow(
      /yarn\(\) scope must be 'project' or 'workspace'/,
    )
  })
})

// The mutation sweep of item 803: each row changes one input the digest
// must read and names the workspaces whose key must move. Before it, each
// could be dropped from yarn.ts with the suite green.
describe('every input the yarn digest must read', () => {
  const ALL = ['.', 'packages/a', 'packages/b', 'packages/c']

  it('an entry with no `resolution` is keyed by its descriptors, never merged with another', () => {
    const strip = (text: string) =>
      text
        .replace(/\n {2}resolution: "bar@npm:[^"]*"/, '')
        .replace(/\n {2}resolution: "baz@npm:[^"]*"/, '')
    expect(strip(berry())).not.toContain('resolution: "bar@')
    expect(movedDirs(strip(berry()), strip(berry({ baz: '3.0.1' })))).toEqual([
      'packages/b',
      'packages/c',
    ])
  })

  it('a peer dependency is followed like any other', () => {
    const peer = (text: string) =>
      text.replace(
        '"baz@npm:^3":\n  version:',
        '"baz@npm:^3":\n  peerDependencies:\n    bar: "npm:^2"\n  version:',
      )
    expect(movedDirs(peer(berry()), peer(berry({ bar: '2.0.1' })))).toEqual(ALL.slice(1))
  })

  it("an entry's checksum alone moves what reaches it", () => {
    expect(
      movedDirs(berry(), berry().replace('checksum: 10c0/foo\n', 'checksum: 10c0/foo2\n')),
    ).toEqual(['packages/a'])
  })

  it('a dependency resolves through the second descriptor of a multi-descriptor key', () => {
    const second = (text: string) => text.replace('    foo: "npm:^1"\n', '    foo: "npm:^1.0.0"\n')
    expect(second(berry())).not.toBe(berry())
    expect(movedDirs(second(berry()), second(berry({ bar: '2.0.1' })))).toEqual(['packages/a'])
  })

  it('the metadata version alone moves every workspace', () => {
    expect(movedDirs(berry(), berry().replace('  version: 8\n', '  version: 9\n'))).toEqual(ALL)
  })

  it('a `workspace:` range the keys do not list resolves to the workspace by name', () => {
    const caret = (text: string) => text.replace('    b: "workspace:*"\n', '    b: "workspace:^"\n')
    expect(caret(berry())).not.toBe(berry())
    expect(movedDirs(caret(berry()), caret(berry({ baz: '3.0.1' })))).toEqual([
      'packages/b',
      'packages/c',
    ])
  })

  it('a bare range resolves to the entry keyed with `npm:`', () => {
    const bare = (text: string) => text.replace('    foo: "npm:^1"\n', '    foo: "^1"\n')
    expect(movedDirs(bare(berry()), bare(berry({ bar: '2.0.1' })))).toEqual(['packages/a'])
  })

  it('an unresolved dependency still folds its range', () => {
    const ghost = (range: string) =>
      berry().replace('    foo: "npm:^1"\n', `    foo: "npm:^1"\n    ghost: "npm:${range}"\n`)
    expect(movedDirs(ghost('^9'), ghost('^10'))).toEqual(['packages/a'])
  })

  it.each([
    ['version', '  version "2.0.0"\n', '  version "2.0.9"\n'],
    [
      'resolved',
      '  resolved "https://r/bar-2.0.0.tgz#abc"\n',
      '  resolved "https://r/bar-2.0.0.tgz#abd"\n',
    ],
    ['integrity', '  integrity sha512-bar2.0.0\n', '  integrity sha512-bar2.0.9\n'],
  ])('classic: the `%s` field alone moves the root digest', (_field, before, after) => {
    const text = classic()
    expect(text).toContain(before)
    expect(digests(text.replace(before, after)).get('.')).not.toBe(digests(text).get('.'))
  })

  it('classic: optional dependencies and a quoted scoped name are read', () => {
    const text = classic().replace(
      '  dependencies:\n    bar "^2"\n',
      '  dependencies:\n    "@s/x" "^1"\n  optionalDependencies:\n    bar "^2"\n',
    )
    const deps = parseLockfile(text).entries.get('foo@^1')!.deps
    expect([...deps]).toEqual([
      ['@s/x', '^1'],
      ['bar', '^2'],
    ])
  })

  it('classic: CRLF line endings and entry order never move the digest', () => {
    const text = classic()
    const crlf = text.replaceAll('\n', '\r\n')
    const [header, ...entries] = text.split('\n\n\n')
    const swapped = [header, entries.join('').split('\n\n').reverse().join('\n\n')].join('\n\n\n')
    expect(swapped).not.toBe(text)
    expect(digests(crlf)).toEqual(digests(text))
    expect(digests(swapped)).toEqual(digests(text))
  })
})
