// yarn.lock: berry per workspace through descriptors; classic as one root
// digest; and the plugin end to end.
import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { afterEach, beforeEach, describe, expect, it } from 'bun:test'
import { planRun, type Logger } from '@vzn/vx'
import { localWorkspaceSource } from './helpers/local-workspace.js'
import { yarn } from '../src/index.js'
import { importerDigests, parseLockfile } from '../src/yarn.js'

const PLUGIN_INDEX = path.resolve(import.meta.dir, '..', 'src', 'index.ts')

function silent(): Logger {
  return {
    runStart() {},
    taskStart() {},
    taskStdout() {},
    taskStderr() {},
    taskComplete() {},
    runStatus() {},
    runEnd() {},
    status() {},
  } as never
}

/** Berry: `a` → foo → bar; `b` → baz; `c` → workspace `b`. */
function berry(opts: { bar?: string; baz?: string; cacheKey?: string } = {}): string {
  const bar = opts.bar ?? '2.0.0'
  const baz = opts.baz ?? '3.0.0'
  return `# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 8
  cacheKey: ${opts.cacheKey ?? '10c0'}

"a@workspace:packages/a":
  version: 0.0.0-use.local
  resolution: "a@workspace:packages/a"
  dependencies:
    foo: "npm:^1"
  languageName: unknown
  linkType: soft

"b@workspace:*, b@workspace:packages/b":
  version: 0.0.0-use.local
  resolution: "b@workspace:packages/b"
  dependencies:
    baz: "npm:^3"
  languageName: unknown
  linkType: soft

"bar@npm:^2":
  version: ${bar}
  resolution: "bar@npm:${bar}"
  checksum: 10c0/bar${bar}
  languageName: node
  linkType: hard

"baz@npm:^3":
  version: ${baz}
  resolution: "baz@npm:${baz}"
  checksum: 10c0/baz${baz}
  languageName: node
  linkType: hard

"c@workspace:packages/c":
  version: 0.0.0-use.local
  resolution: "c@workspace:packages/c"
  dependencies:
    b: "workspace:*"
  languageName: unknown
  linkType: soft

"foo@npm:^1, foo@npm:^1.0.0":
  version: 1.0.0
  resolution: "foo@npm:1.0.0"
  dependencies:
    bar: "npm:^2"
  checksum: 10c0/foo
  languageName: node
  linkType: hard

"ws@workspace:.":
  version: 0.0.0-use.local
  resolution: "ws@workspace:."
  dependencies:
    typescript: "npm:^5"
  languageName: unknown
  linkType: soft

"typescript@npm:^5":
  version: 5.0.0
  resolution: "typescript@npm:5.0.0"
  checksum: 10c0/ts
  languageName: node
  linkType: hard
`
}

/** Classic: one flat tree, every descriptor at the root. */
function classic(bar = '2.0.0'): string {
  return `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


bar@^2:
  version "${bar}"
  resolved "https://r/bar-${bar}.tgz#abc"
  integrity sha512-bar${bar}

"foo@^1", "foo@^1.0.0":
  version "1.0.0"
  resolved "https://r/foo-1.0.0.tgz#def"
  integrity sha512-foo
  dependencies:
    bar "^2"
`
}

const digests = (text: string) => importerDigests(parseLockfile(text))

describe('workspace digests (yarn berry)', () => {
  it('a transitive bump moves the workspaces that reach it and no other', () => {
    const before = digests(berry())
    const after = digests(berry({ bar: '2.0.1' }))
    expect([...before.keys()].sort()).toEqual(['.', 'packages/a', 'packages/b', 'packages/c'])
    expect(after.get('packages/a')).not.toBe(before.get('packages/a'))
    expect(after.get('packages/b')).toBe(before.get('packages/b'))
    expect(after.get('.')).toBe(before.get('.'))
  })

  it("a workspace dependency folds the linked workspace's reach", () => {
    const before = digests(berry())
    const after = digests(berry({ baz: '3.0.1' }))
    expect(after.get('packages/b')).not.toBe(before.get('packages/b'))
    expect(after.get('packages/c')).not.toBe(before.get('packages/c'))
    expect(after.get('packages/a')).toBe(before.get('packages/a'))
  })

  it('the metadata cache key moves every workspace', () => {
    const before = digests(berry())
    const after = digests(berry({ cacheKey: '11c0' }))
    for (const dir of before.keys()) expect(after.get(dir)).not.toBe(before.get(dir))
  })
})

describe('classic yarn.lock', () => {
  it('is one root digest that a change anywhere moves', () => {
    const before = digests(classic())
    expect([...before.keys()]).toEqual(['.'])
    expect(digests(classic('2.0.1')).get('.')).not.toBe(before.get('.'))
    expect(digests(classic()).get('.')).toBe(before.get('.'))
  })

  it('reads dependencies and multi-descriptor keys', () => {
    const lock = parseLockfile(classic())
    expect(lock.generation).toBe('classic')
    expect(lock.descriptors.get('foo@^1.0.0')).toBe('foo@^1')
    expect(lock.entries.get('foo@^1')!.deps.get('bar')).toBe('^2')
  })

  it('refuses what is neither generation', () => {
    expect(() => parseLockfile('hello: world\n')).toThrow(/neither a classic/)
  })
})

describe('yarn() declared', () => {
  let root: string
  const BUILD =
    "export default { tasks: { build: { exec: { command: 'echo built' }, cache: { inputs: { files: ['src/**'] }, outputs: { files: [] } } } } }\n"
  beforeEach(async () => {
    root = await mkdtemp(path.join(tmpdir(), 'vx-yarn-'))
    await writeFile(
      path.join(root, 'package.json'),
      JSON.stringify({ name: 'ws', private: true, workspaces: ['packages/*'] }),
    )
    for (const name of ['a', 'b', 'c']) {
      const dir = path.join(root, 'packages', name)
      await mkdir(path.join(dir, 'src'), { recursive: true })
      await writeFile(path.join(dir, 'package.json'), JSON.stringify({ name, version: '1.0.0' }))
      await writeFile(path.join(dir, 'src', 'index.js'), `// ${name}\n`)
      await writeFile(path.join(dir, 'vx.config.mjs'), BUILD)
    }
    await writeFile(path.join(root, 'yarn.lock'), berry())
    await writeFile(
      path.join(root, 'vx.workspace.mjs'),
      localWorkspaceSource(['yarn()'], `import { yarn } from ${JSON.stringify(PLUGIN_INDEX)}\n`),
    )
    Bun.spawnSync({ cmd: ['git', 'init', '-q'], cwd: root })
  })
  afterEach(async () => {
    await rm(root, { recursive: true, force: true })
  })

  it('a transitive bump re-keys only the projects that reach it', async () => {
    const hashes = async () => {
      const plan = await planRun({ cwd: root, tasks: ['build'], log: silent() })
      return Object.fromEntries(plan.tasks.map((t) => [t.node.id, t.hash]))
    }
    const before = await hashes()
    await writeFile(path.join(root, 'yarn.lock'), berry({ bar: '2.0.1' }))
    const after = await hashes()
    expect(after['a#build']).not.toBe(before['a#build'])
    expect(after['b#build']).toBe(before['b#build'])
    expect(after['c#build']).toBe(before['c#build'])
  })

  it('refuses an unknown scope', () => {
    expect(() => yarn({ scope: 'x' as never })).toThrow(
      /yarn\(\) scope must be 'project' or 'workspace'/,
    )
  })
})
