// REPRO: `vx migrate --from nx` synthesizes a meta for the workspace-root
// project (Nx routinely has root targets), but workspace discovery
// (packages/*) does NOT list the root, so the overwrite-conflict check
// `metas.find(m => m.dir === p.dir)` finds nothing for it. An EXISTING
// root vx.config.ts is therefore overwritten WITHOUT --force — the guard
// is supposed to refuse.

import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import { afterEach, beforeEach, describe, expect, it } from 'bun:test'

const BIN = path.resolve(import.meta.dir, '..', 'src', 'bin.ts')
const TIMEOUT = 20_000
let root: string

async function vx(args: string[]): Promise<{ code: number; out: string; err: string }> {
  const proc = Bun.spawn([process.execPath, BIN, ...args], {
    cwd: root,
    env: { ...process.env },
    stdout: 'pipe',
    stderr: 'pipe',
  })
  const [out, err, code] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited,
  ])
  return { code, out, err }
}

describe('REPRO: nx migrate clobbers existing root vx.config.ts', () => {
  beforeEach(async () => {
    root = await mkdtemp(path.join(os.tmpdir(), 'vx-review-root-'))
    // Discovery uses packages/* — the root itself is NOT a discovered project.
    await writeFile(path.join(root, 'pnpm-workspace.yaml'), 'packages:\n  - "packages/*"\n')
    await writeFile(path.join(root, 'package.json'), JSON.stringify({ name: 'root', private: true }))

    // A resolved Nx graph with a ROOT-rooted node that has a target.
    const graph = {
      graph: {
        nodes: {
          'the-root': {
            name: 'the-root',
            data: {
              root: '.',
              targets: {
                lint: { executor: 'nx:run-commands', options: { command: 'eslint .' } },
              },
            },
          },
        },
        dependencies: {},
      },
    }
    await mkdir(path.join(root, '.nx', 'workspace-data'), { recursive: true })
    await writeFile(
      path.join(root, '.nx', 'workspace-data', 'project-graph.json'),
      JSON.stringify(graph),
    )

    // A pre-existing, HAND-WRITTEN root config the user does not want clobbered.
    await writeFile(
      path.join(root, 'vx.config.ts'),
      `export default { /* PRECIOUS HAND-WRITTEN CONFIG */ tasks: {} }\n`,
    )
  })
  afterEach(async () => {
    await rm(root, { recursive: true, force: true })
  })

  it(
    'migrate (no --force) OVERWRITES the existing root vx.config.ts',
    async () => {
      const before = await Bun.file(path.join(root, 'vx.config.ts')).text()
      expect(before).toContain('PRECIOUS HAND-WRITTEN CONFIG')

      const res = await vx(['migrate', '--from', 'nx'])
      // The guard SHOULD have refused (exit 1, "refusing to overwrite").
      // Instead it succeeds and clobbers.
      console.log('exit', res.code, 'err:', res.err.trim(), 'out-tail:', res.out.slice(-200))

      const after = await Bun.file(path.join(root, 'vx.config.ts')).text()
      // Demonstrate the clobber: the precious marker is gone, replaced by
      // the generated header.
      expect(after).not.toContain('PRECIOUS HAND-WRITTEN CONFIG')
      expect(after).toContain('Generated by `vx migrate`')
    },
    TIMEOUT,
  )
})
