// The site imports the repo's `docs/` tree (scripts/import-docs.ts) and
// lists pages by hand in the Starlight sidebar. Two pages were imported and
// reachable from no sidebar entry (2026-09-03: the overview, i.e.
// docs/README.md, and a stale second pitch). This pins both directions:
// every imported top-level page is named in the sidebar, and every sidebar
// link has a page — a hand-listed sidebar cannot drift silently.
//
// It reads only THIS project: the site's own config, its `.gitignore`, and
// the generated content collection. The generated set is what the sidebar
// must agree with, and `import` produces it before this runs.

import { existsSync, readdirSync, readFileSync } from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'bun:test'

const SITE = path.resolve(import.meta.dir, '..')
const CONTENT = path.join(SITE, 'src/content/docs')

/** Top-level pages the last `import` generated, as file names. */
function importedPages(): string[] {
  return readdirSync(CONTENT)
    .filter((f) => f.endsWith('.md'))
    .sort()
}

function sidebarLinks(): Set<string> {
  const cfg = readdirSync(SITE)
    .filter((f) => f.startsWith('astro.config.'))
    .map((f) => readFileSync(path.join(SITE, f), 'utf8'))
    .join('\n')
  return new Set([...cfg.matchAll(/link:\s*'([^']+)'/g)].map((m) => m[1]!))
}

/** The clean URL a generated top-level page is served at. */
function urlOf(file: string): string {
  return `/${file.replace(/\.md$/, '')}/`
}

describe('docs site sidebar coverage', () => {
  const links = sidebarLinks()

  // The site's .gitignore is the manifest of generated top-level pages:
  // import-docs.ts clears exactly that set before regenerating, so a source
  // deleted from docs/ cannot leave a stale page behind — but only while the
  // list and the tree agree.
  it('the site .gitignore lists exactly the imported top-level pages', () => {
    const ignored = readFileSync(path.join(SITE, '.gitignore'), 'utf8')
      .split('\n')
      .map((l) => l.trim())
      .filter((l) => l.startsWith('/src/content/docs/') && l.endsWith('.md'))
      .map((l) => l.slice('/src/content/docs/'.length))
      .sort()
    expect(ignored).toEqual(importedPages())
  })

  it('names every imported top-level page', () => {
    const orphans = importedPages()
      .map(urlOf)
      .filter((u) => !links.has(u))
    expect(orphans).toEqual([])
  })

  it('links only to pages that exist', () => {
    // Guides and concepts are authored here; the rest is generated by
    // `import`, which this task depends on — so the collection is complete
    // when the check runs.
    const missing = [...links].filter((link) => {
      const rel = link.replace(/^\//, '').replace(/\/$/, '')
      return ![`${rel}.md`, `${rel}.mdx`, `${rel}/index.md`, `${rel}/index.mdx`].some((c) =>
        existsSync(path.join(CONTENT, c)),
      )
    })
    expect(missing).toEqual([])
  })
})
