// Every config the docs, the site and the starters show a user is loaded
// by the current schema, so a schema change that would break a documented
// config goes red here. The sources are found, not listed: each ```ts
// fence that calls `defineProject(` or `defineWorkspace(` in
// packages/vx/docs (history and design aside: a record of the past) and in
// the site's hand-authored pages, and every vx.config / vx.workspace
// under examples/. `vx-migrate`'s writers are held the same way by their
// own suites (each written config goes through `loadProjectConfig`).
//
// Each is written to a fresh directory with the @vzn packages linked,
// imported, and handed to the validator the loader uses. The site and
// examples/ live outside packages/vx, which a sandboxed shard cannot read —
// hence the unsafe suite.
import {
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { afterAll, describe, expect, it } from 'bun:test'
import { validateProjectConfig, validateWorkspace } from '../src/workspace/index.js'
import type { ProjectConfig, WorkspaceConfig } from '../src/config.js'

const CORE = path.resolve(import.meta.dir, '..')
const PACKAGES = path.dirname(CORE)
const REPO = path.dirname(PACKAGES)

function walk(dir: string, keep: (p: string) => boolean): string[] {
  const out: string[] = []
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name)
    if (e.isDirectory()) {
      if (e.name !== 'node_modules') out.push(...walk(p, keep))
    } else if (keep(p)) out.push(p)
  }
  return out
}

interface Sample {
  /** Where a reader meets it: `file#n`, the page's nth config. */
  where: string
  /** The page it came from: a fence may import one the page showed before it. */
  page: string
  source: string
  workspace: boolean
  /** The path its first line names (`// presets/ts-build.ts`), if any. */
  named: string | undefined
}

const NAMED = /^\/\/ ([\w./-]+\.[mc]?[jt]s)\n/

function fences(file: string): Sample[] {
  const text = readFileSync(file, 'utf8')
  if (text.includes('# generated by packages/vx-docs/scripts/import-docs.ts')) return []
  const out: Sample[] = []
  let n = 0
  for (const m of text.matchAll(/^```tsx?[^\n]*\n([\s\S]*?)^```/gm)) {
    const source = m[1]!
    const named = NAMED.exec(source)?.[1]
    const workspace = source.includes('defineWorkspace(')
    const config = workspace || source.includes('defineProject(')
    if (!config && named === undefined) continue
    const page = path.relative(REPO, file)
    out.push({ where: config ? `${page}#${++n}` : '', page, source, workspace, named })
  }
  return out
}

/**
 * Config fences that are not programs, each with why. Anything else that
 * fails to load is a doc a user copies and cannot run.
 */
const SKETCHES = new Map([
  ['packages/vx/docs/schema.md#1', 'the grammar of a project config, `<taskName>: TaskConfig`'],
  [
    'packages/vx-docs/src/content/docs/blog/resolved-config-hashing.md#1',
    'a config importing a preset the post describes but does not show',
  ],
])

function corpus(): Sample[] {
  const md = (p: string): boolean => /\.mdx?$/.test(p)
  const docs = path.join(CORE, 'docs')
  const site = path.join(PACKAGES, 'vx-docs', 'src', 'content', 'docs')
  const pages = [
    ...walk(docs, md).filter((p) => !/\/docs\/(history|design)\//.test(p)),
    ...walk(site, md).filter((p) => !/\/docs\/(design|modules)\//.test(p)),
  ]
  const examples = walk(path.join(REPO, 'examples'), (p) =>
    /\/vx\.(config|workspace)\.[mc]?[jt]s$/.test(p),
  ).map((p) => ({
    where: path.relative(REPO, p),
    page: path.relative(REPO, p),
    source: readFileSync(p, 'utf8'),
    workspace: /\/vx\.workspace\./.test(p),
    named: undefined,
  }))
  return [...pages.flatMap(fences), ...examples]
}

const roots: string[] = []
afterAll(() => {
  for (const r of roots) rmSync(r, { recursive: true, force: true })
})

/** A directory where `import … from '@vzn/<pkg>'` reaches this checkout. */
function home(): string {
  const root = mkdtempSync(path.join(os.tmpdir(), 'vx-corpus-'))
  roots.push(root)
  mkdirSync(path.join(root, 'node_modules', '@vzn'), { recursive: true })
  // definePlugin names a plugin by the package.json above it.
  writeFileSync(path.join(root, 'package.json'), '{ "name": "corpus", "type": "module" }')
  for (const dir of readdirSync(PACKAGES)) {
    symlinkSync(path.join(PACKAGES, dir), path.join(root, 'node_modules', '@vzn', dir))
  }
  return root
}

const samples = corpus()

describe('the documented configs load under the current schema', () => {
  it('the corpus finds the configs it exists for', () => {
    // A finder that matched nothing would pass every row below vacuously.
    const where = samples.map((s) => s.where.replace(/#\d+$/, ''))
    expect(samples.filter((s) => s.where !== '').length).toBeGreaterThan(20)
    for (const file of [
      'packages/vx/docs/schema.md',
      'packages/vx-docs/src/content/docs/guides/configure.md',
      'examples/basic/packages/app/vx.config.ts',
      'examples/turbo/vx.workspace.ts',
    ]) {
      expect(where).toContain(file)
    }
    expect(samples.some((s) => s.workspace)).toBe(true)
  })

  it('each sketch it exempts is still one of its configs', () => {
    const where = new Set(samples.map((s) => s.where))
    expect([...SKETCHES.keys()].filter((k) => !where.has(k))).toEqual([])
  })

  const dir = home()
  // Each page's fences share a directory, a named one written at its path,
  // so a config can import the preset the page showed first.
  const pageDir = new Map<string, string>()
  const written = samples.map((s, i) => {
    let d = pageDir.get(s.page)
    if (d === undefined) pageDir.set(s.page, (d = path.join(dir, String(pageDir.size))))
    const rel = s.named ?? `${i}.${s.workspace ? 'vx.workspace' : 'vx.config'}.ts`
    const file = path.join(d, rel)
    mkdirSync(path.dirname(file), { recursive: true })
    writeFileSync(file, s.source)
    return file
  })
  for (const [i, s] of samples.entries()) {
    if (s.where === '' || SKETCHES.has(s.where)) continue
    it(s.where, async () => {
      const mod = (await import(written[i]!)) as { default: unknown }
      if (s.workspace) validateWorkspace(mod.default as WorkspaceConfig, s.where)
      else validateProjectConfig(mod.default as ProjectConfig, s.where)
    })
  }
})
