// The config schema is a 1.0 contract surface (docs/design/versioning-1.0.md):
// every field `vx.config.ts` and `vx.workspace.ts` accept, the values each
// takes, and the words each refusal says. This file pins all three against a
// committed record, `tests/contract/config-schema.json`, so a schema change
// is a reviewed diff of that record and never a side effect.
//
// The record is GENERATED by running the validator, not written from its
// constants (CLAUDE.md: a test that reads the constant it guards is a
// tautology). The levels and their fields are discovered by injecting an
// unknown key at every object node of a valid seed config and reading the
// "allowed:" list the refusal names; each field is then probed with a fixed
// set of values and every outcome recorded. What stays hand-written is the
// seed (a valid value per field) and `LEVEL_TYPES`, which the type checker
// holds to the exported interfaces in src/config.ts: a field the interface
// has and the validator refuses, or the reverse, fails here.
//
// Regenerate after a deliberate change, format, then review the diff:
//   VX_UPDATE_CONTRACT=1 bun test tests/contract-config-schema.test.ts
//   bun src/bin.ts run lint.oxfmt.fix

import { describe, expect, it } from 'bun:test'
import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import type {
  CacheConfig,
  CacheInputs,
  CacheOutputs,
  ExecConfig,
  ExecEnv,
  PersistentConfig,
  ProjectConfig,
  SandboxConfig,
  SandboxDenials,
  SandboxGrants,
  SandboxIgnore,
  TaskConfig,
  WorkspaceConfig,
} from '../src/config.js'
import { validateProjectConfig, validateWorkspace } from '../src/workspace/config-schema.js'

const RECORD = path.join(import.meta.dir, 'contract', 'config-schema.json')
const PROJECT_PATH = '/ws/pkg/vx.config.ts'
const WORKSPACE_PATH = '/ws/vx.workspace.ts'

type Keys<T> = { [K in keyof Required<T>]: true }
const keys = <T>(k: Keys<T>): string[] => Object.keys(k).sort()

/**
 * Each object level the validator checks, by generic path (a record's entry
 * is `*`), with the fields its TypeScript interface declares. `Keys<T>` makes
 * the compiler refuse a literal that misses or adds a key of `T`.
 */
const LEVEL_TYPES: Record<'workspace' | 'project', Record<string, string[]>> = {
  workspace: {
    '': keys<WorkspaceConfig>({
      concurrency: true,
      cacheDir: true,
      timeout: true,
      cacheRetention: true,
      affectedBase: true,
      cacheScope: true,
      rules: true,
      plugins: true,
    }),
    cacheRetention: keys<NonNullable<WorkspaceConfig['cacheRetention']>>({
      olderThan: true,
      maxSize: true,
    }),
    rules: keys<NonNullable<WorkspaceConfig['rules']>>({
      exclusiveOutputs: true,
      upfrontKeys: true,
    }),
  },
  project: {
    '': keys<ProjectConfig>({ tags: true, tasks: true }),
    'tasks.*': keys<TaskConfig>({ description: true, exec: true, dependsOn: true, cache: true }),
    'tasks.*.exec': keys<ExecConfig>({
      command: true,
      remote: true,
      env: true,
      timeout: true,
      retries: true,
      persistent: true,
      interactive: true,
      sandbox: true,
    }),
    'tasks.*.exec.env': keys<ExecEnv>({ passThrough: true, define: true, secret: true }),
    'tasks.*.exec.persistent': keys<PersistentConfig>({ readyWhen: true }),
    'tasks.*.exec.sandbox': keys<SandboxConfig>({
      allow: true,
      deny: true,
      ignore: true,
      weakerWhenNested: true,
      weakerNetworkIsolation: true,
    }),
    'tasks.*.exec.sandbox.allow': keys<SandboxGrants>({
      read: true,
      write: true,
      network: true,
      systemInfo: true,
      unixSockets: true,
      localBinding: true,
      machLookup: true,
      pty: true,
      gitConfig: true,
    }),
    'tasks.*.exec.sandbox.ignore': keys<SandboxIgnore>({
      read: true,
      write: true,
      network: true,
      systemInfo: true,
    }),
    'tasks.*.exec.sandbox.deny': keys<SandboxDenials>({ network: true }),
    'tasks.*.cache': keys<CacheConfig>({ inputs: true, outputs: true }),
    'tasks.*.cache.inputs': keys<CacheInputs>({
      files: true,
      workspaceFiles: true,
      env: true,
      tasks: true,
      runtime: true,
      workspaceRuntime: true,
    }),
    'tasks.*.cache.outputs': keys<CacheOutputs>({ files: true, workspaceFiles: true }),
  },
}

/** A valid workspace config that sets every field once. */
function workspaceSeed(): Record<string, unknown> {
  return {
    concurrency: 2,
    cacheDir: '.vx/cache',
    timeout: 1000,
    cacheRetention: { olderThan: '30d', maxSize: '10G' },
    affectedBase: 'origin/main',
    cacheScope: 'pr-1',
    rules: { exclusiveOutputs: true, upfrontKeys: true },
    plugins: [],
  }
}

/**
 * A valid project config that sets every field at least once. Field
 * probes run against a field's FIRST occurrence, so each task carries only
 * what its fields need: `remote: 'only'` requires `cache` and sits on `r`,
 * so probing `cache` away on `c` reads the field's own rule.
 */
function projectSeed(): Record<string, unknown> {
  const grants = {
    read: ['.'],
    write: ['dist'],
    network: ['example.com'],
    systemInfo: ['vfs.disk-space'],
    unixSockets: ['/run/x.sock'],
    localBinding: [3000],
    machLookup: ['com.apple.x'],
    pty: true,
    gitConfig: false,
  }
  const ignore = {
    read: grants.read,
    write: grants.write,
    network: grants.network,
    systemInfo: grants.systemInfo,
  }
  return {
    tags: ['scope:web'],
    tasks: {
      t: {
        description: 'd',
        dependsOn: ['^t'],
        exec: {
          command: 'true',
          remote: false,
          timeout: 1000,
          env: { passThrough: ['CI'], define: { A: 'b' }, secret: ['CI'] },
          persistent: { readyWhen: 'ready' },
          sandbox: {
            allow: grants,
            deny: { network: ['example.org'] },
            ignore,
            weakerWhenNested: true,
            weakerNetworkIsolation: false,
          },
        },
      },
      i: { exec: { command: 'true', interactive: true } },
      c: {
        exec: { command: 'true', retries: 1 },
        cache: {
          inputs: {
            files: ['src/**'],
            workspaceFiles: ['tsconfig.json'],
            env: ['A'],
            tasks: [],
            runtime: ['node -v'],
            workspaceRuntime: ['bun -v'],
          },
          outputs: { files: ['dist/**'], workspaceFiles: ['out/**'] },
        },
      },
      g: { dependsOn: ['t'] },
      r: {
        exec: { command: 'true', remote: 'only' },
        cache: { inputs: { files: [] }, outputs: { files: [] } },
      },
    },
  }
}

const ABSENT = Symbol('absent')

/**
 * The values every field is probed with: each JSON type, the numeric edges
 * the schema draws (fraction, sign, port range, the timer ceiling), and the
 * string and glob shapes a refusal names. A probe with nothing to say about
 * a field lands in that field's `ok` or in its type refusal.
 */
const PROBES: readonly unknown[] = [
  ABSENT,
  null,
  true,
  false,
  0,
  1,
  1.5,
  -1,
  65536,
  2 ** 31,
  '',
  'x',
  '(',
  '30d',
  '10G',
  '10',
  [],
  ['x'],
  [''],
  [1],
  [3000],
  ['/x'],
  ['!/x'],
  ['../x'],
  ['!x'],
  ['!!x', 'y'],
  ['.'],
  ['**'],
  ['A=B'],
  ['A*'],
  {},
  { x: 'y' },
]

/** Keys a record's entry is probed under, with the seed entry's value. */
const KEY_PROBES = ['', ' x', 'x#y', 'x*', '^x', '!x', 'A=B']

const label = (v: unknown): string => (v === ABSENT ? '<absent>' : JSON.stringify(v))

type Validate = (config: unknown) => string
type Outcomes = Record<string, string[]>

interface SurfaceRecord {
  /** Object level → the fields it accepts. */
  levels: Record<string, string[]>
  /** Levels keyed by a name the author picks (a task, an env var). */
  records: string[]
  /** Field → outcome (`ok` or the refusal) → the probes that produce it. */
  fields: Record<string, Outcomes>
  /** Record → outcome → the entry names that produce it. */
  keys: Record<string, Outcomes>
}

function validator(
  fn: (config: never, where: string) => void,
  where: string,
): (config: unknown) => string {
  return (config) => {
    try {
      fn(config as never, where)
      return 'ok'
    } catch (err) {
      expect((err as Error).name).toBe('UserError')
      return (err as Error).message.replaceAll(where, '$CONFIG')
    }
  }
}

function at(root: unknown, segs: readonly string[]): Record<string, unknown> {
  let node = root as Record<string, unknown>
  for (const s of segs) node = node[s] as Record<string, unknown>
  return node
}

function add(out: Outcomes, outcome: string, probe: string): void {
  ;(out[outcome] ??= []).push(probe)
}

/** Walk the seed, discovering each level's fields and probing each field. */
function surface(seed: () => Record<string, unknown>, validate: Validate): SurfaceRecord {
  expect(validate(seed())).toBe('ok')
  const rec: SurfaceRecord = { levels: {}, records: [], fields: {}, keys: {} }
  const probed = new Set<string>()
  const seeded: Record<string, Set<string>> = {}
  const firstAt: Record<string, string[]> = {}
  const probe = (segs: readonly string[], k: string, values: readonly unknown[]): Outcomes => {
    const out: Outcomes = {}
    for (const p of values) {
      // The seed itself is the last value; an object seed is spelled out
      // above it already.
      const l =
        p === values.at(-1) && typeof p === 'object' && p !== null && !Array.isArray(p)
          ? '<seed>'
          : label(p)
      if (Object.values(out).some((ps) => ps.includes(l))) continue
      const config = seed()
      const parent = at(config, segs)
      if (p === ABSENT) delete parent[k]
      else parent[k] = structuredClone(p)
      add(out, validate(config), l)
    }
    return out
  }
  const walk = (segs: string[], generic: string[]): void => {
    const node = at(seed(), segs)
    const config = seed()
    at(config, segs)['__probe__'] = 1
    const m = /has unknown field "__probe__" \(allowed: ([^)]*)\)/.exec(validate(config))
    const isLevel = m !== null
    const where = generic.join('.')
    if (isLevel) {
      rec.levels[where] = m[1]!.split(', ').sort()
      firstAt[where] ??= segs
      for (const k of Object.keys(node)) (seeded[where] ??= new Set()).add(k)
    } else if (!rec.records.includes(where)) {
      rec.records.push(where)
      const [first, value] = Object.entries(node)[0]!
      const out: Outcomes = {}
      for (const key of KEY_PROBES) {
        const config = seed()
        const parent = at(config, segs)
        delete parent[first]
        parent[key] = value
        add(out, validate(config), JSON.stringify(key))
      }
      rec.keys[where] = out
    }
    for (const [k, v] of Object.entries(node)) {
      const childGeneric = [...generic, isLevel ? k : '*']
      const field = childGeneric.join('.')
      if (!probed.has(field)) {
        probed.add(field)
        rec.fields[field] = probe(segs, k, [...PROBES, v])
      }
      if (typeof v === 'object' && v !== null && !Array.isArray(v)) {
        walk([...segs, k], childGeneric)
      }
    }
  }
  walk([], [])
  // A field a level names but no value of passes (`sandbox.ignore.pty`: a
  // flag, not something to ignore) cannot be seeded; it is probed on the
  // level's first occurrence instead. One that accepts a probe must be
  // seeded, so its own rules are read in a valid context.
  for (const [where, fields] of Object.entries(rec.levels)) {
    for (const f of fields.filter((f) => !seeded[where]!.has(f))) {
      const out = probe(firstAt[where]!, f, PROBES)
      rec.fields[where === '' ? f : `${where}.${f}`] = out
      expect({
        field: `${where}.${f}`,
        accepts: Object.keys(out).includes('ok') ? out['ok'] : [],
      }).toEqual({ field: `${where}.${f}`, accepts: ['<absent>'] })
    }
  }
  return rec
}

function current(): Record<'workspace' | 'project', SurfaceRecord> {
  return {
    workspace: surface(workspaceSeed, validator(validateWorkspace, WORKSPACE_PATH)),
    project: surface(projectSeed, validator(validateProjectConfig, PROJECT_PATH)),
  }
}

const RULES_RECORD = path.join(import.meta.dir, 'contract', 'config-schema-rules.json')

/** A field of a task set to one of its seed values, or `exec` taken away. */
interface Unit {
  path: string[]
  value: unknown
}

const unitName = (u: Unit): string =>
  `${u.path.join('.')}=${u.value === ABSENT ? '<absent>' : JSON.stringify(u.value)}`

/**
 * The fields of a task and of its `exec`, each with every distinct value
 * the seed tasks give it, plus `exec` taken away. Whole blocks, not their
 * leaves: a cross-field rule is between blocks (`persistent` and `cache`),
 * and a leaf alone (`cache.inputs.env`) is refused by its own block.
 */
function taskUnits(): Unit[] {
  const out = new Map<string, Unit>([['exec=<absent>', { path: ['exec'], value: ABSENT }]])
  for (const task of Object.values(projectSeed()['tasks'] as Record<string, object>)) {
    for (const [k, v] of Object.entries(task)) {
      if (k !== 'exec') out.set(unitName({ path: [k], value: v }), { path: [k], value: v })
    }
    const exec = (task as { exec?: Record<string, unknown> }).exec ?? {}
    for (const [k, v] of Object.entries(exec)) {
      if (k !== 'command')
        out.set(unitName({ path: ['exec', k], value: v }), { path: ['exec', k], value: v })
    }
  }
  return [...out.values()].sort((a, b) => unitName(a).localeCompare(unitName(b)))
}

function applyUnit(task: Record<string, unknown>, u: Unit): void {
  let node = task
  for (const seg of u.path.slice(0, -1)) {
    node[seg] ??= {}
    node = node[seg] as Record<string, unknown>
  }
  const last = u.path.at(-1)!
  if (u.value === ABSENT) delete node[last]
  else node[last] = structuredClone(u.value)
}

/** Two units on one path, or one inside the other, are one edit, not a pair. */
const overlaps = (a: Unit, b: Unit): boolean =>
  a.path.slice(0, b.path.length).join('.') === b.path.join('.') ||
  b.path.slice(0, a.path.length).join('.') === a.path.join('.')

/**
 * The rules between fields, found by trying every seed value alone and
 * every pair together on a plain task (`exec.command` only) and, for the
 * task's own fields, on a group task (`dependsOn` only). A unit refused alone is listed; a pair is
 * listed when it disagrees with its halves: both pass alone and together
 * are refused (a conflict: `persistent` with `cache`), or one is refused
 * alone and the pair passes (a requirement: `remote: 'only'` needs
 * `cache`). A rule that needs three fields to show is outside this table;
 * schema.md's error table holds those (schema-doc-drift.test.ts).
 */
function taskRules(): Record<
  string,
  { alone: Record<string, string>; pairs: Record<string, string> }
> {
  const validate = validator(validateProjectConfig, PROJECT_PATH)
  const bases: Record<string, () => Record<string, unknown>> = {
    'exec task': () => ({ exec: { command: 'true' } }),
    'group task': () => ({ dependsOn: ['^t'] }),
  }
  const out: ReturnType<typeof taskRules> = {}
  for (const [name, base] of Object.entries(bases)) {
    // A group task has no `exec` to put a field in.
    const units = taskUnits().filter((u) => name === 'exec task' || u.path.length === 1)
    const outcome = (...us: Unit[]): string => {
      const task = base()
      for (const u of us) applyUnit(task, u)
      return validate({ tasks: { t: task } })
    }
    const alone = new Map(units.map((u) => [unitName(u), outcome(u)]))
    const pairs: Record<string, string> = {}
    for (const [i, a] of units.entries()) {
      for (const b of units.slice(i + 1)) {
        if (overlaps(a, b)) continue
        const [oa, ob, both] = [alone.get(unitName(a))!, alone.get(unitName(b))!, outcome(a, b)]
        const conflict = oa === 'ok' && ob === 'ok' && both !== 'ok'
        const requirement = both === 'ok' && (oa !== 'ok' || ob !== 'ok')
        if (conflict || requirement) pairs[`${unitName(a)} + ${unitName(b)}`] = both
      }
    }
    out[name] = {
      alone: Object.fromEntries([...alone].filter(([, o]) => o !== 'ok')),
      pairs,
    }
  }
  return out
}

describe('the config schema contract (versioning-1.0.md)', () => {
  // Built inside the rows, so a seed that misses a new field fails a named
  // row rather than the file.
  let memo: ReturnType<typeof current> | undefined
  const live = (): ReturnType<typeof current> => (memo ??= current())

  it('every level the validator checks is an exported interface, field for field', () => {
    for (const file of ['workspace', 'project'] as const) {
      expect({ file, levels: live()[file].levels }).toEqual({ file, levels: LEVEL_TYPES[file] })
    }
  })

  it('the validator agrees with tests/contract/config-schema.json', () => {
    if (process.env['VX_UPDATE_CONTRACT'] === '1' && process.env['CI'] !== 'true') {
      writeFileSync(RECORD, JSON.stringify(live(), null, 2) + '\n')
    }
    const recorded = JSON.parse(readFileSync(RECORD, 'utf8')) as unknown
    // On a failure, the diff below IS the schema change: regenerate the
    // record (header) only if the change is meant to ship, and say so in
    // the release notes.
    expect(live()).toEqual(recorded as ReturnType<typeof current>)
  })

  it('the rules between fields agree with tests/contract/config-schema-rules.json', () => {
    const rules = taskRules()
    if (process.env['VX_UPDATE_CONTRACT'] === '1' && process.env['CI'] !== 'true') {
      writeFileSync(RULES_RECORD, JSON.stringify(rules, null, 2) + '\n')
    }
    expect(rules).toEqual(JSON.parse(readFileSync(RULES_RECORD, 'utf8')) as typeof rules)
  })
})
