// CLASS pins: the greps that hold a claim across EVERY hand-authored page,
// rather than one page against its source. They grew up inside
// site-samples.unsafe.test.ts because that file already read both doc trees,
// and by item 361 it carried 226 of the suite's 411 assertions and every one
// of these. That is why item 358's pin landed in the wrong suite and why the
// shared helper had to be added to a file named for renderer samples.
//
// They live here now, over one contract: `handAuthoredDocs()` is the page
// list, `CLASS_PAGES` names what each narrowing filter actually reaches. A
// move, not a rewrite — item 365 (2026-09-19) held the assertion count across
// it, so nothing was dropped in the carry.
//
// The site lives outside packages/vx, which a sandboxed shard cannot read;
// hence the unsafe suite.
import { existsSync, readFileSync, readdirSync } from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'bun:test'
import { ESSENTIAL_ENV } from '../src/exec/env.js'

const DOCS = path.resolve(import.meta.dir, '..', '..', 'vx-docs', 'src', 'content', 'docs')

/**
 * Which hand-authored pages each class grep actually reaches. A class pin
 * narrows the page list to "the pages that mention X" and then asserts
 * something about them — so the day X is reworded the filter empties and the
 * pin passes having checked nothing, which is the drift it exists to catch.
 * Naming the members makes that a failure (item 361, 2026-09-19); a page
 * joining or leaving a class is a deliberate edit here.
 */
const CLASS_PAGES = {
  remoteCacheLayer: [
    'README.md',
    'architecture.md',
    'cli.md',
    'comparison.md',
    'extensibility.md',
    'flows.md',
    'index.md',
    'layered-cache.md',
    'options.md',
    'patterns.md',
    'plugins.md',
    'remote-caching.md',
  ],
  retryLine: ['execute-task.md', 'schema.md'],
  outputFingerprint: [
    'caching.md',
    'flows.md',
    'optimizations.md',
    'strict-output-ownership.md',
    'why-vx-is-fast.md',
  ],
}

/**
 * Every Markdown or MDX page a person wrote, in both doc trees. `history/` and
 * `design/` are records of what was true then, STATUS.md quotes old wording
 * on purpose, and the site's copies of `packages/vx/docs` are rewritten by
 * the docs build — a class grep that reads them finds its own fix twice.
 */
function handAuthoredDocs(): string[] {
  const pages: string[] = []
  const walk = (dir: string): void => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const p = path.join(dir, entry.name)
      if (entry.isDirectory()) {
        if (entry.name !== 'history' && entry.name !== 'design') walk(p)
      } else if (/\.mdx?$/.test(entry.name) && entry.name !== 'STATUS.md') {
        const text = readFileSync(p, 'utf8')
        if (!text.includes('# generated by packages/vx-docs/scripts/import-docs.ts')) pages.push(p)
      }
    }
  }
  for (const root of [DOCS, path.resolve(import.meta.dir, '..', 'docs')]) walk(root)
  return pages
}

describe('no page still calls the remote seam a three-call one', () => {
  it('every hand-authored page that names the seam names its four methods', () => {
    // Item 346 fixed remote-caching.md and never grepped the class: the same
    // sentence sat on extensibility.md, plugins.md and architecture.md
    // (item 349, 2026-09-19). This pin is the grep.
    const src = readFileSync(
      path.resolve(import.meta.dir, '..', 'src', 'cache', 'layered-cache.ts'),
      'utf8',
    )
    const decl = /export interface RemoteCacheLayer \{([\s\S]*?)\n\}/.exec(src)
    const methods = [...decl![1]!.matchAll(/^  (\w+)\??\(/gm)].map((m) => m[1]!)
    expect(methods.length).toBe(4)
    const roots = [DOCS, path.resolve(import.meta.dir, '..', 'docs')]
    const pages: string[] = []
    const walk = (dir: string): void => {
      for (const entry of readdirSync(dir, { withFileTypes: true })) {
        const p = path.join(dir, entry.name)
        if (entry.isDirectory()) {
          if (entry.name !== 'history' && entry.name !== 'design') walk(p)
        } else if (/\.mdx?$/.test(entry.name)) pages.push(p)
      }
    }
    for (const root of roots) walk(root)
    expect(pages.length).toBeGreaterThan(20)
    const checked: string[] = []
    for (const page of pages) {
      const text = readFileSync(page, 'utf8')
      if (!text.includes('RemoteCacheLayer')) continue
      // STATUS logs the old wording as a quote, and the site's generated
      // copies are rewritten from `packages/vx/docs` by the docs build.
      if (path.basename(page) === 'STATUS.md') continue
      if (text.includes('# generated by packages/vx-docs/scripts/import-docs.ts')) continue
      checked.push(path.basename(page))
      expect({ page: path.basename(page), says: /three-call/.test(text) }).toEqual({
        page: path.basename(page),
        says: false,
      })
    }
    // The pages in the class, named: a rename of the seam would otherwise
    // empty the filter and pass this checking nothing (item 361).
    expect([...new Set(checked)].sort()).toEqual(CLASS_PAGES.remoteCacheLayer)
  })
})

describe('no page says a failed task aborts its dependents', () => {
  it('every hand-authored page uses the status the scheduler sets', () => {
    // Item 348 fixed task-dependencies.md and did not grep the class; the
    // same sentence sat on the how-vx-works concept (item 350, 2026-09-19).
    // `aborted` is what teardown sets, `skipped` is what a failed upstream
    // leaves behind, and the pages must not swap them.
    const src = readFileSync(
      path.resolve(import.meta.dir, '..', 'src', 'graph', 'scheduler.ts'),
      'utf8',
    )
    expect(src).toContain("| 'skipped'")
    expect(src).toContain("| 'aborted'")
    const roots = [DOCS, path.resolve(import.meta.dir, '..', 'docs')]
    const pages: string[] = []
    const walk = (dir: string): void => {
      for (const entry of readdirSync(dir, { withFileTypes: true })) {
        const p = path.join(dir, entry.name)
        if (entry.isDirectory()) {
          if (entry.name !== 'history' && entry.name !== 'design') walk(p)
        } else if (/\.mdx?$/.test(entry.name) && entry.name !== 'STATUS.md') pages.push(p)
      }
    }
    for (const root of roots) walk(root)
    for (const page of pages) {
      const text = readFileSync(page, 'utf8')
      expect({
        page: path.basename(page),
        aborts: /aborts? (its|the) (transitive )?dependents/.test(text),
      }).toEqual({
        page: path.basename(page),
        aborts: false,
      })
    }
  })
})

describe('every --frozen figure on a page is one benchmarks.md measured', () => {
  it('no page quotes a frozen speed number the benchmarks page does not have', () => {
    // Item 346 struck the CI guide's "roughly 10–21%" and did not grep the
    // class: the root README still sold "~120 ms back per 1,000 packages"
    // (item 351, 2026-09-19). The 2026-09-12 head-to-head reads as a tie.
    const bench = readFileSync(path.resolve(import.meta.dir, '..', 'docs', 'benchmarks.md'), 'utf8')
    const roots = [
      DOCS,
      path.resolve(import.meta.dir, '..', 'docs'),
      path.resolve(import.meta.dir, '..', '..', '..'),
    ]
    const pages = new Set<string>()
    const walk = (dir: string, depth: number): void => {
      for (const entry of readdirSync(dir, { withFileTypes: true })) {
        if (entry.name.startsWith('.') || entry.name === 'node_modules') continue
        const p = path.join(dir, entry.name)
        if (entry.isDirectory()) {
          if (depth > 0 && entry.name !== 'history' && entry.name !== 'design') walk(p, depth - 1)
        } else if (/\.mdx?$/.test(entry.name) && entry.name !== 'STATUS.md') pages.add(p)
      }
    }
    walk(roots[0]!, 3)
    walk(roots[1]!, 1)
    walk(roots[2]!, 0)
    expect(pages.size).toBeGreaterThan(20)
    let paragraphs = 0
    for (const page of pages) {
      const text = readFileSync(page, 'utf8')
      for (const para of text.split(/\n\s*\n/)) {
        if (!para.includes('--frozen') && !para.includes('`vx lock`')) continue
        paragraphs += 1
        // A figure attached to a frozen claim must be the benchmarks page's.
        for (const m of para.matchAll(/(\d+(?:[–-]\d+)?)\s?(%|ms)\b/g)) {
          expect({ page: path.basename(page), figure: m[0] }).toEqual({
            page: path.basename(page),
            figure: bench.includes(m[1]!) ? m[0] : `${m[0]} — not on benchmarks.md`,
          })
        }
      }
    }
    // Without this the pin passes on nothing the day `--frozen` is reworded
    // — the drift it exists to catch (item 361).
    expect(paragraphs).toBeGreaterThan(20)
  })
})

describe('no doc describes exec.resources as a field a config can declare', () => {
  it('the field is gone from the schema, and no page says otherwise', () => {
    // It left the config on 2026-09-12 with the reservations. Item 347 fixed
    // four pages and did not grep the module docs, where config-schema.md
    // still had the validator checking it (item 352, 2026-09-19).
    const config = readFileSync(path.resolve(import.meta.dir, '..', 'src', 'config.ts'), 'utf8')
    const schema = readFileSync(
      path.resolve(import.meta.dir, '..', 'src', 'workspace', 'config-schema.ts'),
      'utf8',
    )
    expect(/^\s+resources\??:/m.test(config)).toBe(false)
    expect(schema.includes('resources')).toBe(false)
    const roots = [DOCS, path.resolve(import.meta.dir, '..', 'docs')]
    const pages: string[] = []
    const walk = (dir: string): void => {
      for (const entry of readdirSync(dir, { withFileTypes: true })) {
        const p = path.join(dir, entry.name)
        if (entry.isDirectory()) {
          // `design/` records the decision that removed it; `history/` logs it.
          if (entry.name !== 'history' && entry.name !== 'design') walk(p)
        } else if (/\.mdx?$/.test(entry.name) && entry.name !== 'STATUS.md') pages.push(p)
      }
    }
    for (const root of roots) walk(root)
    expect(pages.length).toBeGreaterThan(40)
    for (const page of pages) {
      const text = readFileSync(page, 'utf8')
      // The site's generated copies are rewritten from `packages/vx/docs`
      // by the docs build; the source above is the one to hold.
      if (text.includes('# generated by packages/vx-docs/scripts/import-docs.ts')) continue
      expect({
        page: path.basename(page),
        claims: /`exec\.resources`|`resources` are |, `resources`,/.test(text),
      }).toEqual({ page: path.basename(page), claims: false })
    }
  })
})

// Two claims about one stderr line: `execute-task.ts` ends the retry notice
// `after a timeout` when the kill was the timeout's and `after exit <code>`
// otherwise, and both pages that quote the line quoted only the second —
// modules/execute-task.md in the same bullet that says "timeouts included"
// (item 357, 2026-09-19). A user greps the message they got; half a message
// finds nothing.
describe('every page quoting the retry line quotes both its endings', () => {
  it('the two spellings are the ones execute-task.ts emits', () => {
    const src = readFileSync(
      path.resolve(import.meta.dir, '..', 'src', 'orchestrator', 'execute-task.ts'),
      'utf8',
    )
    expect(src).toContain("'a timeout'")
    expect(src).toContain('after ${')
    const pages = handAuthoredDocs()
    expect(pages.length).toBeGreaterThan(40)
    const checked: string[] = []
    for (const page of pages) {
      const text = readFileSync(page, 'utf8')
      if (!text.includes('vx: retrying <id>')) continue
      checked.push(path.basename(page))
      expect({ page: path.basename(page), both: text.includes('after a timeout') }).toEqual({
        page: path.basename(page),
        both: true,
      })
    }
    expect(checked.sort()).toEqual(CLASS_PAGES.retryLine)
  })
})

// The formatter reflows prose, and a reflow can break the markdown under it:
// schema.md's "(the count of names + the names themselves …)" wrapped so the
// `+` landed at the start of a line, and oxfmt turned it into a BULLET in the
// middle of a sentence — which is how it shipped to the site (item 357,
// 2026-09-19). A paragraph whose parentheses do not balance is the signature
// of that class, and cheap to check on every page at once.

// The formatter reflows prose, and a reflow can break the markdown under it:
// schema.md's "(the count of names + the names themselves …)" wrapped so the
// `+` landed at the start of a line, and oxfmt turned it into a BULLET in the
// middle of a sentence — which is how it shipped to the site (item 357,
// 2026-09-19). A paragraph whose parentheses do not balance is the signature
// of that class, and cheap to check on every page at once.
describe('no prose block was broken open by a reflow', () => {
  it('every paragraph and list item closes the parentheses it opens', () => {
    const broken: string[] = []
    const pages = handAuthoredDocs()
    expect(pages.length).toBeGreaterThan(40)
    for (const page of pages) {
      const text = readFileSync(page, 'utf8')
      let fenced = false
      let block: string[] = []
      let start = 0
      const flush = (): void => {
        if (block.length === 0) return
        // Code spans hold shell and glob punctuation that is not prose.
        const prose = block
          .join('\n')
          .replace(/`[^`]*`/g, '')
          .replace(/`[^`]*$/, '')
        if (prose.split('(').length !== prose.split(')').length) {
          broken.push(`${path.basename(page)}:${start}`)
        }
        block = []
      }
      text.split('\n').forEach((line, i) => {
        if (line.trim().startsWith('```')) {
          fenced = !fenced
          flush()
          return
        }
        if (fenced) return
        if (line.trim() === '') {
          flush()
          return
        }
        if (block.length === 0) start = i + 1
        block.push(line)
      })
      flush()
    }
    expect(broken).toEqual([])
  })
})

// The same reflow damage in its other shape: a paragraph written into the
// blank line after item N leaves item N+1 with nowhere to start, and the
// formatter joins it onto the paragraph's last line. The four-step cache
// precedence in cli.md rendered as three steps plus a run-on sentence that
// read `--force` as part of a remark about remote layers (item 387,
// 2026-09-19); two design docs carried the same break. A swallowed item is
// invisible in the source line and unreadable on the page, so grep the
// class rather than the one page.
describe('no numbered list item was swallowed by a paragraph', () => {
  it('every step of an ordered list starts its own line', () => {
    const swallowed: string[] = []
    const pages = handAuthoredDocs()
    expect(pages.length).toBeGreaterThan(40)
    for (const page of pages) {
      let fenced = false
      let last: number | undefined
      readFileSync(page, 'utf8')
        .split('\n')
        .forEach((line, i) => {
          const trimmed = line.trim()
          if (trimmed.startsWith('```')) {
            fenced = !fenced
            return
          }
          if (fenced) return
          // A heading ends the list it followed; `### 4. …` is an outline's
          // own numbering, not a continuation of the prose list above it.
          if (trimmed.startsWith('#')) {
            last = undefined
            return
          }
          const item = /^(\d+)\. /.exec(trimmed)
          if (item !== null) {
            last = Number(item[1])
            return
          }
          if (last === undefined) return
          // Only a number that FOLLOWS sentence punctuation is a marker the
          // formatter pulled up; `— item 206. The session` is a citation.
          for (const m of line.matchAll(/[.:)]\*{0,2} (\d+)\. /g)) {
            if (Number(m[1]) === last + 1) {
              swallowed.push(`${path.basename(page)}:${i + 1}`)
              last = Number(m[1])
            }
          }
        })
    }
    expect(swallowed).toEqual([])
  })
})

// The glyph set is `glyphShape` in framed-output.ts plus the `▸` a pinned
// persistent row carries. Two pages and the module's own docblock listed a
// seventh, `⦿ running`, which the renderer has never printed: a live worker
// row leads with its ticking elapsed time and carries NO glyph, as
// status-line.ts says in the same breath (item 359, 2026-09-19). Item 302
// struck one glyph a docblock invented and never grepped the class; this is
// the grep, over the three places that enumerate the set.

// "What does my build script actually see?" is answered by four pages, and
// only schema.md's copy was pinned — the copy that had already drifted once
// (USER, LOGNAME, TEMP and TMP were passed to every task and named nowhere,
// the note on that pin). The other three name every POSIX essential today
// and each defers the Windows set in words; hold them there (item 359,
// 2026-09-19).
describe('every page listing the env allowlist lists all of it', () => {
  it('each names every POSIX essential, and the contract page all 25', () => {
    const posix = ESSENTIAL_ENV.slice(0, ESSENTIAL_ENV.indexOf('SYSTEMROOT'))
    expect(posix.length).toBe(17)
    const pages = handAuthoredDocs().filter((p) => readFileSync(p, 'utf8').includes('`LOGNAME`'))
    // schema.md (pinned separately), execution.md, modules/env.md, and the
    // environment-variables guide. A fifth copy lands here unpinned no more.
    expect(pages.map((p) => path.basename(p)).sort()).toEqual([
      'env.md',
      'environment-variables.md',
      'execution.md',
      'schema.md',
    ])
    for (const page of pages) {
      const text = readFileSync(page, 'utf8')
      const names = page.endsWith('modules/env.md') ? ESSENTIAL_ENV : posix
      expect({
        page: path.basename(page),
        missing: names.filter((n) => !text.includes(`\`${n}\``)),
      }).toEqual({ page: path.basename(page), missing: [] })
    }
  })
})

// The task-timeout ladder has FOUR rungs and a page that drops one inverts
// nothing — it just hides the rung a user actually types. The
// workspace-config guide read "a task's own `exec.timeout`, then the
// `VX_TASK_TIMEOUT` env var, then this", leaving `--timeout` out entirely,
// while schema.md, cli.md, `options.ts`, `run.ts` and
// `options-resolve.test.ts`'s header all name all four (item 378,
// 2026-09-19). The behaviour is pinned; the pages were not.
describe('every page stating the timeout ladder states all four rungs', () => {
  it('names exec.timeout, --timeout, VX_TASK_TIMEOUT and the workspace default', () => {
    // The ladder itself, from the one expression that resolves it. If this
    // line moves, the rung names below are no longer the code's.
    const run = readFileSync(
      path.resolve(import.meta.dir, '..', 'src', 'orchestrator', 'run.ts'),
      'utf8',
    )
    expect(run).toContain(
      'options.timeout ?? readTaskTimeoutEnv() ?? workspaceConfig?.timeout ?? undefined',
    )
    const pages = handAuthoredDocs().filter((p) =>
      readFileSync(p, 'utf8').includes('VX_TASK_TIMEOUT'),
    )
    // cli.md, schema.md and the workspace-config guide. A fourth copy lands
    // here unpinned no more.
    expect(pages.map((p) => path.basename(p)).sort()).toEqual([
      'cli.md',
      'schema.md',
      'workspace-config.md',
    ])
    for (const page of pages) {
      const text = readFileSync(page, 'utf8')
      expect({
        page: path.basename(page),
        missing: ['exec.timeout', '--timeout', 'VX_TASK_TIMEOUT'].filter(
          (rung) => !text.includes(rung),
        ),
      }).toEqual({ page: path.basename(page), missing: [] })
    }
  })
})

// The safe half of this check (`doc-references.test.ts`) walks
// `packages/vx/docs` only, so a `src/…` or `tests/…` path named on a SITE
// page — the guides, the concepts, the blog — was checked by nothing. The
// site is exactly where such a path goes stale: item 377 found a test header
// still citing `src/cli/mcp.ts` a release after the verb left core. Nothing
// is stale today; this is the tripwire (item 380, 2026-09-19).
describe('every source path a site page names exists', () => {
  it('`src/…`, `tests/…` and `docs/…` in site prose resolve under packages/vx', () => {
    const pkg = path.resolve(import.meta.dir, '..')
    const pages = handAuthoredDocs().filter((p) => p.startsWith(DOCS))
    expect(pages.length).toBeGreaterThan(30)
    const missing: string[] = []
    for (const page of pages) {
      for (const m of readFileSync(page, 'utf8').matchAll(
        /`((?:src|tests|docs)\/[A-Za-z0-9_./-]+\.(?:ts|md|mjs))`/g,
      )) {
        if (!existsSync(path.join(pkg, m[1]!))) missing.push(`${path.basename(page)}: ${m[1]!}`)
      }
    }
    expect(missing).toEqual([])
  })
})

// The path checks resolve `src/…`, `tests/…` and `docs/…` against
// packages/vx, so a citation written with a `packages/…` prefix is seen by
// neither — and the contract docs carry seven of them (the bench scripts and
// their RESULTS.md, a vx-migrate test). Nothing is stale today; this is the
// tripwire, one directory up from item 380's (item 384, 2026-09-19).
// `output-index.ts` compares `Math.abs(s.mtimeMs - e.mtimeMs) < 1` and its
// own comment says legacy SECOND-precision rows converge on their first
// restore — so a page describing the skip check as second-precision
// describes what it stopped doing, and overstates the tolerance a
// thousandfold. caching.md said **millisecond** twice; flows.md said
// "floor-to-second mtime" (item 388, 2026-09-19): one copy pinned, the
// other drifted, the shape every finding in this arc has had. Unqualified
// prose (`(size, mode, mtime)`) is left alone — only a stated precision is
// held, and only SECOND is wrong.
describe('no page dates the output fingerprint to the second', () => {
  it('every page stating the (size, mode, mtime) triple states ms or no unit', () => {
    const wrong: string[] = []
    const seen = new Set<string>()
    for (const page of handAuthoredDocs()) {
      const flat = readFileSync(page, 'utf8').split(/\s+/).join(' ')
      for (const m of flat.matchAll(/size[^.]{0,80}?mode[^.]{0,80}?mtime/gi)) {
        seen.add(path.basename(page))
        const window = flat.slice(m.index, m.index + 120)
        // `millisecond` CONTAINS `second`: the first draft flagged both
        // correct pages and nothing else — the naive selector, again, caught
        // by running the check rather than reading it.
        if (/(?<!milli)second/i.test(window))
          wrong.push(`${path.basename(page)}: ${window.slice(0, 70)}`)
      }
    }
    expect([...seen].sort()).toEqual([...CLASS_PAGES.outputFingerprint].sort())
    expect(wrong).toEqual([])
    // The contract page is the one that must name the unit outright — by
    // PATH, not basename: the site's hand-authored caching guide carries
    // the same file name and does not state the triple at all.
    const contract = path.join('vx', 'docs', 'caching.md')
    const caching = handAuthoredDocs().find((p) => p.endsWith(contract)) as string
    expect(caching).toBeString()
    expect(readFileSync(caching, 'utf8')).toContain('**millisecond**-mtime check')
  })
})

describe('every packages/ path the docs cite exists', () => {
  it('`packages/x/y.ts` in prose resolves from the repo root', () => {
    const root = path.resolve(import.meta.dir, '..', '..', '..')
    // A path under a package that does not exist is an ILLUSTRATION, not a
    // citation — `config-imports.md` walks a reader through
    // `packages/lib/preset.mjs`. The first draft of this pin flagged both,
    // which is the contrived-selector failure of items 377 and 380 a third
    // time; the package directory is what tells the two apart.
    const missing: string[] = []
    for (const page of handAuthoredDocs()) {
      for (const m of readFileSync(page, 'utf8').matchAll(
        /`(packages\/([A-Za-z0-9_.-]+)\/[A-Za-z0-9_./-]+\.(?:ts|md|mjs|json))`/g,
      )) {
        if (!existsSync(path.join(root, 'packages', m[2]!))) continue
        if (!existsSync(path.join(root, m[1]!))) missing.push(`${path.basename(page)}: ${m[1]!}`)
      }
    }
    expect(missing).toEqual([])
  })
})

// A blog post's benchmark TABLE is a quotation, and item 391 pinned
// benchmarks.md to `packages/vx-bench/results.json` — which left a second
// full copy of those rows sitting unanchored in `honest-benchmarks.md`,
// the exact configuration every finding in this arc came from. Read
// 2026-09-19 (item 395): all seventeen cells and all three derived
// overheads already agreed.
//
// TABLES only. Blog PROSE rounds and converts on purpose — `0.76 s` for
// 760ms, `73 s` for 1m 13s, `35 s` for 34.61s — so an exact pin there
// would fail on correct text. A cell is a quotation; a sentence is a
// paraphrase.
describe('every benchmark figure a blog table quotes is a measured one', () => {
  const BLOG = path.join(DOCS, 'blog')
  const bench = (): string =>
    readFileSync(path.resolve(import.meta.dir, '..', 'docs', 'benchmarks.md'), 'utf8')
  // The space before the unit is optional on BOTH: the solid tables write
  // `40.6 s` while the head-to-head writes `3.59s`, and a pattern allowing
  // it only on `ms` silently skipped every solid row — the floor below is
  // what surfaced that (four rows checked where twelve were expected).
  const FIGURE = /^\d+m \d+s$|^\d+(?:\.\d+)? ?s$|^\d+ ?ms$/

  // ROW-wise, not figure-wise, which item 383 had to learn once already:
  // a row's figures must appear TOGETHER on one benchmarks.md row, or a
  // number can drift onto the wrong runner and still be "on the page".
  // Proven: mutating solid's restore row from 66 ms to 67 ms passed a
  // figure-wise draft of this pin, because 67ms is the git-walk floor
  // elsewhere on the page.
  it("each table row's figures sit together on a benchmarks.md row", () => {
    const rows = bench()
      .split('\n')
      .filter((l) => l.startsWith('|') && !/^\|\s*-/.test(l))
      .map((l) =>
        l
          .trim()
          .replace(/^\||\|$/g, '')
          .split('|')
          .map((c) => c.trim()),
      )
    const wrong: string[] = []
    let checked = 0
    for (const file of readdirSync(BLOG).filter((f) => /\.mdx?$/.test(f))) {
      for (const line of readFileSync(path.join(BLOG, file), 'utf8').split('\n')) {
        if (!line.startsWith('|') || /^\|\s*-/.test(line)) continue
        // Strip the emphasis and a trailing `(+0:08)` / `(1.9×)` aside;
        // what is left is the figure the cell claims.
        const figures = line
          .trim()
          .replace(/^\||\|$/g, '')
          .split('|')
          .map((c) =>
            c
              .trim()
              .replace(/\*\*/g, '')
              .replace(/\s*\((?:\+[\d:]+|[\d.]+×)\)\s*$/, '')
              .trim(),
          )
          .filter((c) => FIGURE.test(c))
        if (figures.length === 0) continue
        // The 3,270-task table is TRANSPOSED in the post — runner rows where
        // benchmarks.md has runner columns — so its figures cannot sit on one
        // row there by construction. The arm below pins those to results.json
        // instead, which is where they come from.
        if (/^\| (vx|Turborepo|Nx) /.test(line)) continue
        checked += 1
        const together = rows.some((r) => {
          const cells = r.map((c) =>
            c
              .replace(/\*\*/g, '')
              .replace(/\s*\(.*$/, '')
              .trim(),
          )
          return figures.every((f) => cells.includes(f))
        })
        if (!together) wrong.push(`${file}: ${figures.join(' | ')}`)
      }
    }
    expect(checked).toBe(6)
    expect(wrong).toEqual([])
  })

  it('the transposed 3,270-task rows are the recorded run, figure by figure', () => {
    const results = JSON.parse(
      readFileSync(
        path.resolve(import.meta.dir, '..', '..', '..', 'packages', 'vx-bench', 'results.json'),
        'utf8',
      ),
    ) as { rows: Array<Record<string, number | string>> }
    const post = readFileSync(path.join(BLOG, 'honest-benchmarks.md'), 'utf8')
    // Same parse-to-granularity as item 391: hold the CLAIM, not the spelling.
    const parse = (raw: string): { ms: number; step: number } | null => {
      let m = /^(\d+)m (\d+)s$/.exec(raw)
      if (m !== null) return { ms: (Number(m[1]) * 60 + Number(m[2])) * 1000, step: 1000 }
      m = /^(\d+(?:\.\d+)?)s$/.exec(raw)
      if (m !== null) {
        const decimals = (m[1]!.split('.')[1] ?? '').length
        return { ms: Number(m[1]) * 1000, step: 1000 / 10 ** decimals }
      }
      m = /^(\d+) ?ms$/.exec(raw)
      return m === null ? null : { ms: Number(m[1]), step: 1 }
    }
    const FIELDS = ['fresh', 'warmNoRestore', 'freshCpu'] as const
    let checked = 0
    for (const [runner, label] of [
      ['vx', 'vx'],
      ['turbo', 'Turborepo'],
      ['nx', 'Nx'],
    ] as const) {
      const row = new RegExp(`^\\| ${label} +\\|(.*)$`, 'm').exec(post)
      expect(row).not.toBeNull()
      const cells = row![1]!
        .replace(/\|\s*$/, '')
        .split('|')
        .map((c) =>
          c
            .trim()
            .replace(/\*\*/g, '')
            .replace(/\s*\(.*$/, '')
            .trim(),
        )
      expect(cells.length).toBe(3)
      cells.forEach((cell, i) => {
        const shown = parse(cell)
        expect({ runner, cell, readable: shown !== null }).toEqual({ runner, cell, readable: true })
        const actual = results.rows.find((r) => r['runner'] === runner)![FIELDS[i]!] as number
        // The page must show what ROUNDING the measurement to that precision
        // gives — not merely land within one step of it. A tolerance of one
        // step let `510ms` become `511ms` and still pass (510.34 is inside
        // either), which is a figure the page would be getting wrong.
        const rounded = Math.round(actual / shown!.step) * shown!.step
        expect({ runner, field: FIELDS[i], shown: shown!.ms }).toEqual({
          runner,
          field: FIELDS[i],
          shown: rounded,
        })
        checked += 1
      })
    }
    expect(checked).toBe(9)
  })

  it("the cold column's overheads are the run's, over the ideal schedule", () => {
    const results = JSON.parse(
      readFileSync(
        path.resolve(import.meta.dir, '..', '..', '..', 'packages', 'vx-bench', 'results.json'),
        'utf8',
      ),
    ) as { baseline: Record<string, number>; rows: Array<Record<string, number | string>> }
    const post = readFileSync(path.join(BLOG, 'honest-benchmarks.md'), 'utf8')
    const mmss = (ms: number): string => {
      const s = Math.round(ms / 1000)
      return `${Math.floor(s / 60)}:${String(s % 60).padStart(2, '0')}`
    }
    let checked = 0
    for (const [runner, label] of [
      ['vx', 'vx'],
      ['turbo', 'Turborepo'],
      ['nx', 'Nx'],
    ] as const) {
      const fresh = results.rows.find((r) => r['runner'] === runner)!['fresh'] as number
      const over = mmss(fresh - results.baseline['workBoundMs']!)
      const row = new RegExp(`\\| ${label} +\\|[^|]*\\(\\+(${'[0-9:]+'})\\)`).exec(post)
      expect(row).not.toBeNull()
      expect({ runner, over: row![1] }).toEqual({ runner, over })
      checked += 1
    }
    expect(checked).toBe(3)
  })
})

// The task-config hash is stated in four places and only ONE was right.
// `task-hash.ts` computes `xxh3hex(JSON.stringify(hashableConfig(cfg)))`,
// and `hashableConfig` drops `exec.remote` — placement is not key
// material, which is the whole point of the executor seam.
// modules/config.md had it. caching.md (the stale-hit-critical contract
// page) and the blog post both omitted the projection, so read literally
// they put `exec.remote` IN the key; modules/execute-task.md omitted it
// AND named `sha256`, a function core replaced with xxh3 long ago and
// which appears in no `src/` file (item 396, 2026-09-19).
describe('every page stating the task-config hash states the projection', () => {
  it('names hashableConfig and xxh3, never sha256, wherever the formula appears', () => {
    const src = readFileSync(
      path.resolve(import.meta.dir, '..', 'src', 'orchestrator', 'task-hash.ts'),
      'utf8',
    )
    // The two facts the pages must not drift from, read from the module.
    expect(src).toContain('xxh3hex(JSON.stringify(hashableConfig(cfg)))')
    expect(/function hashableConfig[\s\S]*?remote: _remote/.test(src)).toBe(true)

    const pages = handAuthoredDocs()
    const stating: string[] = []
    const wrong: string[] = []
    for (const page of pages) {
      const text = readFileSync(page, 'utf8')
      // A page STATES the formula when it shows the stringify of a config.
      for (const m of text.matchAll(/`?\w+\(JSON\.stringify\(([^)]*[Cc]onfig)[^`\n]*/g)) {
        const claim = m[0]
        stating.push(`${path.basename(page)}: ${claim.slice(0, 60)}`)
        if (!claim.includes('hashableConfig')) wrong.push(`${path.basename(page)}: ${claim}`)
        if (/sha256/i.test(claim)) wrong.push(`${path.basename(page)}: ${claim}`)
      }
    }
    // Four copies today; a fifth must be a deliberate edit here.
    expect(stating.length).toBeGreaterThan(3)
    expect(wrong).toEqual([])
  })
})

// Item 385 fixed caching.md's numbered key-parts list — steps 11 and 12
// were inverted against the seed chain — and never greped for another
// copy. `blog/keys-from-git.md` numbers the same twelve parts, says so
// ("as Caching numbers them"), and still carried the inversion four items
// later, with its own prose contradicting its own number ("folded right
// after the upstream keys"). Item 381 recorded that exact failure once
// already; this is the grep that should have run then (item 397).
//
// The rule is DERIVED, not asserted: `key()`'s own fold order decides
// which of the two comes first, so a future reordering moves the pages
// with it rather than failing them.
describe('every page numbering the key parts folds plugin before inputs', () => {
  it('the order is the one key() uses, on each page that numbers them', () => {
    const src = readFileSync(
      path.resolve(import.meta.dir, '..', 'src', 'cache', 'key-fold.ts'),
      'utf8',
    )
    const body = src.slice(
      src.indexOf('let h = xxh3(CACHE_VERSION)'),
      src.indexOf('return h.toString(16)'),
    )
    const labels = [...body.matchAll(/h = xxh3\(`([a-z-]+):/g)].map((m) => m[1]!)
    expect(labels).toContain('plugin')
    expect(labels).toContain('inputs')
    expect(labels.indexOf('plugin')).toBeLessThan(labels.indexOf('inputs'))

    const pages: string[] = []
    const wrong: string[] = []
    for (const page of handAuthoredDocs()) {
      const text = readFileSync(page, 'utf8')
      // A page NUMBERS the parts when a numbered item names the sentinel
      // and another names the input-file glob.
      const items = [...text.matchAll(/^(\d+)\.[ ]([\s\S]*?)(?=^\d+\. |^\n*##? |\n\n(?!\s))/gm)]
      const sentinel = items.find((m) => m[2]!.includes('CACHE_VERSION'))
      // "content hashes", not the glob NAME: caching.md's config step
      // mentions `cache.inputs.files` among the declarations it captures,
      // so a search for the glob found step 5 and called the order wrong.
      const inputs = items.find((m) => /content hashes/i.test(m[2]!))
      const plugin = items.find((m) => /plugin'?s? `key` stage|Plugin key material/.test(m[2]!))
      if (sentinel === undefined || inputs === undefined || plugin === undefined) continue
      pages.push(path.basename(page))
      if (Number(plugin[1]) >= Number(inputs[1])) {
        wrong.push(`${path.basename(page)}: plugin is ${plugin[1]}, inputs ${inputs[1]}`)
      }
    }
    // Two copies today — caching.md and the blog post. A third is a
    // deliberate edit here, and an empty result cannot pass for agreement.
    expect(pages.length).toBeGreaterThan(1)
    expect(wrong).toEqual([])
  })
})

// `signals.ts` registers THREE handlers, and the third is the one the
// docs kept dropping: SIGHUP, which matters precisely because a task runs
// in its own session, so a closing terminal reaches vx and nothing else —
// without the forward, the tree outlives the window. `modules/signals.md`
// and `cli.md` had all three. `execution.md` said "SIGINT/SIGTERM
// handlers", `modules/orchestrator.md` said "SIGINT + SIGTERM handlers",
// and `blog/ctrl-c.md` — a post whose thesis is that EVERY way a run can
// end goes through one teardown — never said the word (item 398).
describe('every page enumerating the run signal handlers names all three', () => {
  it('the set is the one signals.ts registers, and 130/143/129 travel together', () => {
    const src = readFileSync(
      path.resolve(import.meta.dir, '..', 'src', 'orchestrator', 'signals.ts'),
      'utf8',
    )
    const registered = [...src.matchAll(/process\.on\('(SIG[A-Z]+)'/g)].map((m) => m[1]!)
    expect(registered.sort()).toEqual(['SIGHUP', 'SIGINT', 'SIGTERM'])

    const pages: string[] = []
    const wrong: string[] = []
    for (const page of handAuthoredDocs()) {
      const text = readFileSync(page, 'utf8')
      // A page ENUMERATES the set when it names the exit code SIGINT gets
      // on the vx process. 143 alone is a timeout's SIGTERM, 137 a SIGKILL;
      // 130 is only ever this.
      if (!/\b130\b/.test(text)) continue
      if (!/handler|teardown|Ctrl-C|every way a run/i.test(text)) continue
      // A page that DISCLAIMS installing handlers is not claiming the set:
      // `runner.md` says "Doesn't install signal handlers" and then maps
      // signals to codes generally, which is `signalExitCode`'s business,
      // not the run's. The first draft of this filter read that sentence as
      // a claim and reported the page missing SIGHUP.
      if (/Doesn't install signal handlers|does not install signal handlers/i.test(text)) continue
      pages.push(path.basename(page))
      // At the ENUMERATION SITE, not merely somewhere on the page: a first
      // draft asked whether the page contained the word SIGHUP at all, and
      // execution.md passed with "SIGINT/SIGTERM handlers" intact because a
      // later sentence happened to mention it. The same figure-wise mistake
      // item 395 made about a table cell.
      const flat = text.replace(/\s+/g, ' ')
      for (const m of flat.matchAll(/SIGINT[^.]{0,60}?SIGTERM/g)) {
        const site = flat.slice(m.index, m.index + m[0].length + 30)
        // A sentence naming a suite describes THAT FILE's cases, not the
        // handler set: `signal-handling.test.ts` covers SIGINT and SIGTERM
        // and `task-tree-kill.test.ts` covers SIGHUP, so signals.md's Tests
        // paragraph is right to pair only two.
        const sentence = flat.slice(Math.max(0, m.index! - 120), m.index! + 120)
        if (sentence.includes('.test.ts')) continue
        if (!site.includes('SIGHUP')) {
          wrong.push(`${path.basename(page)}: ${site.slice(0, 55)}`)
        }
      }
      if (!/\b129\b/.test(text)) wrong.push(`${path.basename(page)}: no 129 beside 130`)
    }
    // Four copies today; floored so an empty result cannot pass.
    expect(pages.length).toBeGreaterThan(3)
    expect(wrong).toEqual([])
  })
})
