// The out-of-project half of doc-references.test.ts: the site guides and
// CLAUDE.md name core files too, and live outside packages/vx, which a
// sandboxed shard cannot read (the cross-project law). Same rule, the
// unsafe suite.

import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'bun:test'
import { headingSlugs, proseLinks } from './helpers/markdown-anchors.js'
import { CACHE_VERSION, SCHEMA_VERSION } from '../src/cache/index.js'
import { TELEMETRY_SCHEMA_VERSION } from '../src/orchestrator/telemetry.js'

const pkg = path.resolve(import.meta.dir, '..')
const repo = path.resolve(pkg, '..', '..')

function walk(dir: string, ext: string, out: string[] = []): string[] {
  for (const name of readdirSync(dir)) {
    const p = path.join(dir, name)
    if (statSync(p).isDirectory()) walk(p, ext, out)
    else if (p.endsWith(ext)) out.push(p)
  }
  return out
}

describe('every core file path the guides and CLAUDE.md name exists', () => {
  it('src/, tests/ and docs/ paths resolve under packages/vx', () => {
    const files = [
      ...walk(path.join(repo, 'packages', 'vx-docs', 'src', 'content', 'docs', 'guides'), '.md'),
      path.join(repo, 'CLAUDE.md'),
    ]
    const missing: string[] = []
    for (const file of files) {
      const text = readFileSync(file, 'utf8')
      for (const m of text.matchAll(/`((?:src|tests|docs)\/[A-Za-z0-9_./-]+\.(?:ts|md|mjs))`/g)) {
        const ref = m[1]!
        if (!existsSync(path.join(pkg, ref))) missing.push(`${path.relative(repo, file)}: ${ref}`)
      }
    }
    expect(missing).toEqual([])
  })
})

/**
 * The site's own pages (the guides, the blog, the top-level pages; the
 * generated copies of `packages/vx/docs` are skipped — the source is
 * pinned by the safe half). A link is a URL — `../running-tasks/#…`,
 * `/vx/cli/#…` — so it resolves against the page's URL, and a page that
 * the import script generates is read from its source; a link with an
 * extension (an image, a config file) is a path beside the page.
 */
function sitePages(): string[] {
  return walk(path.join(repo, 'packages', 'vx-docs', 'src', 'content', 'docs'), '.md').filter(
    (p) => !readFileSync(p, 'utf8').startsWith('---\n# generated by '),
  )
}

const CONTENT = path.join(repo, 'packages', 'vx-docs', 'src', 'content', 'docs')
const CORE_DOCS = path.join(pkg, 'docs')

function siteSource(urlPath: string): string | undefined {
  const page = urlPath.replace(/^\/vx\//, '/').replace(/^\/|\/$/g, '')
  const core = page === 'overview' ? 'README' : page
  for (const candidate of [
    path.join(CORE_DOCS, `${core}.md`),
    path.join(CONTENT, `${page}.md`),
    path.join(CONTENT, page, 'index.md'),
  ]) {
    if (existsSync(candidate)) return candidate
  }
  return undefined
}

describe('every relative link on the site pages resolves', () => {
  it('`](../page/)` is a page, an asset link a file, and `#anchor` a heading by its rendered id', () => {
    const missing: string[] = []
    const slugs = new Map<string, Set<string>>()
    for (const file of sitePages()) {
      const rel = path.relative(CONTENT, file).split(path.sep).join('/')
      const urlDir = `/${rel.replace(/(^|\/)index\.md$/, '').replace(/\.md$/, '/')}`
      for (const { target, anchor } of proseLinks(readFileSync(file, 'utf8'))) {
        const link = `${rel}: ${target}${anchor === undefined ? '' : `#${anchor}`}`
        const source =
          target === ''
            ? file
            : /\.[a-z0-9]+$/i.test(target)
              ? path.resolve(path.dirname(file), target)
              : siteSource(path.posix.resolve(urlDir, `${target}/`))
        if (source === undefined || !existsSync(source)) {
          missing.push(link)
          continue
        }
        if (anchor === undefined || !source.endsWith('.md')) continue
        if (!slugs.has(source)) slugs.set(source, headingSlugs(readFileSync(source, 'utf8')))
        if (!slugs.get(source)!.has(anchor)) missing.push(link)
      }
    }
    expect(missing).toEqual([])
  })
})

describe('docs/README.md names every published plugin package', () => {
  it('the "published plugin packages" sentence names each non-private @vzn/vx-* sibling', () => {
    const readme = readFileSync(path.join(pkg, 'docs', 'README.md'), 'utf8')
    const sentence = /The published plugin packages are[\s\S]*?specifier/.exec(readme)
    expect(sentence).not.toBeNull()
    const named = new Set([...sentence![0].matchAll(/`(@vzn\/vx-[a-z-]+)`/g)].map((m) => m[1]!))
    const packagesDir = path.join(repo, 'packages')
    const published = readdirSync(packagesDir)
      .map((dir) => path.join(packagesDir, dir, 'package.json'))
      .filter((file) => existsSync(file))
      .map((file) => JSON.parse(readFileSync(file, 'utf8')) as { name: string; private?: boolean })
      .filter((manifest) => manifest.private !== true && manifest.name !== '@vzn/vx')
      .map((manifest) => manifest.name)
      .sort()
    expect([...named].sort()).toEqual(published)
  })
})

describe('docs/parity.md names suites that exist and the versions its suites cite', () => {
  it('every `tests/…` and `packages/…` deep pin resolves', () => {
    const doc = readFileSync(path.join(pkg, 'docs', 'parity.md'), 'utf8')
    const cited = [
      ...new Set([...doc.matchAll(/`((?:tests|packages)\/[\w./-]+)`/g)].map((m) => m[1]!)),
    ]
    expect(cited.length).toBeGreaterThan(40)
    const missing = cited.filter(
      (p) => !existsSync(p.startsWith('packages/') ? path.join(repo, p) : path.join(pkg, p)),
    )
    expect(missing).toEqual([])
  })

  // The paths resolving is not the claim the column makes: it says the
  // suite PINS the row. Two did not. `"cache": false` cited
  // no-cache-word.test.ts, which holds the WORD `no-cache` in the row,
  // legend and report and never reads `--summarize` — run-artifacts.test.ts
  // is where `noCache: true` is asserted. And `nx reset` cited
  // cache-hygiene.test.ts, which is about an interrupted run publishing
  // nothing and says `prune` nowhere (item 390, 2026-09-19).
  //
  // Where a row's vx cell names a flag or a config path, the check derives
  // the token from the row itself. Where it does not, the token is named
  // here — those are exactly the two that were wrong.
  const REQUIRED: Record<string, string> = { '"cache": false': 'noCache', 'nx reset': 'prune' }
  // Two dotted paths the suites prove but never spell: both are written as
  // config literals in the fixtures (`inputs: { files: [...] }`,
  // `passThrough: ['AWS_REGION']`). They are RE-SPELLED, not exempted —
  // dropping them would have left their rows with no token at all, which
  // is a row the check stops reading, not a row it passes.
  const ALIAS: Record<string, string> = {
    'cache.inputs.files': 'resolveInputs',
    'exec.env.passThrough': 'passThrough',
  }

  it('every deep-pin suite mentions what its row claims', () => {
    const doc = readFileSync(path.join(pkg, 'docs', 'parity.md'), 'utf8')
    const read = (f: string): string => {
      const abs = f.startsWith('packages/') ? path.join(repo, f) : path.join(pkg, f)
      if (!statSync(abs).isDirectory()) return readFileSync(abs, 'utf8')
      return walk(abs, '.ts')
        .map((g) => readFileSync(g, 'utf8'))
        .join('')
    }
    const gaps: string[] = []
    let checked = 0
    for (const line of doc.split('\n')) {
      if (!line.startsWith('| ') || line.startsWith('| ---')) continue
      const cells = line
        .trim()
        .replace(/^\||\|$/g, '')
        .split('|')
        .map((c) => c.trim())
      if (cells.length < 3) continue
      const [turbo, vx, pin] = cells as [string, string, string]
      const files = [...pin.matchAll(/`((?:tests|packages)\/[\w./-]+)`/g)].map((m) => m[1]!)
      if (files.length === 0) continue
      const tokens = new Set(
        [...vx.matchAll(/`(--[a-z-]+|[a-z]+\.[a-z][a-zA-Z.]+)`/g)]
          .map((m) => m[1]!)
          .filter((t) => t.length > 4)
          .map((t) => ALIAS[t] ?? t),
      )
      const named = REQUIRED[turbo.replace(/`/g, '')]
      if (named !== undefined) tokens.add(named)
      if (tokens.size === 0) continue
      checked += 1
      const blob = files.map(read).join('')
      for (const t of tokens) if (!blob.includes(t)) gaps.push(`${vx.slice(0, 40)} → ${t}`)
    }
    expect(checked).toBeGreaterThan(13)
    // Both REQUIRED rows must have been reached, or the map is dead weight.
    expect(Object.keys(REQUIRED).every((k) => doc.includes(k))).toBe(true)
    expect(gaps).toEqual([])
  })

  it('the Turbo and Nx versions are the ones the two parity suites name', () => {
    const doc = readFileSync(path.join(pkg, 'docs', 'parity.md'), 'utf8')
    const turbo = /\(turborepo\.dev, ([\d.]+)\)/.exec(doc)
    const nx = /\(nx\.dev, (\d+)\)/.exec(doc)
    expect(turbo).not.toBeNull()
    expect(nx).not.toBeNull()
    expect(readFileSync(path.join(pkg, 'tests', 'parity-turbo.test.ts'), 'utf8')).toContain(
      `(turborepo.dev/docs, ${turbo![1]})`,
    )
    expect(readFileSync(path.join(pkg, 'tests', 'parity-nx.test.ts'), 'utf8')).toContain(
      `(nx.dev, ${nx![1]})`,
    )
  })
})

describe("architecture.md's orchestrator inventory is the directory", () => {
  const doc = readFileSync(path.join(pkg, 'docs', 'architecture.md'), 'utf8')
  const start = doc.indexOf('| Layer                  | Files')
  const table = doc.slice(start, doc.indexOf('```mermaid', start))

  it('names every file in src/orchestrator but its index', () => {
    // A table of forty-odd filenames is a snapshot the moment a file lands
    // beside it; nothing held it until item 355 (2026-09-19).
    expect(start).toBeGreaterThan(-1)
    const named = new Set([...table.matchAll(/`([a-z-]+\.ts)`/g)].map((m) => m[1]!))
    const onDisk = readdirSync(path.join(pkg, 'src', 'orchestrator'))
      .filter((f) => f.endsWith('.ts') && f !== 'index.ts')
      .sort()
    expect(onDisk.length).toBeGreaterThan(30)
    expect(onDisk.filter((f) => !named.has(f))).toEqual([])
    expect([...named].filter((f) => !existsSync(path.join(pkg, 'src', 'orchestrator', f)))).toEqual(
      [],
    )
  })

  // Its runtime-floor paragraph said core's floor is `Bun.Archive` and the
  // answers that go wrong without it, the same sentence this repo carried
  // in CLAUDE.md and in package-boundaries' Rule 6 comment. The floor's
  // OWN docblock names three wrong answers and not the archive, and the
  // archive left `src/` entirely (item 389, 2026-09-19).
  it('states the floor the way bun-version.ts does', () => {
    const floor = readFileSync(path.join(pkg, 'src', 'util', 'bun-version.ts'), 'utf8')
    const para = doc.slice(
      doc.indexOf('RUNTIME floor'),
      doc.indexOf('## The plugin capability seam'),
    )
    expect(para.length).toBeGreaterThan(200)
    expect(para).not.toContain('Bun.Archive')
    expect(para).toContain('util/bun-version.ts')
    // The three the docblock measured, each named on the page in its own
    // words — a paragraph that keeps only one of them has stopped saying
    // what the floor is for.
    for (const claim of ['json', 'peakRssBytes', 'BuildMessage']) {
      expect(floor).toContain(claim)
      expect(para).toContain(claim)
    }
  })

  it('counts its own layers — it said five of a six-row table', () => {
    const rows = table
      .split('\n')
      .filter((l) => l.startsWith('| ') && !l.startsWith('| ---') && !l.startsWith('| Layer'))
    const words = ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight']
    // The sentence wraps, which is why a grep for "five layers" found nothing.
    const flat = doc.replace(/\s+/g, ' ')
    expect(flat).toContain(`its files fall into ${words[rows.length]} layers`)
  })
})

// The cache constants are quoted in five places. `caching-doc-drift.test.ts`
// holds the two inside `packages/vx/docs`; the other three live at the repo
// root, which a sandboxed shard cannot read, and nothing held them — CLAUDE.md
// § Live invariants, which tells a reader to "verify in source before
// quoting" (an admission that it rots), and the bump skill, whose whole job is
// to keep this set consistent (item 358, 2026-09-19).
describe('the repo-root files quote the cache constants as they are', () => {
  const repoRoot = path.resolve(import.meta.dir, '..', '..', '..')

  it('CLAUDE.md § Live invariants carries all three', async () => {
    const text = await Bun.file(path.join(repoRoot, 'CLAUDE.md')).text()
    expect(text).toContain(
      `- \`CACHE_VERSION\` \`${CACHE_VERSION}\`, core \`SCHEMA_VERSION\` \`${SCHEMA_VERSION}\`,\n` +
        `  \`TELEMETRY_SCHEMA_VERSION\` ${TELEMETRY_SCHEMA_VERSION}.`,
    )
  })

  it('the bump skill quotes the version it exists to increment', async () => {
    const skill = await Bun.file(
      path.join(repoRoot, '.claude', 'skills', 'bump-cache-version', 'SKILL.md'),
    ).text()
    expect(skill).toContain(`Current: \`${CACHE_VERSION}\``)
    expect(skill).toContain(`\`SCHEMA_VERSION\`\n\`${SCHEMA_VERSION}\``)
  })

  // The doc listed `CLAUDE.md` (decision log) — a section retired 2026-09-02 —
  // and left out STATUS.md, so a bump followed to the letter would update four
  // of the six files and miss the entry that says why (item 358).
  it("caching.md's bump procedure names the files the skill does", async () => {
    const skill = await Bun.file(
      path.join(repoRoot, '.claude', 'skills', 'bump-cache-version', 'SKILL.md'),
    ).text()
    const list = skill.slice(
      skill.indexOf('## Files to update'),
      skill.indexOf('## After the bump'),
    )
    const files = [...list.matchAll(/^\d+\. \*\*`([^`]+)`\*\*/gm)].map((m) =>
      (m[1] as string).replace('packages/vx/', ''),
    )
    expect(files.length).toBeGreaterThan(3)
    const doc = await Bun.file(path.join(import.meta.dir, '..', 'docs', 'caching.md')).text()
    const section = doc.slice(doc.indexOf('The bump procedure has a dedicated skill'))
    const para = section.slice(0, section.indexOf('\n\n###'))
    for (const file of files) {
      // caching.md is the page itself, and refers to itself as "this doc".
      expect(para).toContain(file === 'docs/caching.md' ? 'this doc' : `\`${file}\``)
    }
    expect(para).not.toContain('(decision log)')
  })
})

// Step 3's parenthetical explains the `fingerprint` seam by naming the two
// plugins that use it. A rename to the one-package shape left it saying
// "`@vzn/vx-lockfile` … `@vzn/vx-lockfile` is the same for `bun.lock`" — the
// package compared to itself, and neither helper named (item 358,
// 2026-09-19). Tie the sentence to the exports it is about.
describe('caching.md names the lockfile plugin by the helpers it exports', () => {
  it('step 3 names `pnpm()` and `bun()`, and the one this repo declares', async () => {
    const exported = new Set(
      [
        ...(
          await Bun.file(
            path.resolve(import.meta.dir, '..', '..', 'vx-lockfile', 'src', 'index.ts'),
          ).text()
        ).matchAll(/^export function (\w+)\(/gm),
      ].map((m) => m[1] as string),
    )
    expect([...exported].sort()).toEqual(['bun', 'npm', 'pnpm', 'yarn'])
    const doc = await Bun.file(path.join(import.meta.dir, '..', 'docs', 'caching.md')).text()
    const start = doc.indexOf('3. **Workspace fingerprint**')
    const step = doc.slice(start, doc.indexOf('\n4. **', start))
    expect(step).toContain('`pnpm()`')
    expect(step).toContain('`bun()`')
    // The workspace file decides which one "this repo declares".
    const ws = await Bun.file(
      path.resolve(import.meta.dir, '..', '..', '..', 'vx.workspace.ts'),
    ).text()
    const declared = [...exported].filter((f) => new RegExp(`\\b${f}\\(\\)`).test(ws))
    expect(declared).toEqual(['bun'])
    expect(step).toContain('its `bun()` is the same')
  })
})

// § Live invariants states four properties of the run path and, since item
// 364, names the suite that proves each. The audit that added them re-derived
// every one by grep — the proof existed for all four, nothing connected them
// to the claim, and that search is what the citations save. They are the same
// shape as flows.md's owners (item 353), so they rot the same way: hold each
// file to disk and each quoted describe to its file.
describe("CLAUDE.md's invariants cite suites that prove them", () => {
  it('every named test file exists and holds every describe quoted with it', async () => {
    const repoRoot = path.resolve(import.meta.dir, '..', '..', '..')
    const text = await Bun.file(path.join(repoRoot, 'CLAUDE.md')).text()
    const start = text.indexOf('## Live invariants')
    expect(start).toBeGreaterThan(-1)
    const section = text.slice(start, text.indexOf('\n## ', start + 1))
    // A citation is `tests/x.test.ts` plus the describes quoted before the
    // next citation or the end of its bullet.
    const cites = [...section.matchAll(/`(tests\/[\w.-]+\.ts)`((?:[^`]|`(?!tests\/))*)/g)]
    expect(cites.length).toBeGreaterThan(2)
    const missing: string[] = []
    for (const [, file, tail] of cites) {
      // That the file EXISTS is already held by the path pin above; this
      // adds the half nothing covered — that the suite still has the
      // describe the invariant points at. A missing file throws here, which
      // is loud enough.
      const abs = path.join(import.meta.dir, '..', file as string)
      // A quoted name wraps at CLAUDE.md's margin, so compare both sides
      // with their whitespace collapsed — the hazard item 355 hit from the
      // other side, where a grep for "five layers" missed "five\nlayers".
      const flat = (await Bun.file(abs).text()).replace(/\s+/g, ' ')
      // Only the quotes before the next bullet belong to this citation.
      const own = (tail as string).split('\n- ')[0] as string
      for (const q of own.matchAll(/"([^"]+)"/g)) {
        const name = (q[1] as string).replace(/\s+/g, ' ')
        if (!flat.includes(`describe('${name}'`)) {
          missing.push(`${file} has no describe "${name}"`)
        }
      }
    }
    expect(missing).toEqual([])
  })
})

// A design doc is a record of intent at a date, and a stale record is fine —
// until live documentation promotes one to a contract. Item 371 found
// `pipeline-2026-09.md`, marked "shipped", carrying a rule the local floor had
// replaced, and CLAUDE.md sends readers there for the seam contract. The
// general shape: a design doc CITED by a live page (or by CLAUDE.md) must say
// what became of it, so a reader knows whether they are holding a contract or
// a snapshot. Uncited design docs are left alone on purpose — rewriting the
// record of a rejected shape destroys the evidence it was considered
// (item 372, 2026-09-19).
describe('every design doc live documentation cites says what became of it', () => {
  it('each cited design page carries a status line', async () => {
    const pkg = path.resolve(import.meta.dir, '..')
    const repoRoot = path.resolve(pkg, '..', '..')
    const citers = [
      path.join(repoRoot, 'CLAUDE.md'),
      // `scanSync` yields an iterator, not an array — spread before mapping.
      ...[...new Bun.Glob('docs/*.md').scanSync({ cwd: pkg })].map((r) => path.join(pkg, r)),
      ...[...new Bun.Glob('docs/modules/*.md').scanSync({ cwd: pkg })].map((r) =>
        path.join(pkg, r),
      ),
    ]
    const cited = new Set<string>()
    for (const file of citers) {
      // STATUS.md logs history, including designs that were superseded.
      if (path.basename(file) === 'STATUS.md') continue
      for (const m of (await Bun.file(file).text()).matchAll(/design\/([a-z0-9-]+)\.md/g)) {
        cited.add(m[1] as string)
      }
    }
    expect(cited.size).toBeGreaterThan(4)
    const missing: string[] = []
    for (const name of [...cited].sort()) {
      const head = (await Bun.file(path.join(pkg, 'docs', 'design', `${name}.md`)).text())
        .split('\n')
        .slice(0, 12)
        .join('\n')
      // A dated survey states its own vintage instead ("Generated: <date>").
      if (!/\*\*Status[:*]|Status: \*\*|Generated: \d{4}-\d{2}-\d{2}/.test(head)) {
        missing.push(name)
      }
    }
    expect(missing).toEqual([])
  })
})

/**
 * CLAUDE.md § Stack named `Bun.Archive` a hard dependency for months after
 * the artifact container stopped using it: `archive.ts` says in its own
 * header that it "used to do all three" and that vx's streaming tar code
 * replaced it (2026-09-03, for the memory peaks). Zero `src/` files call
 * it — only `archive-security.test.ts`, as an independent oracle against
 * vx's own writer. The same stale sentence rode two more copies,
 * architecture.md's runtime-floor paragraph and this suite's own Rule 6
 * comment, each claiming the floor is `Bun.Archive` where
 * `util/bun-version.ts` names three wrong ANSWERS instead (item 389,
 * 2026-09-19). Discovered from the sentence, so a name added to it is
 * held without an edit here.
 */
describe('CLAUDE.md names Bun APIs core actually calls', () => {
  it('every hard dependency it lists is used outside a comment, and Archive is not', async () => {
    const claude = await Bun.file(path.join(repo, 'CLAUDE.md')).text()
    const sentence = /Bun ≥ [\d.]+ only \(([\s\S]*?)are\s*\n?hard dependencies/.exec(claude)
    expect(sentence).not.toBeNull()
    const named = [...sentence![1]!.matchAll(/`(Bun\.[A-Za-z]+\*?|bun:[a-z]+)`/g)].map((m) => m[1]!)
    expect(named.length).toBeGreaterThan(3)

    // Comments are where a retired API lingers, so they are exactly what
    // must not count as a use.
    let code = ''
    const srcs = new Bun.Glob('*/src/**/*.ts')
    for await (const rel of srcs.scan({ cwd: path.join(repo, 'packages') })) {
      const text = await Bun.file(path.join(repo, 'packages', rel)).text()
      for (const line of text.split('\n')) {
        const t = line.trim()
        if (t.startsWith('//') || t.startsWith('*') || t.startsWith('/*')) continue
        code += `${line.replace(/\/\/.*$/, '')}\n`
      }
    }
    expect(code.length).toBeGreaterThan(100_000)

    const unused = named.filter((n) => !code.includes(n.endsWith('*') ? n.slice(0, -1) : n))
    expect(unused).toEqual([])
    // The claim the corrected sentence makes in the other direction.
    expect(code).not.toContain('Bun.Archive')
  })
})

/**
 * The 3,270-task table is the only table in the docs backed by a committed
 * data file (`packages/vx-bench/results.json`), and the page re-derives
 * every ratio and overhead from it BY HAND: five rows × three runners,
 * ten `(N×)` ratios, a baseline row and three measured floors. Nothing
 * held any of it, and README and patterns.md quote onward from here.
 *
 * Numbers, not spellings: each displayed figure is parsed back to
 * milliseconds and compared against the file within the granularity the
 * page chose to print. Re-implementing the formatter here would only
 * restate its assumptions (CLAUDE.md § Rules: a platform unit is measured,
 * never asserted) — this asks what the page CLAIMS, not how it writes it.
 * Read 2026-09-19 (item 391): every figure already agreed.
 */
describe('benchmarks.md quotes the run results.json recorded', () => {
  /** `3m 46s`, `34.61s`, `1.17s`, `510ms` → ms, with the step it was printed to. */
  const parse = (raw: string): { ms: number; step: number } | null => {
    let m = /^(\d+)m (\d+)s$/.exec(raw)
    if (m !== null) return { ms: (Number(m[1]) * 60 + Number(m[2])) * 1000, step: 1000 }
    m = /^(\d+(?:\.\d+)?)s$/.exec(raw)
    if (m !== null) {
      const decimals = (m[1]!.split('.')[1] ?? '').length
      return { ms: Number(m[1]) * 1000, step: 1000 / 10 ** decimals }
    }
    m = /^(\d+)ms$/.exec(raw)
    return m === null ? null : { ms: Number(m[1]), step: 1 }
  }

  const FIELD: Record<string, string> = {
    Cold: 'fresh',
    'Warm**, nothing to rebuild': 'warmNoRestore',
    'Warm**, restore outputs': 'warmRestore',
    'CPU burned**, cold': 'freshCpu',
    'CPU burned**, warm': 'warmNoRestoreCpu',
  }

  it('every figure and every ratio in the 3,270-task table is the recorded one', () => {
    const doc = readFileSync(path.join(pkg, 'docs', 'benchmarks.md'), 'utf8')
    const results = JSON.parse(
      readFileSync(path.join(repo, 'packages', 'vx-bench', 'results.json'), 'utf8'),
    ) as {
      packages: number
      baseline: Record<string, number>
      rows: Array<Record<string, number | string>>
    }
    const by = (name: string): Record<string, number | string> =>
      results.rows.find((r) => r['runner'] === name) as Record<string, number | string>
    // The table's three columns, left to right.
    const runners = ['vx', 'turbo', 'nx'] as const

    const start = doc.indexOf('## A real monorepo: 3,270 tasks')
    expect(start).toBeGreaterThan(0)
    const table = doc.slice(start, doc.indexOf('**Baseline** is the theoretical best', start))
    const wrong: string[] = []
    let rowsChecked = 0

    for (const line of table.split('\n')) {
      if (!line.startsWith('| **')) continue
      const cells = line
        .trim()
        .replace(/^\||\|$/g, '')
        .split('|')
        .map((c) => c.trim())
      const label = Object.keys(FIELD).find((k) => cells[0]!.includes(k))
      if (label === undefined) continue
      const field = FIELD[label]!
      rowsChecked += 1
      const vxMs = by('vx')[field] as number
      cells.slice(1, 4).forEach((cell, i) => {
        const runner = runners[i]!
        const shown = parse(
          cell
            .replace(/\*\*/g, '')
            .replace(/\s*\(.*$/, '')
            .trim(),
        )
        const actual = by(runner)[field] as number
        if (shown === null) {
          wrong.push(`${field}/${runner}: unreadable ${cell}`)
          return
        }
        // The page must show what ROUNDING the measurement to that precision
        // gives, not merely land within one step of it: a one-step tolerance
        // let 510ms become 511ms and still pass (item 395 caught that on this
        // pin's sibling over the blog's copy of the same table).
        if (shown.ms !== Math.round(actual / shown.step) * shown.step) {
          wrong.push(`${field}/${runner}: page ${shown.ms}ms, file ${actual.toFixed(1)}ms`)
        }
        const ratio = /\(([\d.]+)×\)/.exec(cell)
        if (ratio === null) return
        const want = actual / vxMs
        if (Math.abs(Number(ratio[1]) - want) > 0.05) {
          wrong.push(`${field}/${runner}: page ${ratio[1]}×, file ${want.toFixed(2)}×`)
        }
      })
    }
    expect(rowsChecked).toBe(5)
    expect(wrong).toEqual([])
  })

  it('the baseline row and the measured floors are the recorded ones', () => {
    const doc = readFileSync(path.join(pkg, 'docs', 'benchmarks.md'), 'utf8')
    const { baseline, rows, packages } = JSON.parse(
      readFileSync(path.join(repo, 'packages', 'vx-bench', 'results.json'), 'utf8'),
    ) as {
      packages: number
      baseline: Record<string, number>
      rows: Array<Record<string, number | string>>
    }
    const secs = (ms: number): string => {
      const s = Math.round(ms / 1000)
      return `${Math.floor(s / 60)}m ${String(s % 60).padStart(2, '0')}s`
    }
    // `3m 38s cold` is workBoundMs; the floors are the baseline's own warm,
    // restore and task-shell CPU numbers.
    expect(doc).toContain(`${secs(baseline['workBoundMs']!).replace('m 0', 'm ')} cold`)
    expect(doc).toContain(`critical path ${secs(baseline['criticalPathMs']!).replace('m 0', 'm ')}`)
    expect(doc).toContain(`git walk ${Math.round(baseline['warmNoRestore']!)}ms`)
    expect(doc).toContain(`raw copy ${Math.round(baseline['warmRestore']!)}ms`)
    expect(doc).toContain(`task shells ${(baseline['freshCpu']! / 1000).toFixed(2)}s`)

    // The per-package overhead sentence: each runner's cold time over the
    // ideal schedule, and that difference divided by the package count.
    const overhead = (runner: string): number =>
      (rows.find((r) => r['runner'] === runner)!['fresh'] as number) - baseline['workBoundMs']!
    expect(doc).toContain(`is\n${(overhead('vx') / 1000).toFixed(2)}s on 3,270 tasks`)
    expect(doc).toContain(`(${Math.round(overhead('vx') / packages)} ms per package)`)
    expect(doc).toContain(`(${Math.round(overhead('turbo') / packages)} ms per package)`)
    expect(doc).toContain(
      `(${Math.round(overhead('nx') / packages).toLocaleString('en-US')} ms per package)`,
    )
  })
})
