// CLASS pins: the greps that hold a claim across EVERY hand-authored page,
// rather than one page against its source. They grew up inside
// site-samples.unsafe.test.ts because that file already read both doc trees,
// and by item 361 it carried 226 of the suite's 411 assertions and every one
// of these. That is why item 358's pin landed in the wrong suite and why the
// shared helper had to be added to a file named for renderer samples.
//
// They live here now, over one contract: `handAuthoredDocs()` is the page
// list, `CLASS_PAGES` names what each narrowing filter actually reaches. A
// move, not a rewrite — item 365 (2026-09-19) held the assertion count across
// it, so nothing was dropped in the carry.
//
// The site lives outside packages/vx, which a sandboxed shard cannot read;
// hence the unsafe suite.
import { readFileSync, readdirSync } from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'bun:test'
import { ESSENTIAL_ENV } from '../src/exec/env.js'

const DOCS = path.resolve(import.meta.dir, '..', '..', 'vx-docs', 'src', 'content', 'docs')

/**
 * Which hand-authored pages each class grep actually reaches. A class pin
 * narrows the page list to "the pages that mention X" and then asserts
 * something about them — so the day X is reworded the filter empties and the
 * pin passes having checked nothing, which is the drift it exists to catch.
 * Naming the members makes that a failure (item 361, 2026-09-19); a page
 * joining or leaving a class is a deliberate edit here.
 */
const CLASS_PAGES = {
  remoteCacheLayer: [
    'README.md',
    'architecture.md',
    'cli.md',
    'comparison.md',
    'extensibility.md',
    'flows.md',
    'index.md',
    'layered-cache.md',
    'options.md',
    'patterns.md',
    'plugins.md',
    'remote-caching.md',
  ],
  retryLine: ['execute-task.md', 'schema.md'],
}

/**
 * Every markdown page a person wrote, in both doc trees. `history/` and
 * `design/` are records of what was true then, STATUS.md quotes old wording
 * on purpose, and the site's copies of `packages/vx/docs` are rewritten by
 * the docs build — a class grep that reads them finds its own fix twice.
 */
function handAuthoredDocs(): string[] {
  const pages: string[] = []
  const walk = (dir: string): void => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const p = path.join(dir, entry.name)
      if (entry.isDirectory()) {
        if (entry.name !== 'history' && entry.name !== 'design') walk(p)
      } else if (entry.name.endsWith('.md') && entry.name !== 'STATUS.md') {
        const text = readFileSync(p, 'utf8')
        if (!text.includes('# generated by packages/vx-docs/scripts/import-docs.ts')) pages.push(p)
      }
    }
  }
  for (const root of [DOCS, path.resolve(import.meta.dir, '..', 'docs')]) walk(root)
  return pages
}

describe('no page still calls the remote seam a three-call one', () => {
  it('every hand-authored page that names the seam names its four methods', () => {
    // Item 346 fixed remote-caching.md and never grepped the class: the same
    // sentence sat on extensibility.md, plugins.md and architecture.md
    // (item 349, 2026-09-19). This pin is the grep.
    const src = readFileSync(
      path.resolve(import.meta.dir, '..', 'src', 'cache', 'layered-cache.ts'),
      'utf8',
    )
    const decl = /export interface RemoteCacheLayer \{([\s\S]*?)\n\}/.exec(src)
    const methods = [...decl![1]!.matchAll(/^  (\w+)\??\(/gm)].map((m) => m[1]!)
    expect(methods.length).toBe(4)
    const roots = [DOCS, path.resolve(import.meta.dir, '..', 'docs')]
    const pages: string[] = []
    const walk = (dir: string): void => {
      for (const entry of readdirSync(dir, { withFileTypes: true })) {
        const p = path.join(dir, entry.name)
        if (entry.isDirectory()) {
          if (entry.name !== 'history' && entry.name !== 'design') walk(p)
        } else if (entry.name.endsWith('.md')) pages.push(p)
      }
    }
    for (const root of roots) walk(root)
    expect(pages.length).toBeGreaterThan(20)
    const checked: string[] = []
    for (const page of pages) {
      const text = readFileSync(page, 'utf8')
      if (!text.includes('RemoteCacheLayer')) continue
      // STATUS logs the old wording as a quote, and the site's generated
      // copies are rewritten from `packages/vx/docs` by the docs build.
      if (path.basename(page) === 'STATUS.md') continue
      if (text.includes('# generated by packages/vx-docs/scripts/import-docs.ts')) continue
      checked.push(path.basename(page))
      expect({ page: path.basename(page), says: /three-call/.test(text) }).toEqual({
        page: path.basename(page),
        says: false,
      })
    }
    // The pages in the class, named: a rename of the seam would otherwise
    // empty the filter and pass this checking nothing (item 361).
    expect([...new Set(checked)].sort()).toEqual(CLASS_PAGES.remoteCacheLayer)
  })
})

describe('no page says a failed task aborts its dependents', () => {
  it('every hand-authored page uses the status the scheduler sets', () => {
    // Item 348 fixed task-dependencies.md and did not grep the class; the
    // same sentence sat on the how-vx-works concept (item 350, 2026-09-19).
    // `aborted` is what teardown sets, `skipped` is what a failed upstream
    // leaves behind, and the pages must not swap them.
    const src = readFileSync(
      path.resolve(import.meta.dir, '..', 'src', 'graph', 'scheduler.ts'),
      'utf8',
    )
    expect(src).toContain("| 'skipped'")
    expect(src).toContain("| 'aborted'")
    const roots = [DOCS, path.resolve(import.meta.dir, '..', 'docs')]
    const pages: string[] = []
    const walk = (dir: string): void => {
      for (const entry of readdirSync(dir, { withFileTypes: true })) {
        const p = path.join(dir, entry.name)
        if (entry.isDirectory()) {
          if (entry.name !== 'history' && entry.name !== 'design') walk(p)
        } else if (entry.name.endsWith('.md') && entry.name !== 'STATUS.md') pages.push(p)
      }
    }
    for (const root of roots) walk(root)
    for (const page of pages) {
      const text = readFileSync(page, 'utf8')
      expect({
        page: path.basename(page),
        aborts: /aborts? (its|the) (transitive )?dependents/.test(text),
      }).toEqual({
        page: path.basename(page),
        aborts: false,
      })
    }
  })
})

describe('every --frozen figure on a page is one benchmarks.md measured', () => {
  it('no page quotes a frozen speed number the benchmarks page does not have', () => {
    // Item 346 struck the CI guide's "roughly 10–21%" and did not grep the
    // class: the root README still sold "~120 ms back per 1,000 packages"
    // (item 351, 2026-09-19). The 2026-09-12 head-to-head reads as a tie.
    const bench = readFileSync(path.resolve(import.meta.dir, '..', 'docs', 'benchmarks.md'), 'utf8')
    const roots = [
      DOCS,
      path.resolve(import.meta.dir, '..', 'docs'),
      path.resolve(import.meta.dir, '..', '..', '..'),
    ]
    const pages = new Set<string>()
    const walk = (dir: string, depth: number): void => {
      for (const entry of readdirSync(dir, { withFileTypes: true })) {
        if (entry.name.startsWith('.') || entry.name === 'node_modules') continue
        const p = path.join(dir, entry.name)
        if (entry.isDirectory()) {
          if (depth > 0 && entry.name !== 'history' && entry.name !== 'design') walk(p, depth - 1)
        } else if (entry.name.endsWith('.md') && entry.name !== 'STATUS.md') pages.add(p)
      }
    }
    walk(roots[0]!, 3)
    walk(roots[1]!, 1)
    walk(roots[2]!, 0)
    expect(pages.size).toBeGreaterThan(20)
    let paragraphs = 0
    for (const page of pages) {
      const text = readFileSync(page, 'utf8')
      for (const para of text.split(/\n\s*\n/)) {
        if (!para.includes('--frozen') && !para.includes('`vx lock`')) continue
        paragraphs += 1
        // A figure attached to a frozen claim must be the benchmarks page's.
        for (const m of para.matchAll(/(\d+(?:[–-]\d+)?)\s?(%|ms)\b/g)) {
          expect({ page: path.basename(page), figure: m[0] }).toEqual({
            page: path.basename(page),
            figure: bench.includes(m[1]!) ? m[0] : `${m[0]} — not on benchmarks.md`,
          })
        }
      }
    }
    // Without this the pin passes on nothing the day `--frozen` is reworded
    // — the drift it exists to catch (item 361).
    expect(paragraphs).toBeGreaterThan(20)
  })
})

describe('no doc describes exec.resources as a field a config can declare', () => {
  it('the field is gone from the schema, and no page says otherwise', () => {
    // It left the config on 2026-09-12 with the reservations. Item 347 fixed
    // four pages and did not grep the module docs, where config-schema.md
    // still had the validator checking it (item 352, 2026-09-19).
    const config = readFileSync(path.resolve(import.meta.dir, '..', 'src', 'config.ts'), 'utf8')
    const schema = readFileSync(
      path.resolve(import.meta.dir, '..', 'src', 'workspace', 'config-schema.ts'),
      'utf8',
    )
    expect(/^\s+resources\??:/m.test(config)).toBe(false)
    expect(schema.includes('resources')).toBe(false)
    const roots = [DOCS, path.resolve(import.meta.dir, '..', 'docs')]
    const pages: string[] = []
    const walk = (dir: string): void => {
      for (const entry of readdirSync(dir, { withFileTypes: true })) {
        const p = path.join(dir, entry.name)
        if (entry.isDirectory()) {
          // `design/` records the decision that removed it; `history/` logs it.
          if (entry.name !== 'history' && entry.name !== 'design') walk(p)
        } else if (entry.name.endsWith('.md') && entry.name !== 'STATUS.md') pages.push(p)
      }
    }
    for (const root of roots) walk(root)
    expect(pages.length).toBeGreaterThan(40)
    for (const page of pages) {
      const text = readFileSync(page, 'utf8')
      // The site's generated copies are rewritten from `packages/vx/docs`
      // by the docs build; the source above is the one to hold.
      if (text.includes('# generated by packages/vx-docs/scripts/import-docs.ts')) continue
      expect({
        page: path.basename(page),
        claims: /`exec\.resources`|`resources` are |, `resources`,/.test(text),
      }).toEqual({ page: path.basename(page), claims: false })
    }
  })
})

// Two claims about one stderr line: `execute-task.ts` ends the retry notice
// `after a timeout` when the kill was the timeout's and `after exit <code>`
// otherwise, and both pages that quote the line quoted only the second —
// modules/execute-task.md in the same bullet that says "timeouts included"
// (item 357, 2026-09-19). A user greps the message they got; half a message
// finds nothing.
describe('every page quoting the retry line quotes both its endings', () => {
  it('the two spellings are the ones execute-task.ts emits', () => {
    const src = readFileSync(
      path.resolve(import.meta.dir, '..', 'src', 'orchestrator', 'execute-task.ts'),
      'utf8',
    )
    expect(src).toContain("'a timeout'")
    expect(src).toContain('after ${')
    const pages = handAuthoredDocs()
    expect(pages.length).toBeGreaterThan(40)
    const checked: string[] = []
    for (const page of pages) {
      const text = readFileSync(page, 'utf8')
      if (!text.includes('vx: retrying <id>')) continue
      checked.push(path.basename(page))
      expect({ page: path.basename(page), both: text.includes('after a timeout') }).toEqual({
        page: path.basename(page),
        both: true,
      })
    }
    expect(checked.sort()).toEqual(CLASS_PAGES.retryLine)
  })
})

// The formatter reflows prose, and a reflow can break the markdown under it:
// schema.md's "(the count of names + the names themselves …)" wrapped so the
// `+` landed at the start of a line, and oxfmt turned it into a BULLET in the
// middle of a sentence — which is how it shipped to the site (item 357,
// 2026-09-19). A paragraph whose parentheses do not balance is the signature
// of that class, and cheap to check on every page at once.

// The formatter reflows prose, and a reflow can break the markdown under it:
// schema.md's "(the count of names + the names themselves …)" wrapped so the
// `+` landed at the start of a line, and oxfmt turned it into a BULLET in the
// middle of a sentence — which is how it shipped to the site (item 357,
// 2026-09-19). A paragraph whose parentheses do not balance is the signature
// of that class, and cheap to check on every page at once.
describe('no prose block was broken open by a reflow', () => {
  it('every paragraph and list item closes the parentheses it opens', () => {
    const broken: string[] = []
    const pages = handAuthoredDocs()
    expect(pages.length).toBeGreaterThan(40)
    for (const page of pages) {
      const text = readFileSync(page, 'utf8')
      let fenced = false
      let block: string[] = []
      let start = 0
      const flush = (): void => {
        if (block.length === 0) return
        // Code spans hold shell and glob punctuation that is not prose.
        const prose = block
          .join('\n')
          .replace(/`[^`]*`/g, '')
          .replace(/`[^`]*$/, '')
        if (prose.split('(').length !== prose.split(')').length) {
          broken.push(`${path.basename(page)}:${start}`)
        }
        block = []
      }
      text.split('\n').forEach((line, i) => {
        if (line.trim().startsWith('```')) {
          fenced = !fenced
          flush()
          return
        }
        if (fenced) return
        if (line.trim() === '') {
          flush()
          return
        }
        if (block.length === 0) start = i + 1
        block.push(line)
      })
      flush()
    }
    expect(broken).toEqual([])
  })
})

// The glyph set is `glyphShape` in framed-output.ts plus the `▸` a pinned
// persistent row carries. Two pages and the module's own docblock listed a
// seventh, `⦿ running`, which the renderer has never printed: a live worker
// row leads with its ticking elapsed time and carries NO glyph, as
// status-line.ts says in the same breath (item 359, 2026-09-19). Item 302
// struck one glyph a docblock invented and never grepped the class; this is
// the grep, over the three places that enumerate the set.

// "What does my build script actually see?" is answered by four pages, and
// only schema.md's copy was pinned — the copy that had already drifted once
// (USER, LOGNAME, TEMP and TMP were passed to every task and named nowhere,
// the note on that pin). The other three name every POSIX essential today
// and each defers the Windows set in words; hold them there (item 359,
// 2026-09-19).
describe('every page listing the env allowlist lists all of it', () => {
  it('each names every POSIX essential, and the contract page all 25', () => {
    const posix = ESSENTIAL_ENV.slice(0, ESSENTIAL_ENV.indexOf('SYSTEMROOT'))
    expect(posix.length).toBe(17)
    const pages = handAuthoredDocs().filter((p) => readFileSync(p, 'utf8').includes('`LOGNAME`'))
    // schema.md (pinned separately), execution.md, modules/env.md, and the
    // environment-variables guide. A fifth copy lands here unpinned no more.
    expect(pages.map((p) => path.basename(p)).sort()).toEqual([
      'env.md',
      'environment-variables.md',
      'execution.md',
      'schema.md',
    ])
    for (const page of pages) {
      const text = readFileSync(page, 'utf8')
      const names = page.endsWith('modules/env.md') ? ESSENTIAL_ENV : posix
      expect({
        page: path.basename(page),
        missing: names.filter((n) => !text.includes(`\`${n}\``)),
      }).toEqual({ page: path.basename(page), missing: [] })
    }
  })
})

// The task-timeout ladder has FOUR rungs and a page that drops one inverts
// nothing — it just hides the rung a user actually types. The
// workspace-config guide read "a task's own `exec.timeout`, then the
// `VX_TASK_TIMEOUT` env var, then this", leaving `--timeout` out entirely,
// while schema.md, cli.md, `options.ts`, `run.ts` and
// `options-resolve.test.ts`'s header all name all four (item 378,
// 2026-09-19). The behaviour is pinned; the pages were not.
describe('every page stating the timeout ladder states all four rungs', () => {
  it('names exec.timeout, --timeout, VX_TASK_TIMEOUT and the workspace default', () => {
    // The ladder itself, from the one expression that resolves it. If this
    // line moves, the rung names below are no longer the code's.
    const run = readFileSync(
      path.resolve(import.meta.dir, '..', 'src', 'orchestrator', 'run.ts'),
      'utf8',
    )
    expect(run).toContain(
      'options.timeout ?? readTaskTimeoutEnv() ?? workspaceConfig?.timeout ?? undefined',
    )
    const pages = handAuthoredDocs().filter((p) =>
      readFileSync(p, 'utf8').includes('VX_TASK_TIMEOUT'),
    )
    // cli.md, schema.md and the workspace-config guide. A fourth copy lands
    // here unpinned no more.
    expect(pages.map((p) => path.basename(p)).sort()).toEqual([
      'cli.md',
      'schema.md',
      'workspace-config.md',
    ])
    for (const page of pages) {
      const text = readFileSync(page, 'utf8')
      expect({
        page: path.basename(page),
        missing: ['exec.timeout', '--timeout', 'VX_TASK_TIMEOUT'].filter(
          (rung) => !text.includes(rung),
        ),
      }).toEqual({ page: path.basename(page), missing: [] })
    }
  })
})
