// The out-of-project half of doc-references.test.ts: the site guides and
// CLAUDE.md name core files too, and live outside packages/vx, which a
// sandboxed shard cannot read (the cross-project law). Same rule, the
// unsafe suite.

import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'bun:test'
import { anchoredLinks, headingSlugs } from './helpers/markdown-anchors.js'

const pkg = path.resolve(import.meta.dir, '..')
const repo = path.resolve(pkg, '..', '..')

function walk(dir: string, ext: string, out: string[] = []): string[] {
  for (const name of readdirSync(dir)) {
    const p = path.join(dir, name)
    if (statSync(p).isDirectory()) walk(p, ext, out)
    else if (p.endsWith(ext)) out.push(p)
  }
  return out
}

describe('every core file path the guides and CLAUDE.md name exists', () => {
  it('src/, tests/ and docs/ paths resolve under packages/vx', () => {
    const files = [
      ...walk(path.join(repo, 'packages', 'vx-docs', 'src', 'content', 'docs', 'guides'), '.md'),
      path.join(repo, 'CLAUDE.md'),
    ]
    const missing: string[] = []
    for (const file of files) {
      const text = readFileSync(file, 'utf8')
      for (const m of text.matchAll(/`((?:src|tests|docs)\/[A-Za-z0-9_./-]+\.(?:ts|md|mjs))`/g)) {
        const ref = m[1]!
        if (!existsSync(path.join(pkg, ref))) missing.push(`${path.relative(repo, file)}: ${ref}`)
      }
    }
    expect(missing).toEqual([])
  })
})

/**
 * The site's own pages (the guides, the blog, the top-level pages; the
 * generated copies of `packages/vx/docs` are skipped — the source is
 * pinned by the safe half). A link is a URL — `../running-tasks/#…`,
 * `/vx/cli/#…` — so it resolves against the page's URL, and a page that
 * the import script generates is read from its source.
 */
function sitePages(): string[] {
  return walk(path.join(repo, 'packages', 'vx-docs', 'src', 'content', 'docs'), '.md').filter(
    (p) => !readFileSync(p, 'utf8').startsWith('---\n# generated by '),
  )
}

const CONTENT = path.join(repo, 'packages', 'vx-docs', 'src', 'content', 'docs')
const CORE_DOCS = path.join(pkg, 'docs')

function siteSource(urlPath: string): string | undefined {
  const page = urlPath.replace(/^\/vx\//, '/').replace(/^\/|\/$/g, '')
  const core = page === 'overview' ? 'README' : page
  for (const candidate of [
    path.join(CORE_DOCS, `${core}.md`),
    path.join(CONTENT, `${page}.md`),
    path.join(CONTENT, page, 'index.md'),
  ]) {
    if (existsSync(candidate)) return candidate
  }
  return undefined
}

describe('every heading anchor the site pages link to exists', () => {
  it('`](../page/#anchor)` names a heading of that page by its rendered id', () => {
    const missing: string[] = []
    const slugs = new Map<string, Set<string>>()
    for (const file of sitePages()) {
      const rel = path.relative(CONTENT, file).split(path.sep).join('/')
      const urlDir = `/${rel.replace(/(^|\/)index\.md$/, '').replace(/\.md$/, '/')}`
      for (const { target, anchor } of anchoredLinks(readFileSync(file, 'utf8'))) {
        if (/^[a-z]+:/.test(target)) continue
        const source =
          target === '' ? file : siteSource(path.posix.resolve(urlDir, target.replace(/\/?$/, '/')))
        if (source === undefined) {
          missing.push(`${rel}: ${target}#${anchor} (no page)`)
          continue
        }
        if (!slugs.has(source)) slugs.set(source, headingSlugs(readFileSync(source, 'utf8')))
        if (!slugs.get(source)!.has(anchor)) missing.push(`${rel}: ${target}#${anchor}`)
      }
    }
    expect(missing).toEqual([])
  })
})
