// The out-of-project half of doc-references.test.ts: the site guides and
// CLAUDE.md name core files too, and live outside packages/vx, which a
// sandboxed shard cannot read (the cross-project law). Same rule, the
// unsafe suite.

import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'bun:test'
import { headingSlugs, proseLinks } from './helpers/markdown-anchors.js'

const pkg = path.resolve(import.meta.dir, '..')
const repo = path.resolve(pkg, '..', '..')

function walk(dir: string, ext: string, out: string[] = []): string[] {
  for (const name of readdirSync(dir)) {
    const p = path.join(dir, name)
    if (statSync(p).isDirectory()) walk(p, ext, out)
    else if (p.endsWith(ext)) out.push(p)
  }
  return out
}

describe('every core file path the guides and CLAUDE.md name exists', () => {
  it('src/, tests/ and docs/ paths resolve under packages/vx', () => {
    const files = [
      ...walk(path.join(repo, 'packages', 'vx-docs', 'src', 'content', 'docs', 'guides'), '.md'),
      path.join(repo, 'CLAUDE.md'),
    ]
    const missing: string[] = []
    for (const file of files) {
      const text = readFileSync(file, 'utf8')
      for (const m of text.matchAll(/`((?:src|tests|docs)\/[A-Za-z0-9_./-]+\.(?:ts|md|mjs))`/g)) {
        const ref = m[1]!
        if (!existsSync(path.join(pkg, ref))) missing.push(`${path.relative(repo, file)}: ${ref}`)
      }
    }
    expect(missing).toEqual([])
  })
})

/**
 * The site's own pages (the guides, the blog, the top-level pages; the
 * generated copies of `packages/vx/docs` are skipped — the source is
 * pinned by the safe half). A link is a URL — `../running-tasks/#…`,
 * `/vx/cli/#…` — so it resolves against the page's URL, and a page that
 * the import script generates is read from its source; a link with an
 * extension (an image, a config file) is a path beside the page.
 */
function sitePages(): string[] {
  return walk(path.join(repo, 'packages', 'vx-docs', 'src', 'content', 'docs'), '.md').filter(
    (p) => !readFileSync(p, 'utf8').startsWith('---\n# generated by '),
  )
}

const CONTENT = path.join(repo, 'packages', 'vx-docs', 'src', 'content', 'docs')
const CORE_DOCS = path.join(pkg, 'docs')

function siteSource(urlPath: string): string | undefined {
  const page = urlPath.replace(/^\/vx\//, '/').replace(/^\/|\/$/g, '')
  const core = page === 'overview' ? 'README' : page
  for (const candidate of [
    path.join(CORE_DOCS, `${core}.md`),
    path.join(CONTENT, `${page}.md`),
    path.join(CONTENT, page, 'index.md'),
  ]) {
    if (existsSync(candidate)) return candidate
  }
  return undefined
}

describe('every relative link on the site pages resolves', () => {
  it('`](../page/)` is a page, an asset link a file, and `#anchor` a heading by its rendered id', () => {
    const missing: string[] = []
    const slugs = new Map<string, Set<string>>()
    for (const file of sitePages()) {
      const rel = path.relative(CONTENT, file).split(path.sep).join('/')
      const urlDir = `/${rel.replace(/(^|\/)index\.md$/, '').replace(/\.md$/, '/')}`
      for (const { target, anchor } of proseLinks(readFileSync(file, 'utf8'))) {
        const link = `${rel}: ${target}${anchor === undefined ? '' : `#${anchor}`}`
        const source =
          target === ''
            ? file
            : /\.[a-z0-9]+$/i.test(target)
              ? path.resolve(path.dirname(file), target)
              : siteSource(path.posix.resolve(urlDir, `${target}/`))
        if (source === undefined || !existsSync(source)) {
          missing.push(link)
          continue
        }
        if (anchor === undefined || !source.endsWith('.md')) continue
        if (!slugs.has(source)) slugs.set(source, headingSlugs(readFileSync(source, 'utf8')))
        if (!slugs.get(source)!.has(anchor)) missing.push(link)
      }
    }
    expect(missing).toEqual([])
  })
})

describe('docs/README.md names every published plugin package', () => {
  it('the "published plugin packages" sentence names each non-private @vzn/vx-* sibling', () => {
    const readme = readFileSync(path.join(pkg, 'docs', 'README.md'), 'utf8')
    const sentence = /The published plugin packages are[\s\S]*?specifier/.exec(readme)
    expect(sentence).not.toBeNull()
    const named = new Set([...sentence![0].matchAll(/`(@vzn\/vx-[a-z-]+)`/g)].map((m) => m[1]!))
    const packagesDir = path.join(repo, 'packages')
    const published = readdirSync(packagesDir)
      .map((dir) => path.join(packagesDir, dir, 'package.json'))
      .filter((file) => existsSync(file))
      .map((file) => JSON.parse(readFileSync(file, 'utf8')) as { name: string; private?: boolean })
      .filter((manifest) => manifest.private !== true && manifest.name !== '@vzn/vx')
      .map((manifest) => manifest.name)
      .sort()
    expect([...named].sort()).toEqual(published)
  })
})

describe('docs/parity.md names suites that exist and the versions its suites cite', () => {
  it('every `tests/…` and `packages/…` deep pin resolves', () => {
    const doc = readFileSync(path.join(pkg, 'docs', 'parity.md'), 'utf8')
    const cited = [
      ...new Set([...doc.matchAll(/`((?:tests|packages)\/[\w./-]+)`/g)].map((m) => m[1]!)),
    ]
    expect(cited.length).toBeGreaterThan(40)
    const missing = cited.filter(
      (p) => !existsSync(p.startsWith('packages/') ? path.join(repo, p) : path.join(pkg, p)),
    )
    expect(missing).toEqual([])
  })

  it('the Turbo and Nx versions are the ones the two parity suites name', () => {
    const doc = readFileSync(path.join(pkg, 'docs', 'parity.md'), 'utf8')
    const turbo = /\(turborepo\.dev, ([\d.]+)\)/.exec(doc)
    const nx = /\(nx\.dev, (\d+)\)/.exec(doc)
    expect(turbo).not.toBeNull()
    expect(nx).not.toBeNull()
    expect(readFileSync(path.join(pkg, 'tests', 'parity-turbo.test.ts'), 'utf8')).toContain(
      `(turborepo.dev/docs, ${turbo![1]})`,
    )
    expect(readFileSync(path.join(pkg, 'tests', 'parity-nx.test.ts'), 'utf8')).toContain(
      `(nx.dev, ${nx![1]})`,
    )
  })
})

describe("architecture.md's orchestrator inventory is the directory", () => {
  const doc = readFileSync(path.join(pkg, 'docs', 'architecture.md'), 'utf8')
  const start = doc.indexOf('| Layer                  | Files')
  const table = doc.slice(start, doc.indexOf('```mermaid', start))

  it('names every file in src/orchestrator but its index', () => {
    // A table of forty-odd filenames is a snapshot the moment a file lands
    // beside it; nothing held it until item 355 (2026-09-19).
    expect(start).toBeGreaterThan(-1)
    const named = new Set([...table.matchAll(/`([a-z-]+\.ts)`/g)].map((m) => m[1]!))
    const onDisk = readdirSync(path.join(pkg, 'src', 'orchestrator'))
      .filter((f) => f.endsWith('.ts') && f !== 'index.ts')
      .sort()
    expect(onDisk.length).toBeGreaterThan(30)
    expect(onDisk.filter((f) => !named.has(f))).toEqual([])
    expect([...named].filter((f) => !existsSync(path.join(pkg, 'src', 'orchestrator', f)))).toEqual(
      [],
    )
  })

  it('counts its own layers — it said five of a six-row table', () => {
    const rows = table
      .split('\n')
      .filter((l) => l.startsWith('| ') && !l.startsWith('| ---') && !l.startsWith('| Layer'))
    const words = ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight']
    // The sentence wraps, which is why a grep for "five layers" found nothing.
    const flat = doc.replace(/\s+/g, ' ')
    expect(flat).toContain(`its files fall into ${words[rows.length]} layers`)
  })
})
