// Product, 2026-10-09: one example per verb and per config field, checked,
// so llms.txt never teaches an agent a command or a config vx refuses.
// The pages are the ones llms.txt serves: packages/vx/docs (history and
// design aside) and the site's hand-authored pages; blog and release posts
// quote refused commands on purpose and are not reference. Every `vx <verb>` line
// in a shell fence must name a verb and flags the parser accepts, every
// verb in the CLI contract must have one such line, and every config key in
// the config contract must appear in a config fence, which
// config-corpus.unsafe.test.ts loads through the validator and
// vx-docs' config-snippets test type-checks. Unsafe: it reads vx-docs.

import { readFileSync, readdirSync } from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'bun:test'
import { acceptedFlags } from '../src/cli/help.js'

const CORE = path.resolve(import.meta.dir, '..')
const REPO = path.resolve(CORE, '../..')

type Surface = { verbs: Record<string, string[]> }
type Schema = Record<string, { levels?: Record<string, string[]> }>
const surface = JSON.parse(
  readFileSync(path.join(CORE, 'tests/contract/cli-surface.json'), 'utf8'),
) as Surface
const schema = JSON.parse(
  readFileSync(path.join(CORE, 'tests/contract/config-schema.json'), 'utf8'),
) as Schema

function walk(dir: string): string[] {
  const out: string[] = []
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name)
    if (e.isDirectory()) {
      if (!['node_modules', 'history', 'design', 'blog', 'releases'].includes(e.name))
        out.push(...walk(p))
    } else if (/\.mdx?$/.test(e.name)) out.push(p)
  }
  return out
}

interface Fence {
  page: string
  lang: string
  code: string
}

const pages = [
  ...walk(path.join(CORE, 'docs')),
  ...walk(path.join(REPO, 'packages/vx-docs/src/content/docs')),
]
const fences: Fence[] = pages.flatMap((file) => {
  const text = readFileSync(file, 'utf8')
  // An imported copy of a packages/vx/docs page: the source is read already.
  if (text.includes('# generated by packages/vx-docs/scripts/import-docs.ts')) return []
  return [...text.matchAll(/^```(\w*)[^\n]*\n([\s\S]*?)^```/gm)].map((m) => ({
    page: path.relative(REPO, file),
    lang: m[1]!,
    code: m[2]!,
  }))
})

/** Each `vx <verb> <args>` a shell fence shows, with the flags it passes. */
function commands(f: Fence): { verb: string; flags: string[] }[] {
  if (!['', 'sh', 'bash', 'shell', 'console'].includes(f.lang)) return []
  const out: { verb: string; flags: string[] }[] = []
  for (const raw of f.code.split('\n')) {
    const line = raw
      .replace(/^\s*\$\s/, '')
      .replace(/\s+#.*$/, '')
      .replace(/\s\|\s.*$/, '')
      .replace(/\s[<>]\s.*$/, '')
      // Past `--` the words are the task's own.
      .replace(/\s--(?:\s.*)?$/, '')
      .trim()
    const m = /^(?:npx |bunx )?vx ([a-z]+)(.*)$/.exec(line)
    if (m === null || !(m[1]! in surface.verbs)) continue
    out.push({ verb: m[1]!, flags: m[2]!.split(/\s+/).filter((a) => a.startsWith('-')) })
  }
  return out
}

/** A config key a fence's object literal sets. */
const sets = (code: string, key: string): boolean =>
  new RegExp(`(?:^|[\\s{,])['"]?${key}['"]?\\s*:`, 'm').test(code)

const configs = fences
  .filter((f) => /^tsx?$/.test(f.lang) && /define(?:Project|Workspace)\(/.test(f.code))
  .map((f) => f.code)

describe('every example an agent reads from the docs', () => {
  it('passes only flags the verb accepts', () => {
    const bad: string[] = []
    let seen = 0
    for (const f of fences)
      for (const { verb, flags } of commands(f)) {
        seen++
        const ok = acceptedFlags(verb)
        for (const a of flags)
          if (!ok.includes(a.split('=')[0]!)) bad.push(`${f.page}: vx ${verb} ${a}`)
      }
    expect(bad).toEqual([])
    expect(seen).toBeGreaterThan(100)
  })

  it('shows every verb at least once', () => {
    const shown = new Set(fences.flatMap((f) => commands(f).map((c) => c.verb)))
    expect(Object.keys(surface.verbs).filter((v) => !shown.has(v))).toEqual([])
  })

  it('sets every config key in a checked config at least once', () => {
    const keys = new Set<string>()
    for (const { levels } of Object.values(schema))
      for (const list of Object.values(levels ?? {})) for (const k of list) keys.add(k)
    expect(keys.size).toBeGreaterThan(40)
    expect([...keys].filter((k) => !configs.some((c) => sets(c, k))).sort()).toEqual([])
  })

  // Controls: the parsers find what they are for, and miss what is absent.
  it('reads a command and a key the way the rows above do', () => {
    const f: Fence = { page: 'x', lang: 'sh', code: '$ npx vx run build --all --nope | jq .\n' }
    expect(commands(f)).toEqual([{ verb: 'run', flags: ['--all', '--nope'] }])
    expect(acceptedFlags('run')).not.toContain('--nope')
    expect(sets("  cache: { inputs: { files: ['x'] } },", 'files')).toBe(true)
    expect(sets('  profiles: 1', 'files')).toBe(false)
  })
})
