// A Yarn 2+ repo on Plug'n'Play has no node_modules/.bin, and a mapped
// task's bin exited 127 under vx: the report says so and names the ways
// out.
import { mkdtemp, rm, writeFile } from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import { expect, it } from 'bun:test'
import { migrateScripts } from '../src/workspace/migrate-scripts.js'

it("names Plug'n'Play when Yarn 2+ installs with it", async () => {
  const rows: Record<string, boolean> = {}
  for (const [label, lock, rc] of [
    [
      'berry, no yarnrc',
      '# This file is generated by running "yarn install".\n\n__metadata:\n  version: 8\n',
      null,
    ],
    [
      'berry, nodeLinker pnp',
      '# This file is generated by running "yarn install".\n\n__metadata:\n  version: 8\n',
      'nodeLinker: pnp\n',
    ],
    // CONTROLS: another linker, and Yarn 1.
    [
      'berry, node-modules',
      '# This file is generated by running "yarn install".\n\n__metadata:\n  version: 8\n',
      'nodeLinker: "node-modules"\n',
    ],
    [
      'berry, pnpm linker',
      '# This file is generated by running "yarn install".\n\n__metadata:\n  version: 8\n',
      'nodeLinker: pnpm\n',
    ],
    ['yarn 1', '# yarn lockfile v1\n', null],
  ] as [string, string, string | null][]) {
    const dir = await mkdtemp(path.join(os.tmpdir(), 'vx-init-pnp-'))
    try {
      await writeFile(path.join(dir, 'yarn.lock'), lock)
      if (rc !== null) await writeFile(path.join(dir, '.yarnrc.yml'), rc)
      const notes = migrateScripts([
        {
          name: 'a',
          dir,
          packageJson: { name: 'a', scripts: { b: 'tsc' } } as never,
          configPath: null,
        },
      ]).notes
      rows[label] = notes.some((n) => n.startsWith("Yarn Plug'n'Play installs this repo"))
    } finally {
      await rm(dir, { recursive: true, force: true })
    }
  }
  expect(rows).toEqual({
    'berry, no yarnrc': true,
    'berry, nodeLinker pnp': true,
    'berry, node-modules': false,
    'berry, pnpm linker': false,
    'yarn 1': false,
  })
})
