// vx promises Turbo and Nx users their config runs unchanged
// (`@vzn/vx-migrate`'s `turbo()` and `nx()`). This holds that promise to
// the upstream schemas: every key `turbo.json`, `nx.json` and
// `project.json` accept is read from a vendored copy of the schema
// (`tests/contract/turbo-nx/`, versions in its SOURCE.md) and must have a
// row in `tests/contract/turbo-nx-support.json` saying what vx does with
// it. A new upstream key fails here until it is classified; a row for a
// key the schema dropped fails too. `docs/turbo-nx-support.md` is rendered
// from the table.
//
// Regenerate the page after editing the table:
//   VX_UPDATE_CONTRACT=1 bun test tests/turbo-nx-support.test.ts

import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'bun:test'

const ROOT = path.resolve(import.meta.dir, '..')
const SCHEMAS = path.join(import.meta.dir, 'contract', 'turbo-nx')
const TABLE = path.join(import.meta.dir, 'contract', 'turbo-nx-support.json')
const PAGE = path.join(ROOT, 'docs', 'turbo-nx-support.md')

type Schema = {
  properties: Record<string, Schema>
  definitions: Record<string, Schema>
  additionalProperties?: Schema
  items?: { oneOf: Array<{ type?: string; properties?: Record<string, unknown> }> }
}

const STATUSES = ['supported', 'mapped', 'not-supported', 'not-applicable'] as const
type Status = (typeof STATUSES)[number]
interface Row {
  key: string
  status: Status
  reason: string
}

const read = (file: string): Schema =>
  JSON.parse(readFileSync(path.join(SCHEMAS, file), 'utf8')) as Schema

/** Every key a user can write, as `<file> <path>`, from the schemas alone. */
function schemaKeys(): string[] {
  const turbo = read('turbo-schema.json')
  const nx = read('nx-schema.json')
  const project = read('project-schema.json')
  const keys = (prefix: string, s: Schema): string[] =>
    Object.keys(s.properties).map((k) => `${prefix}${k}`)
  const d = turbo.definitions
  return [
    ...keys('turbo.json ', turbo),
    ...keys('turbo.json tasks.*.', d['Pipeline']!),
    ...keys('turbo.json tasks.*.inputs[].', d['StructuredInput']!),
    ...keys('turbo.json remoteCache.', d['RemoteCache']!),
    ...keys('turbo.json futureFlags.', d['FutureFlags']!),
    ...keys('turbo.json boundaries.', d['BoundariesConfig']!),
    ...keys('nx.json ', nx),
    ...keys('nx.json targetDefaults.*.', nx.definitions['targetDefaultArrayEntry']!),
    ...keys('project.json ', project),
    ...keys('project.json targets.*.', project.properties['targets']!.additionalProperties!),
    ...project.definitions['inputs']!.items!.oneOf.map((f) =>
      f.type === 'string'
        ? 'inputs: a string'
        : `inputs: {${Object.keys(f.properties!).join(', ')}}`,
    ),
  ]
}

const table = JSON.parse(readFileSync(TABLE, 'utf8')) as Row[]

const LABEL: Record<Status, string> = {
  supported: 'supported',
  mapped: 'mapped, with a note',
  'not-supported': 'not supported',
  'not-applicable': 'not applicable',
}

function render(rows: readonly Row[]): string {
  const source = readFileSync(path.join(SCHEMAS, 'SOURCE.md'), 'utf8')
  const versions = [...source.matchAll(/^\| `[\w-]+\.json` +\| `([^`]+)` +\| ([\d.]+) /gm)]
    .map((m) => `\`${m[1]}\` ${m[2]}`)
    .filter((v, i, all) => all.indexOf(v) === i)
  const out = [
    '# Turbo and Nx config support',
    '',
    '<!-- Generated by tests/turbo-nx-support.test.ts from tests/contract/turbo-nx-support.json; edit the table, not this page. -->',
    '',
    `Every key \`turbo.json\`, \`nx.json\` and \`project.json\` accept, read from the upstream schemas (${versions.join(', ')}), and what \`@vzn/vx-migrate\`'s \`turbo()\` or \`nx()\`, a temporary start before native config, does with it. A key a new upstream release adds fails vx's tests until it has a row here.`,
    '',
    '- **supported**: vx honours it with the same meaning.',
    '- **mapped, with a note**: vx honours it through a translation; the note says how it differs.',
    '- **not supported**: vx ignores or refuses it; the note says which.',
    '- **not applicable**: it configures something outside a task runner and its cache.',
  ]
  const sections: Array<[string, (k: string) => boolean]> = [
    ['`turbo.json`', (k) => k.startsWith('turbo.json ')],
    ['`nx.json`', (k) => k.startsWith('nx.json ')],
    ['`project.json`', (k) => k.startsWith('project.json ')],
    ['Nx `inputs` forms', (k) => k.startsWith('inputs: ')],
  ]
  for (const [title, has] of sections) {
    out.push('', `## ${title}`, '', '| Key | vx | Note |', '| --- | --- | --- |')
    for (const r of rows.filter((r) => has(r.key))) {
      const key = r.key.replace(/^(turbo|nx|project)\.json |^inputs: /, '')
      out.push(`| \`${key}\` | ${LABEL[r.status]} | ${r.reason.replace(/\|/g, '\\|')} |`)
    }
  }
  return out.join('\n') + '\n'
}

describe('Turbo and Nx config support (docs/turbo-nx-support.md)', () => {
  it('every key the upstream schemas accept has one row, and every row names such a key', () => {
    const want = schemaKeys()
    const have = table.map((r) => r.key)
    expect({
      unclassified: want.filter((k) => !have.includes(k)),
      notInSchema: have.filter((k) => !want.includes(k)),
      duplicated: have.filter((k, i) => have.indexOf(k) !== i),
    }).toEqual({ unclassified: [], notInSchema: [], duplicated: [] })
  })

  it('each row has a known status and a reason', () => {
    expect(
      table.filter((r) => !STATUSES.includes(r.status) || r.reason.trim() === '').map((r) => r.key),
    ).toEqual([])
  })

  // The row said `vx watch` "watches each task's declared inputs"; it
  // hears every change in a watched project, as cli.md states (J2-64).
  it("watchUsingTaskInputs' note says what cli.md says watch hears", () => {
    const row = table.find((r) => r.key === 'turbo.json futureFlags.watchUsingTaskInputs')!
    const cli = readFileSync(path.join(import.meta.dir, '..', 'docs', 'cli.md'), 'utf8')
    expect(cli.split(/\s+/).join(' ')).toContain(
      "We deliberately don't filter events against per-task `cache.inputs.files`",
    )
    expect(row.reason).toContain('re-runs on any change in a watched project')
  })

  it('the page is the table rendered', () => {
    const live = render(table)
    if (process.env['VX_UPDATE_CONTRACT'] === '1' && process.env['CI'] !== 'true') {
      writeFileSync(PAGE, live)
    }
    expect(live).toBe(readFileSync(PAGE, 'utf8'))
  })
})
