export function printHelp(): void {
  process.stdout.write(
    [
      'vx — open, extensible monorepo task runner',
      '',
      'Usage:',
      '  vx run [OPTIONS] [TASK | PKG#TASK] [-- forwarded-args...]',
      '  vx stats',
      '  vx cache prune [--older-than <duration>] [--max-size <bytes>]',
      '  vx help',
      '  vx version',
      '',
      'Selection (for run):',
      '  (default)                Run task in the project containing cwd.',
      '  -r, --recursive          Run task in every project that declares it.',
      '  -F, --filter <pattern>   pnpm-style filter (repeatable). Examples:',
      '                             foo, @scope/*, ./packages/foo, foo..., ...foo,',
      '                             foo^..., !foo',
      "  pkg#task                 Run a specific project's task directly.",
      '',
      'Behavior (for run):',
      '  -c, --concurrency <n>    Max parallel tasks (default: CPU count).',
      '      --ignore-depends-on  Skip dependsOn expansion; run only the requested task(s).',
      '      --no-cache           Skip cache reads AND writes.',
      '      --cache              No-op (parity with vite-task).',
      '  -v, --verbose            Print a detailed summary after the run.',
      '',
      'Argument forwarding (for run):',
      "  Anything after `--` is forwarded (shell-quoted) to the task's exec",
      '  command. The forwarded args are folded into the cache key, so',
      '  different args produce different cache entries.',
      '',
      'Cache management:',
      '  vx stats                            Print cache size + last-24h run/hit summary.',
      '  vx cache prune --older-than 30d     Evict entries last accessed > 30 days ago.',
      '  vx cache prune --max-size 1G        Keep total cache under 1 GB (LRU eviction).',
      '',
      '  Duration units: s, m, h, d. Size units: K, M, G, T (powers of 1024).',
      '',
    ].join('\n'),
  )
}
