export function printHelp(): void {
  process.stdout.write(
    [
      'vx — open, extensible monorepo task runner',
      '',
      'Usage:',
      '  vx run [OPTIONS] [TASK | PKG#TASK] [-- forwarded-args...]',
      '  vx serve [--port <n>] [--ui] [--open]',
      '  vx dev [--port <n>]',
      '  vx watch [OPTIONS] TASK [-- forwarded-args...]',
      '  vx cache prune [--older-than <duration>] [--max-size <bytes>]',
      '  vx lock [--check]',
      '  vx migrate [--from turbo|nx] [--dry] [--force]',
      '  vx upgrade [tag]',
      '  vx show [PROJECT[#TASK]] [--format pretty|json]',
      '  vx info',
      '  vx mcp [--stdio]',
      '  vx coordinator <tasks...> [--port <n>] [--host <h>] [--workers <n>]',
      '  vx worker --worker <coord-url> [--capacity <n>] [--label <l>]',
      '  vx help',
      '  vx version',
      '',
      'Selection (for run):',
      '  (default)                Run task in the project containing cwd.',
      '      --all                Run task in every project that declares it.',
      '      --filter <pat>       pnpm-style filter (repeatable). Examples:',
      '                             foo, @scope/*, ./packages/foo, foo..., ...foo,',
      '                             foo^..., !foo, [<since>]',
      '      --affected[=<base>]  Sugar for --filter "[<base>]". Default base =',
      '                             origin/HEAD (falls back to HEAD~1).',
      "  pkg#task                 Run a specific project's task directly.",
      '',
      'Execution (for run):',
      '      --concurrency <n>           Max parallel tasks (default: CPU count).',
      '      --excludeDependencies[=names]  Skip dependsOn edges. No value = all; comma list = specific names.',
      '      --no-cache                  Disable caching entirely (no reads, no writes, outputs left alone).',
      '      --force                     Re-execute everything (skip reads) but still refresh the cache (writes on).',
      '      --cache <spec>              Per-layer read/write control. Comma list of <layer>:<flags>',
      '                                  (layer = local|remote, flags ⊆ rw). A named layer is set EXACTLY',
      '                                  to its flags; unnamed layers keep their value. Examples:',
      '                                  local:rw,remote:r (remote read-only), remote: (remote off),',
      '                                  local:r (local read-only).',
      '      --frozen                    Load configs from vx-lock.json (CI; pair with vx lock --check).',
      '      --output-logs <mode>        full | errors-only | none — overrides the flow default',
      '                                  (focused without --all/--filter/--affected, broad with, full in CI).',
      '      --verbosity <n>             0=quiet, 1=verbose summary, 2+=debug (reserved).',
      '',
      'Planning (for run — skips execution):',
      '      --dry[=text|json]    Print the task graph + cache hit/miss prediction.',
      '      --graph[=<path>]     Emit Graphviz DOT (stdout if no path).',
      '',
      'Artifacts (for run):',
      '      --summarize[=<path>] Write per-run JSON to <cacheDir>/runs/<run_id>.json.',
      '      --profile[=<path>]   Write Chrome-trace JSON (default profile.json).',
      '',
      'Execution service (treat vx as a service; `vx run` becomes a client):',
      '  vx serve                 Foreground unified backend. While it runs, every',
      '                           `vx run` in this workspace DELEGATES to it over a',
      '                           WebSocket (work happens server-side; output streams',
      '                           back and renders identically). Also exposes the',
      '                           metrics JSON API at /v1/* and SSE / NDJSON event',
      '                           streams. No service running = runs execute in-process',
      '                           as before. Ctrl-C stops it.',
      '      --port <n>           Bind port (default: 4321, or an open one if taken).',
      '      --ui                 Also serve the bundled dashboard SPA at /.',
      '      --open               Open the UI in the default browser (implies --ui).',
      '  VX_SERVICE_URL=<origin>  Delegate to an explicit (e.g. hosted) service origin',
      '                           instead of a local one.',
      '',
      'Live devtools (needs the optional `devframe` package):',
      '  vx dev                   Foreground devtools hub: serves a devframe dev server',
      '                           and listens for runs on a per-workspace socket. While',
      '                           it runs, every `vx run` streams its events here (and',
      '                           still prints normally). Ctrl-C stops it. No hub running',
      '                           = runs behave exactly as before.',
      '      --port <n>           Preferred port for the dev server.',
      '      --ui                 (run) One-shot: serve a devframe devtool for THIS run',
      '                           only, staying up until Ctrl-C. Prefer `vx dev`.',
      '      --ui-port <n>        Preferred port for --ui (default 9999, scans if taken).',
      '',
      'Argument forwarding (for run):',
      "  Anything after `--` is forwarded (shell-quoted) to the task's exec",
      '  command. The forwarded args are folded into the cache key.',
      '',
      'Watch mode:',
      '  vx watch <task>            Initial run, then re-run on filesystem changes.',
      '                             Uses the same flags as `vx run` except --dry /',
      '                             --graph / --summarize / --profile. Press Ctrl+C',
      '                             to stop. Cache means most re-runs are near-zero',
      '                             cost (cache hits restore outputs + replay logs).',
      '',
      'Cache management:',
      '  vx cache prune --older-than 30d     Evict entries last accessed > 30 days ago.',
      '  vx cache prune --max-size 1G        Keep total cache under 1 GB (LRU eviction).',
      '',
      '  Duration units: s, m, h, d. Size units: K, M, G, T (powers of 1024).',
      '',
      'Introspection:',
      '  vx show              List every project: name, dir, declared task count.',
      "  vx show <project>    Print the project's LIVE resolved config (fresh",
      '                       evaluation, not the lock), one block per task.',
      "  vx show <pkg>#<task> Print a single task's resolved config.",
      '      --format <fmt>   pretty (default) | json.',
      '  vx info              Workspace doctor: vx/bun/git versions, project +',
      '                       task counts, cache dir/entries/size, recent runs,',
      '                       lock + remote-cache status.',
      '  vx stats             Deprecated: alias of vx info.',
      '  vx mcp               Model Context Protocol server (stdio) — exposes inspector',
      '                       RPCs as MCP tools for AI agents (Claude Code, Cursor, …).',
      '',
      'Distributed CI (scaffold):',
      '  vx coordinator       Per-run coordinator — holds graph + ready queue + fans',
      '                       tasks to attached workers over WebSocket.',
      '  vx worker            Stateless worker that pulls tasks from a coordinator.',
      '                       Content-addressed; multiple workers can join one run.',
      '',
      'Migration:',
      '  vx migrate           Generate vx.config.ts per package from turbo.json or an',
      '                       Nx project graph (.nx/workspace-data/project-graph.json).',
      '                       Unmappable settings become TODO(vx-migrate) comments;',
      '                       turbo global fields become a shared vx-preset.ts.',
      '      --dry            Print the generated files instead of writing them.',
      '      --force          Overwrite existing vx.config.* / vx-preset.ts files.',
      '',
      'Config lock:',
      '  vx lock              Evaluate every vx.config in the current environment and',
      '                       freeze the resolved objects into vx-lock.json. Plain runs',
      '                       always evaluate live; only `vx run --frozen` consumes the',
      '                       lock (CI reproducibility, frozen-env semantics).',
      '  vx lock --check      Audit the lock: file-changed hash report PLUS a full',
      '                       re-evaluation compared against the frozen objects. Exits 1',
      '                       on drift (e.g. configs that read env vars). Run it before',
      '                       `vx run --frozen` in CI.',
      '',
    ].join('\n'),
  )
}
