export function printHelp(): void {
  process.stdout.write(
    [
      'vx — open, extensible monorepo task runner',
      '',
      'Usage:',
      '  vx run [OPTIONS] [TASK | PKG#TASK] [-- forwarded-args...]',
      '  vx watch [OPTIONS] TASK [-- forwarded-args...]',
      '  vx cache prune [--older-than <duration>] [--max-size <bytes>]',
      '  vx lock [--check]',
      '  vx migrate [--from turbo|nx] [--dry] [--force]',
      '  vx upgrade [tag]',
      '  vx show [PROJECT[#TASK]] [--format pretty|json]',
      '  vx info',
      '  vx mcp [--stdio]',
      '  vx help',
      '  vx version',
      '',
      'Selection (for run):',
      '  (default)                Run task in the project containing cwd.',
      '      --all                Run task in every project that declares it.',
      '      --filter <pat>       pnpm-style filter (repeatable). Examples:',
      '                             foo, @scope/*, ./packages/foo, foo..., ...foo,',
      '                             foo^..., !foo, [<since>]',
      '      --affected[=<base>]  Sugar for --filter "[<base>]". Default base =',
      '                             origin/HEAD (falls back to HEAD~1).',
      "  pkg#task                 Run a specific project's task directly.",
      '',
      'Execution (for run):',
      '      --concurrency <n>           Max parallel tasks (default: CPU count).',
      '      --excludeDependencies[=names]  Skip dependsOn edges. No value = all; comma list = specific names.',
      '      --no-cache                  Disable caching entirely (no reads, no writes, outputs left alone).',
      '      --force                     Re-execute everything (skip reads) but still refresh the cache (writes on).',
      '      --cache <spec>              Per-layer read/write control. Comma list of <layer>:<flags>',
      '                                  (layer = local|remote, flags ⊆ rw). A named layer is set EXACTLY',
      '                                  to its flags; unnamed layers keep their value. Examples:',
      '                                  local:rw,remote:r (remote read-only), remote: (remote off),',
      '                                  local:r (local read-only).',
      '      --cache-dir <path>          Cache directory override (cwd-relative). Beats the workspace',
      '                                  cacheDir field + the .vx/cache default.',
      '      --retry <n>                 Re-run a failed task up to <n> more times (default for tasks',
      "                                  without their own exec.retries; explicit config wins). Doesn't",
      '                                  affect cache keys.',
      '      --timeout <ms>              Default per-task timeout for tasks without their own exec.timeout',
      '                                  (above VX_TASK_TIMEOUT env + workspace timeout). Kills + fails',
      '                                  a runaway task. Per-task exec.timeout always wins.',
      '      --frozen                    Load configs from vx-lock.json (CI; pair with vx lock --check).',
      '      --output-logs <mode>        full | errors-only | none — overrides the flow default',
      '                                  (focused without --all/--filter/--affected, broad with, full in CI).',
      '      --verbosity <n>             0=quiet, 1=verbose summary, 2+=debug (reserved).',
      '',
      'Planning (for run — skips execution):',
      '      --dry[=text|json]    Print the task graph + cache hit/miss prediction.',
      '      --graph[=<path>]     Emit Graphviz DOT (stdout if no path).',
      '',
      'Artifacts (for run):',
      '      --summarize[=<path>] Write per-run JSON to <cacheDir>/runs/<run_id>.json.',
      '      --profile[=<path>]   Write Chrome-trace JSON (default profile.json).',
      '',
      'Extensions (plugins):',
      '  vx core runs tasks in-process and nothing else. A dashboard, remote',
      '  cache, distributed execution, and telemetry export are provided by',
      '  PLUGINS declared in vx.workspace.ts — first-party or your own. Core',
      '  depends on none of them; a plain `vx run` never requires a plugin.',
      '  See the plugin guide: https://vznjs.github.io/vx/guides/plugins/',
      '',
      'Argument forwarding (for run):',
      "  Anything after `--` is forwarded (shell-quoted) to the task's exec",
      '  command. The forwarded args are folded into the cache key.',
      '',
      'Watch mode:',
      '  vx watch <task>            Initial run, then re-run on filesystem changes.',
      '                             Uses the same flags as `vx run` except --dry /',
      '                             --graph / --summarize / --profile. Press Ctrl+C',
      '                             to stop. Cache means most re-runs are near-zero',
      '                             cost (cache hits restore outputs + replay logs).',
      '',
      'Cache management:',
      '  vx cache prune --older-than 30d     Evict entries last accessed > 30 days ago.',
      '  vx cache prune --max-size 1G        Keep total cache under 1 GB (LRU eviction).',
      '',
      '  Duration units: s, m, h, d. Size units: K, M, G, T (powers of 1024).',
      '',
      'Introspection:',
      '  vx show              List every project: name, dir, declared task count.',
      "  vx show <project>    Print the project's LIVE resolved config (fresh",
      '                       evaluation, not the lock), one block per task.',
      "  vx show <pkg>#<task> Print a single task's resolved config.",
      '      --format <fmt>   pretty (default) | json.',
      '  vx info              Workspace doctor: vx/bun/git versions, project +',
      '                       task counts, cache dir/entries/size, recent runs,',
      '                       lock + remote-cache status.',
      '  vx stats             Deprecated: alias of vx info.',
      '  vx mcp               Model Context Protocol server (stdio) — exposes inspector',
      '                       RPCs as MCP tools for AI agents (Claude Code, Cursor, …).',
      '',
      'Migration:',
      '  vx migrate           Generate vx.config.ts per package from turbo.json or an',
      '                       Nx project graph (.nx/workspace-data/project-graph.json).',
      '                       Unmappable settings become TODO(vx-migrate) comments;',
      '                       turbo global fields become a shared vx-preset.ts.',
      '      --dry            Print the generated files instead of writing them.',
      '      --force          Overwrite existing vx.config.* / vx-preset.ts files.',
      '',
      'Config lock:',
      '  vx lock              Evaluate every vx.config in the current environment and',
      '                       freeze the resolved objects into vx-lock.json. Plain runs',
      '                       always evaluate live; only `vx run --frozen` consumes the',
      '                       lock (CI reproducibility, frozen-env semantics).',
      '  vx lock --check      Audit the lock: file-changed hash report PLUS a full',
      '                       re-evaluation compared against the frozen objects. Exits 1',
      '                       on drift (e.g. configs that read env vars). Run it before',
      '                       `vx run --frozen` in CI.',
      '',
    ].join('\n'),
  )
}
