{{- if eq .Values.mode "hosted" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vx-cloud.fullname" . }}-coordinator
  labels:
    {{- include "vx-cloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: coordinator
spec:
  type: ClusterIP
  selector:
    {{- include "vx-cloud.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: coordinator
  ports:
    - name: http
      port: {{ .Values.coordinator.port }}
      targetPort: http
      protocol: TCP
{{- end -}}
