{{- if and .Values.auth.token (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vx-cloud.fullname" . }}-auth
  labels:
    {{- include "vx-cloud.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.auth.token | quote }}
{{- end }}
{{- if and (or (eq .Values.cache.backend "s3") (eq .Values.cache.backend "r2")) (not .Values.cache.s3.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vx-cloud.fullname" . }}-cache
  labels:
    {{- include "vx-cloud.labels" . | nindent 4 }}
type: Opaque
stringData:
  accessKeyId: {{ .Values.cache.s3.accessKeyId | quote }}
  secretAccessKey: {{ .Values.cache.s3.secretAccessKey | quote }}
{{- end }}
{{- if and (eq .Values.insights.store "postgres") (not .Values.insights.postgres.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vx-cloud.fullname" . }}-insights
  labels:
    {{- include "vx-cloud.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.insights.postgres.secretKey }}: {{ .Values.insights.postgres.dsn | quote }}
{{- end }}
