// Every URL the old sidebar or the Guide linked still resolves
// (design/site-redo-2026-09.md: "Every old URL that moves gets a redirect";
// design/site-short-2026-09.md: every `guide/*` URL redirects to the
// landing's line for its idea). A page moves, and a link from outside, a
// search result or the blog still names the old path; it must land on a
// page, or on Astro's redirect page to one, at an id the page has.
//
// OLD_SIDEBAR is the sidebar as astro.config.mjs had it at 5b230b61, before
// the redo, and OLD_GUIDE the Guide's pages at 094c80f3, before the short
// site, written out by hand: generating either from the current config
// would list only what the config still has.

import { existsSync, readFileSync } from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'bun:test'
import { collectionPages } from './collection.js'

const DIST = path.resolve(import.meta.dir, '../dist')
const BASE = (process.env['BASE_PATH'] ?? '/vx').replace(/\/?$/, '/')

const OLD_SIDEBAR = [
  // Learn
  'learn/what-is-task-orchestration/',
  'learn/caching/',
  'learn/correctness/',
  'learn/scheduling/',
  'learn/architecture/',
  'learn/extending/',
  'learn/choosing/',
  'learn/playground/',
  'learn/labs/',
  'learn/glossary/',
  // Get started
  'introduction/',
  'quickstart/',
  'add-to-existing-repo/',
  // Build your monorepo
  'guides/tasks/',
  'guides/caching/',
  'guides/task-dependencies/',
  'guides/running-tasks/',
  'guides/dev-tasks/',
  'guides/environment-variables/',
  'guides/sandboxing/',
  'guides/trusting-the-cache/',
  'guides/lockfiles/',
  'guides/remote-caching/',
  'guides/remote-execution/',
  'guides/ci/',
  'guides/workspace-config/',
  // Extending vx
  'guides/extensibility/',
  'guides/plugins/',
  'guides/otel-bridge/',
  'guides/mcp/',
  // Migrate to vx
  'migrate/from-turborepo/',
  'migrate/from-nx/',
  // Concepts
  'concepts/how-vx-works/',
  'concepts/why-vx-is-fast/',
  'caching/',
  'execution/',
  'comparison/',
  'parity/',
  // Reference
  'cli/',
  'schema/',
  'benchmarks/',
  // Internals
  'overview/',
  'architecture/',
  'optimizations/',
  'patterns/',
  'flows/',
]
// The Guide: its ten chapters and the labs page chapter 10 linked.
const OLD_GUIDE = [
  'guide/why/',
  'guide/tasks/',
  'guide/dependencies/',
  'guide/concurrency/',
  'guide/caching/',
  'guide/trust/',
  'guide/affected/',
  'guide/many-machines/',
  'guide/inside-vx/',
  'guide/try-it/',
  'guide/labs/',
]
// The Internals group also autogenerated one link per page under these.
const OLD_AUTOGENERATED = ['modules', 'design']

// The pages R3 merged into another, the Docs pages the six took in (each
// lands on the section of the page that took it), the old Learn pages and
// the Guide's chapters, each sent to the landing's line for the idea it
// taught (design/site-short-2026-09.md), the pages that moved whole, and
// where each old URL must land: resolving somewhere is not enough when a
// reader followed a link to one particular page.
const MERGED: Record<string, string> = {
  'introduction/': 'quickstart/',
  'add-to-existing-repo/': 'quickstart/#an-existing-repo',
  'guides/tasks/': 'guides/configure/#tasks-and-dependencies',
  'guides/task-dependencies/': 'guides/configure/#tasks-and-dependencies',
  'guides/caching/': 'guides/configure/#caching',
  'guides/trusting-the-cache/': 'guides/configure/#caching',
  'guides/environment-variables/': 'guides/configure/#environment-variables',
  'guides/dev-tasks/': 'guides/configure/#dev-tasks',
  'guides/workspace-config/': 'guides/configure/#workspace-config',
  'guides/lockfiles/': 'guides/configure/#lockfiles',
  'guides/running-tasks/': 'guides/ci/#run-and-filter',
  'guides/remote-caching/': 'guides/ci/#remote-cache',
  'guides/remote-execution/': 'guides/ci/#remote-execution',
  'guides/extensibility/': 'guides/plugins/',
  'guides/otel-bridge/': 'guides/plugins/#opentelemetry',
  'guides/mcp/': 'guides/plugins/#vx-mcp',
  'migrate/from-turborepo/': 'guides/migrate/#turborepo',
  'migrate/from-nx/': 'guides/migrate/#nx',
  'concepts/how-vx-works/': '#plugins',
  'learn/what-is-task-orchestration/': '#tasks',
  'learn/caching/': '#cache',
  'learn/correctness/': '#sandbox',
  'learn/scheduling/': '#parallel',
  'learn/architecture/': '#plugins',
  'learn/extending/': '#plugins',
  'learn/playground/': 'playground/',
  'learn/labs/': 'playground/',
  'learn/choosing/': 'compare/',
  'learn/glossary/': 'glossary/',
  'guide/why/': '#one-run',
  'guide/tasks/': '#tasks',
  'guide/dependencies/': '#tasks',
  'guide/concurrency/': '#parallel',
  'guide/caching/': '#cache',
  'guide/trust/': '#sandbox',
  'guide/affected/': '#changed',
  'guide/many-machines/': '#extensible',
  'guide/inside-vx/': '#plugins',
  'guide/try-it/': 'playground/',
  'guide/labs/': 'playground/',
}

/** Where Astro's static redirect page sends the reader, if `html` is one. */
function redirectTarget(html: string): string | undefined {
  return /<meta http-equiv="refresh" content="\d+;\s*url=([^"]+)"/i.exec(html)?.[1]
}

/** Why `rel` does not resolve in dist/, following one redirect; undefined when it does.
 *  A redirect to a section lands only when the target page has that id. */
function miss(rel: string): string | undefined {
  const file = path.join(DIST, rel, 'index.html')
  if (!existsSync(file)) return `${rel}: no page and no redirect`
  const to = redirectTarget(readFileSync(file, 'utf8'))
  if (to === undefined) return undefined
  if (!to.startsWith(BASE)) return `${rel}: redirects outside the site, to ${to}`
  const [page, anchor] = to.slice(BASE.length).split('#') as [string, string | undefined]
  const target = path.join(DIST, page, 'index.html')
  if (!existsSync(target)) return `${rel}: redirects to ${to}, which is not built`
  const html = readFileSync(target, 'utf8')
  if (redirectTarget(html) !== undefined) {
    return `${rel}: redirects to ${to}, which redirects again`
  }
  if (anchor !== undefined && !html.includes(` id="${anchor}"`)) {
    return `${rel}: redirects to ${to}, which has no such section`
  }
  return undefined
}

describe('every URL the old sidebar or the Guide linked', () => {
  it('resolves, as a page or a redirect to one', () => {
    expect([...OLD_SIDEBAR, ...OLD_GUIDE].map(miss).filter((m) => m !== undefined)).toEqual([])
  })

  it('sends every Guide URL somewhere the map names', () => {
    expect(OLD_GUIDE.filter((rel) => !(rel in MERGED))).toEqual([])
  })

  it('sends each merged or moved page to the page that took its place', () => {
    const got = Object.fromEntries(
      Object.keys(MERGED).map((rel) => [
        rel,
        redirectTarget(readFileSync(path.join(DIST, rel, 'index.html'), 'utf8')),
      ]),
    )
    expect(got).toEqual(
      Object.fromEntries(Object.entries(MERGED).map(([rel, to]) => [rel, `${BASE}${to}`])),
    )
  })

  it('including each page the internals groups listed by directory', () => {
    const pages = OLD_AUTOGENERATED.flatMap((d) => collectionPages(d))
    expect(pages.length).toBeGreaterThan(100)
    expect(pages.map(miss).filter((m) => m !== undefined)).toEqual([])
  })

  it('tells a page, a redirect and a missing path apart', () => {
    const redirect =
      '<!doctype html><title>Redirecting to: /vx/quickstart/</title><meta http-equiv="refresh" content="0;url=/vx/quickstart/"><meta name="robots" content="noindex">'
    expect(redirectTarget(redirect)).toBe('/vx/quickstart/')
    expect(redirectTarget(readFileSync(path.join(DIST, 'quickstart/index.html'), 'utf8'))).toBe(
      undefined,
    )
    expect(miss('quickstart/')).toBeUndefined()
    expect(miss('guides/mcp/')).toBeUndefined()
    expect(miss('no-such-page/')).toBe('no-such-page/: no page and no redirect')
  })
})
