// Every URL the old sidebar linked still resolves (design/site-redo-2026-09.md:
// "Every old URL that moves gets a redirect"). A page moves in the redo, and
// a link from outside, a search result or the blog still names the old path;
// it must land on a page, or on Astro's redirect page to one.
//
// OLD_SIDEBAR is the sidebar as astro.config.mjs had it at 5b230b61, before
// the redo, written out by hand: generating it from the current config would
// list only what the config still has.

import { existsSync, readFileSync } from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'bun:test'
import { collectionPages } from './collection.js'

const DIST = path.resolve(import.meta.dir, '../dist')
const BASE = (process.env['BASE_PATH'] ?? '/vx').replace(/\/?$/, '/')

const OLD_SIDEBAR = [
  // Learn
  'learn/what-is-task-orchestration/',
  'learn/caching/',
  'learn/correctness/',
  'learn/scheduling/',
  'learn/architecture/',
  'learn/extending/',
  'learn/choosing/',
  'learn/playground/',
  'learn/labs/',
  'learn/glossary/',
  // Get started
  'introduction/',
  'quickstart/',
  'add-to-existing-repo/',
  // Build your monorepo
  'guides/tasks/',
  'guides/caching/',
  'guides/task-dependencies/',
  'guides/running-tasks/',
  'guides/dev-tasks/',
  'guides/environment-variables/',
  'guides/sandboxing/',
  'guides/trusting-the-cache/',
  'guides/lockfiles/',
  'guides/remote-caching/',
  'guides/remote-execution/',
  'guides/ci/',
  'guides/workspace-config/',
  // Extending vx
  'guides/extensibility/',
  'guides/plugins/',
  'guides/otel-bridge/',
  'guides/mcp/',
  // Migrate to vx
  'migrate/from-turborepo/',
  'migrate/from-nx/',
  // Concepts
  'concepts/how-vx-works/',
  'concepts/why-vx-is-fast/',
  'caching/',
  'execution/',
  'comparison/',
  'parity/',
  // Reference
  'cli/',
  'schema/',
  'benchmarks/',
  // Internals
  'overview/',
  'architecture/',
  'optimizations/',
  'patterns/',
  'flows/',
]
// The Internals group also autogenerated one link per page under these.
const OLD_AUTOGENERATED = ['modules', 'design']

// The pages R3 merged into another (or, for how-vx-works, into chapter 9),
// and where each old URL must land: resolving somewhere is not enough when a
// reader followed a link to one particular page.
const MERGED: Record<string, string> = {
  'introduction/': 'quickstart/',
  'guides/trusting-the-cache/': 'guides/caching/',
  'guides/task-dependencies/': 'guides/tasks/',
  'guides/extensibility/': 'guides/plugins/',
  'concepts/how-vx-works/': 'guide/inside-vx/',
}

/** Where Astro's static redirect page sends the reader, if `html` is one. */
function redirectTarget(html: string): string | undefined {
  return /<meta http-equiv="refresh" content="\d+;\s*url=([^"]+)"/i.exec(html)?.[1]
}

/** Why `rel` does not resolve in dist/, following one redirect; undefined when it does. */
function miss(rel: string): string | undefined {
  const file = path.join(DIST, rel, 'index.html')
  if (!existsSync(file)) return `${rel}: no page and no redirect`
  const to = redirectTarget(readFileSync(file, 'utf8'))
  if (to === undefined) return undefined
  if (!to.startsWith(BASE)) return `${rel}: redirects outside the site, to ${to}`
  const target = path.join(DIST, to.slice(BASE.length), 'index.html')
  if (!existsSync(target)) return `${rel}: redirects to ${to}, which is not built`
  if (redirectTarget(readFileSync(target, 'utf8')) !== undefined) {
    return `${rel}: redirects to ${to}, which redirects again`
  }
  return undefined
}

describe('every URL the old sidebar linked', () => {
  it('resolves, as a page or a redirect to one', () => {
    expect(OLD_SIDEBAR.map(miss).filter((m) => m !== undefined)).toEqual([])
  })

  it('sends each merged page to the page it merged into', () => {
    const got = Object.fromEntries(
      Object.keys(MERGED).map((rel) => [
        rel,
        redirectTarget(readFileSync(path.join(DIST, rel, 'index.html'), 'utf8')),
      ]),
    )
    expect(got).toEqual(
      Object.fromEntries(Object.entries(MERGED).map(([rel, to]) => [rel, `${BASE}${to}`])),
    )
  })

  it('including each page the internals groups listed by directory', () => {
    const pages = OLD_AUTOGENERATED.flatMap((d) => collectionPages(d))
    expect(pages.length).toBeGreaterThan(100)
    expect(pages.map(miss).filter((m) => m !== undefined)).toEqual([])
  })

  it('tells a page, a redirect and a missing path apart', () => {
    const redirect =
      '<!doctype html><title>Redirecting to: /vx/guide/why/</title><meta http-equiv="refresh" content="0;url=/vx/guide/why/"><meta name="robots" content="noindex">'
    expect(redirectTarget(redirect)).toBe('/vx/guide/why/')
    expect(redirectTarget(readFileSync(path.join(DIST, 'quickstart/index.html'), 'utf8'))).toBe(
      undefined,
    )
    expect(miss('quickstart/')).toBeUndefined()
    expect(miss('no-such-page/')).toBe('no-such-page/: no page and no redirect')
  })
})
