// The site imports the repo's `docs/` tree (scripts/import-docs.ts) and
// lists pages by hand in the sidebars (src/nav/sections.ts). Two pages were
// imported and reachable from no sidebar entry (2026-09-03: the overview,
// i.e. docs/README.md, and a stale second pitch). This pins both directions:
// every page is named in a sidebar or is one of the kinds the redo keeps out
// of them on purpose, and every sidebar link has a page — a hand-listed
// sidebar cannot drift silently.
//
// Kept out on purpose (design/site-redo-2026-09.md): the internals, reached
// through the internals index at the end of the Reference, and the blog,
// which has its own.
//
// It reads only THIS project: the site's sidebar module, its `.gitignore`,
// and the generated content collection. The generated set is what the
// sidebar must agree with, and `import` produces it before this runs.

import { existsSync, readdirSync, readFileSync } from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'bun:test'
import { SIDEBAR } from '../src/nav/sections.js'
import { collectionPages } from './collection.js'

const SITE = path.resolve(import.meta.dir, '..')
const CONTENT = path.join(SITE, 'src/content/docs')

const INTERNALS = ['/overview/', '/architecture/', '/optimizations/', '/patterns/', '/flows/']
const OUT_OF_SIDEBAR = /^\/(?:modules|design|internals|blog)\//

/**
 * Top-level pages the last `import` generated, as file names. A generated
 * page carries the import script's frontmatter mark; the hand-authored
 * pages beside them (introduction, quickstart, …) do not and are tracked.
 */
function importedPages(): string[] {
  return readdirSync(CONTENT)
    .filter(
      (f) =>
        f.endsWith('.md') &&
        readFileSync(path.join(CONTENT, f), 'utf8').includes(
          '# generated by packages/vx-docs/scripts/import-docs.ts',
        ),
    )
    .sort()
}

type Item = { link?: string; items?: Item[] }
function links(items: readonly Item[]): string[] {
  return items.flatMap((i) =>
    i.items === undefined ? (i.link === undefined ? [] : [i.link]) : links(i.items),
  )
}

describe('docs site sidebar coverage', () => {
  const listed = links(SIDEBAR as Item[])

  // The site's .gitignore is the manifest of generated top-level pages:
  // import-docs.ts clears exactly that set before regenerating, so a source
  // deleted from docs/ cannot leave a stale page behind — but only while the
  // list and the tree agree.
  it('the site .gitignore lists exactly the imported top-level pages', () => {
    const ignored = readFileSync(path.join(SITE, '.gitignore'), 'utf8')
      .split('\n')
      .map((l) => l.trim())
      .filter((l) => l.startsWith('/src/content/docs/') && l.endsWith('.md'))
      .map((l) => l.slice('/src/content/docs/'.length))
      .sort()
    expect(ignored).toEqual(importedPages())
  })

  it('names every page but the internals and the blog', () => {
    const orphans = collectionPages()
      .map((p) => `/${p}`)
      .filter((u) => !listed.includes(u) && !INTERNALS.includes(u) && !OUT_OF_SIDEBAR.test(u))
    expect(orphans).toEqual([])
  })

  // The control for the row above: each kind it excuses exists, so the
  // excuse is not true of an empty set; the two pages the Reference took
  // from the old Learn section are listed; and no Learn or Guide page is
  // left, the playground the Guide hosted being a Docs page now.
  it('excuses only kinds of page that exist, and lists the glossary and the comparison', () => {
    const pages = collectionPages().map((p) => `/${p}`)
    expect(INTERNALS.filter((u) => !pages.includes(u))).toEqual([])
    for (const dir of ['modules', 'design', 'internals', 'blog']) {
      expect(pages.some((u) => u.startsWith(`/${dir}/`))).toBe(true)
    }
    expect(listed).toContain('/glossary/')
    expect(listed).toContain('/compare/')
    expect(listed).toContain('/playground/')
    expect(pages.filter((u) => /^\/(?:learn|guide)\//.test(u))).toEqual([])
  })

  it('links only to pages that exist, each once', () => {
    // Guides and concepts are authored here; the rest is generated by
    // `import`, which this task depends on — so the collection is complete
    // when the check runs.
    const missing = listed.filter((link) => {
      const rel = link.replace(/^\//, '').replace(/\/$/, '')
      return ![`${rel}.md`, `${rel}.mdx`, `${rel}/index.md`, `${rel}/index.mdx`].some((c) =>
        existsSync(path.join(CONTENT, c)),
      )
    })
    expect(missing).toEqual([])
    expect(new Set(listed).size).toBe(listed.length)
  })
})
