// The site's "Upgrading to 1.0" page, from git log: one entry per breaking
// commit (`type!:` or a `BREAKING CHANGE:` footer), newest first, with the
// footer as what changed and what to do. A commit's subject loses its
// squash-merge `(#N)`, so a branch's own commit and the one main gets read
// the same. tests/site-upgrading.unsafe.test.ts holds the page to the log.
//
//   bun packages/vx/scripts/upgrading.ts           # rewrite the page
//   bun packages/vx/scripts/upgrading.ts --check   # exit 1 if it would change
import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { commitsBetween, isBreaking, type Commit } from './release-notes.ts'

export const PAGE = path.resolve(
  import.meta.dir,
  '../../vx-docs/src/content/docs/guides/upgrading.md',
)

const HEADER = /^(\w+)(?:\(([^)]*)\))?!?: (.+?)(?: \(#\d+\))?$/

/** A breaking commit's title line and its footer, as the page shows them. */
function entry({ subject, body }: Commit): { title: string; footer: string } {
  const m = HEADER.exec(subject)
  const title = (m === null ? subject : `${m[2] ? `${m[2]}: ` : ''}${m[3]}`).replace(
    / \([A-Z][A-Z0-9]*-\d+\)$/,
    '',
  )
  const lines = body.split('\n')
  const start = lines.findIndex((l) => /^BREAKING[ -]CHANGE: /.test(l))
  if (start === -1) return { title, footer: '' }
  const end = lines.findIndex((l, i) => i > start && l.trim() === '')
  const footer = lines
    .slice(start, end === -1 ? undefined : end)
    .join(' ')
    .replace(/^BREAKING[ -]CHANGE: /, '')
    .replace(/\s+/g, ' ')
    .trim()
  return { title, footer }
}

export function page(commits: readonly Commit[]): string {
  // A squash commit's body can carry an earlier commit's footer again
  // (#2527 repeated #2521's); the commit that made the change keeps it.
  const seen = new Set<string>()
  const entries = commits
    .filter(isBreaking)
    .map(entry)
    .filter(({ footer }) => footer === '' || (!seen.has(footer) && !!seen.add(footer)))
    .toReversed()
    .map(({ title, footer }) => `## ${title}\n\n${footer || 'No migration note.'}\n`)
  return `---
title: Upgrading to 1.0
description: Every breaking change before 1.0, newest first, and what to do about it.
---

<!-- Generated by packages/vx/scripts/upgrading.ts from git log; do not hand-edit. -->

Before 1.0 a release may break what the last one did. Each heading below
is a breaking commit (\`type!:\` or a \`BREAKING CHANGE:\` footer), newest
first; its text is that footer: what changed and what to do.

${entries.join('\n')}`
}

if (import.meta.main) {
  const want = page(commitsBetween('', 'HEAD', path.resolve(import.meta.dir, '../../..')))
  if (process.argv.includes('--check')) {
    if (readFileSync(PAGE, 'utf8') !== want) {
      process.stderr.write('guides/upgrading.md does not match git log; run the script\n')
      process.exit(1)
    }
  } else writeFileSync(PAGE, want)
}
