// `vx completions <shell>` — a bash / zsh / fish script over the verb table
// and each verb's help cut, so the verbs and every flag of each complete
// from the one text `vx <verb> --help` prints. Plugin verbs of the
// workspace around the cwd are included at generation time; task and
// project names are not (a completion that evaluates configs on every
// Tab is the wrong price).

import { CORE_VERBS, seeHelp, verbHelpText } from './help.js'

export type CompletionShell = 'bash' | 'zsh' | 'fish'
const SHELLS: readonly CompletionShell[] = ['bash', 'zsh', 'fish']

/** Every `--flag` the verb's help cut names, plus `--help`; deduped, in order of appearance. */
export function verbFlags(verb: string): string[] {
  const flags = new Set<string>(['--help'])
  for (const f of verbHelpText(verb).match(/--[a-zA-Z][a-zA-Z-]*/g) ?? []) flags.add(f)
  return [...flags]
}

/** The words that follow `vx <verb>` besides flags: subcommands and fixed choices. */
const VERB_WORDS: Readonly<Record<string, readonly string[]>> = {
  cache: ['prune'],
  completions: [...SHELLS],
}

export function completionScript(shell: CompletionShell, verbs: readonly string[]): string {
  const table = verbs.map((v) => ({
    verb: v,
    // A plugin verb owns its own arguments; only `--help` is known here.
    words: [
      ...(VERB_WORDS[v] ?? []),
      ...((CORE_VERBS as readonly string[]).includes(v) ? verbFlags(v) : ['--help']),
    ],
  }))
  switch (shell) {
    case 'bash':
      return [
        '# vx completions — generated by `vx completions bash`',
        '_vx() {',
        '  local cur="${COMP_WORDS[COMP_CWORD]}"',
        '  local verb="${COMP_WORDS[1]}"',
        '  if [ "$COMP_CWORD" -eq 1 ]; then',
        `    COMPREPLY=($(compgen -W "${verbs.join(' ')}" -- "$cur"))`,
        '    return',
        '  fi',
        '  case "$verb" in',
        ...table.map(
          (t) => `    ${t.verb}) COMPREPLY=($(compgen -W "${t.words.join(' ')}" -- "$cur")) ;;`,
        ),
        '    *) COMPREPLY=() ;;',
        '  esac',
        '}',
        'complete -F _vx vx',
        '',
      ].join('\n')
    case 'zsh':
      return [
        '#compdef vx',
        '# vx completions — generated by `vx completions zsh`',
        '_vx() {',
        '  if (( CURRENT == 2 )); then',
        `    compadd -- ${verbs.join(' ')}`,
        '    return',
        '  fi',
        '  case "${words[2]}" in',
        ...table.map((t) => `    ${t.verb}) compadd -- ${t.words.join(' ')} ;;`),
        '  esac',
        '}',
        'compdef _vx vx',
        '',
      ].join('\n')
    case 'fish':
      return [
        '# vx completions — generated by `vx completions fish`',
        'complete -c vx -f',
        ...verbs.map((v) => `complete -c vx -n __fish_use_subcommand -a ${v}`),
        ...table.flatMap((t) =>
          t.words.map((w) =>
            w.startsWith('--')
              ? `complete -c vx -n "__fish_seen_subcommand_from ${t.verb}" -l ${w.slice(2)}`
              : `complete -c vx -n "__fish_seen_subcommand_from ${t.verb}" -a ${w}`,
          ),
        ),
        '',
      ].join('\n')
  }
}

export async function completionsCmd(
  args: readonly string[],
  pluginVerbs: readonly string[],
): Promise<number> {
  const shell = args[0]
  if (args.length !== 1 || !(SHELLS as readonly string[]).includes(shell ?? '')) {
    process.stderr.write(
      `vx completions: expected one shell — bash, zsh or fish${shell !== undefined && args.length === 1 ? ` (got ${shell})` : ''}${seeHelp('completions')}\n`,
    )
    return 1
  }
  const verbs = [...CORE_VERBS.filter((v) => v !== 'help' && v !== 'version'), 'help', 'version']
  for (const v of pluginVerbs) if (!verbs.includes(v)) verbs.push(v)
  process.stdout.write(completionScript(shell as CompletionShell, verbs))
  return 0
}
