// `vx completions <shell>` — a bash / zsh / fish script over the verb table
// and each verb's Usage line in the help text, so the verbs and every flag
// of each complete from the one text `vx <verb> --help` prints. Plugin verbs of the
// workspace around the cwd are included at generation time; task and
// project names are not (a completion that evaluates configs on every
// Tab is the wrong price).

import { acceptedFlags, CORE_VERBS, flagHint, seeHelp } from './help.js'
import { nearest } from '../util/index.js'

/** A flag whose value is one of a fixed set; the tests hold each to its parser. */
export const FLAG_VALUES: Readonly<Record<string, readonly string[]>> = {
  '--format': ['pretty', 'json'],
  '--output-logs': ['full', 'errors-only', 'hash-only', 'none'],
  '--download': ['all', 'toplevel', 'none'],
}

export type CompletionShell = 'bash' | 'zsh' | 'fish'
const SHELLS: readonly CompletionShell[] = ['bash', 'zsh', 'fish']

/**
 * `--help` and every flag the verb accepts. Not every `--flag` its help cut
 * mentions: the cut's prose names other verbs' flags, and `vx watch`
 * completed only `--dry --graph --summarize --profile`, the four its line
 * says it refuses, while `vx show` offered `--run` and `--list`.
 */
export function verbFlags(verb: string): string[] {
  return [...new Set(['--help', ...acceptedFlags(verb)])]
}

/** The words that follow `vx <verb>` besides flags: subcommands and fixed choices. */
const VERB_WORDS: Readonly<Record<string, readonly string[]>> = {
  cache: ['prune'],
  completions: [...SHELLS],
}

export function completionScript(shell: CompletionShell, verbs: readonly string[]): string {
  const table = verbs.map((v) => ({
    verb: v,
    // A plugin verb owns its own arguments; only `--help` is known here.
    words: [
      ...(VERB_WORDS[v] ?? []),
      ...((CORE_VERBS as readonly string[]).includes(v) ? verbFlags(v) : ['--help']),
    ],
  }))
  // `vx run --output-logs <Tab>` offered the flags again; a flag with a
  // fixed value set offers that set.
  const values = table.flatMap((t) =>
    t.words.flatMap((w) => {
      const vs = FLAG_VALUES[w]
      return vs === undefined ? [] : [{ verb: t.verb, flag: w, values: vs.join(' ') }]
    }),
  )
  switch (shell) {
    case 'bash':
      return [
        '# vx completions — generated by `vx completions bash`',
        '_vx() {',
        '  local cur="${COMP_WORDS[COMP_CWORD]}"',
        '  local verb="${COMP_WORDS[1]}"',
        '  local prev="${COMP_WORDS[COMP_CWORD-1]}"',
        '  if [ "$COMP_CWORD" -eq 1 ]; then',
        `    COMPREPLY=($(compgen -W "${verbs.join(' ')}" -- "$cur"))`,
        '    return',
        '  fi',
        // bash splits `--format=js` at the `=` (COMP_WORDBREAKS).
        '  if [ "$cur" = "=" ]; then',
        '    cur=""',
        '  elif [ "$prev" = "=" ]; then',
        '    prev="${COMP_WORDS[COMP_CWORD-2]}"',
        '  fi',
        '  case "$verb $prev" in',
        ...values.map(
          (v) =>
            `    "${v.verb} ${v.flag}") COMPREPLY=($(compgen -W "${v.values}" -- "$cur")); return ;;`,
        ),
        '  esac',
        '  case "$verb" in',
        ...table.map(
          (t) => `    ${t.verb}) COMPREPLY=($(compgen -W "${t.words.join(' ')}" -- "$cur")) ;;`,
        ),
        '    *) COMPREPLY=() ;;',
        '  esac',
        '}',
        'complete -F _vx vx',
        '',
      ].join('\n')
    case 'zsh':
      return [
        '#compdef vx',
        '# vx completions — generated by `vx completions zsh`',
        '_vx() {',
        '  if (( CURRENT == 2 )); then',
        `    compadd -- ${verbs.join(' ')}`,
        '    return',
        '  fi',
        '  case "${words[2]} ${words[CURRENT-1]}" in',
        ...values.map((v) => `    "${v.verb} ${v.flag}") compadd -- ${v.values}; return ;;`),
        '  esac',
        '  case "${words[2]}" in',
        ...table.map((t) => `    ${t.verb}) compadd -- ${t.words.join(' ')} ;;`),
        '  esac',
        '}',
        // Autoloaded from $fpath (the `#compdef` file), this body runs on
        // the first Tab: it must complete then, not only define `_vx`, or
        // that Tab rings the bell. Sourced, it registers instead.
        'if [[ "${funcstack[1]}" == _vx ]]; then',
        '  _vx "$@"',
        'else',
        '  compdef _vx vx',
        'fi',
        '',
      ].join('\n')
    case 'fish':
      return [
        '# vx completions — generated by `vx completions fish`',
        'complete -c vx -f',
        ...verbs.map((v) => `complete -c vx -n __fish_use_subcommand -a ${v}`),
        ...table.flatMap((t) =>
          t.words.map((w) => {
            const on = `complete -c vx -n "__fish_seen_subcommand_from ${t.verb}"`
            if (!w.startsWith('--')) return `${on} -a ${w}`
            const vs = FLAG_VALUES[w]
            return vs === undefined
              ? `${on} -l ${w.slice(2)}`
              : `${on} -l ${w.slice(2)} -x -a "${vs.join(' ')}"`
          }),
        ),
        '',
      ].join('\n')
  }
}

export async function completionsCmd(
  args: readonly string[],
  pluginVerbs: readonly string[],
): Promise<number> {
  const shell = args[0]
  if (args.length !== 1 || !(SHELLS as readonly string[]).includes(shell ?? '')) {
    const flag = args.find((a) => a.startsWith('-'))
    if (flag !== undefined) {
      process.stderr.write(
        `vx completions: unknown flag: ${flag}${flagHint('completions', flag)}${seeHelp('completions')}\n`,
      )
      return 1
    }
    const one = shell !== undefined && args.length === 1
    // One edit: shell names are three or four letters, so two edits took
    // `tcsh` to `bash`, a different shell.
    const best = one ? nearest(shell, SHELLS, 1) : undefined
    process.stderr.write(
      `vx completions: expected one shell — bash, zsh or fish${one ? ` (got ${shell})` : ''}${best === undefined ? '' : `. Did you mean ${best}?`}${seeHelp('completions')}\n`,
    )
    return 1
  }
  const verbs = [...CORE_VERBS.filter((v) => v !== 'help' && v !== 'version'), 'help', 'version']
  // No overlap to skip: the workspace load refuses a plugin verb named like a core one.
  verbs.push(...pluginVerbs)
  process.stdout.write(completionScript(shell as CompletionShell, verbs))
  return 0
}
